language: java

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

sudo: false

branches:
  except:
    - javame
    
before_install:
 - chmod +x gradlew

after_success:
  - ./gradlew cobertura coveralls
#  - mvn cobertura:cobertura coveralls:report
