//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleDropWhile.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleDropWhile")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleDropWhile
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleDropWhile 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleDropWhile 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleDropWhile

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleDropWhile_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleDropWhile || defined(INCLUDE_CASDoubleDropWhile))
#define CASDoubleDropWhile_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@class CASPrimitiveIterator_OfDouble;
@protocol CASDoublePredicate;

@interface CASDoubleDropWhile : CASPrimitiveExtIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                        withCASDoublePredicate:(id<CASDoublePredicate>)predicate;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleDropWhile)

FOUNDATION_EXPORT void CASDoubleDropWhile_initWithCASPrimitiveIterator_OfDouble_withCASDoublePredicate_(CASDoubleDropWhile *self, CASPrimitiveIterator_OfDouble *iterator, id<CASDoublePredicate> predicate);

FOUNDATION_EXPORT CASDoubleDropWhile *new_CASDoubleDropWhile_initWithCASPrimitiveIterator_OfDouble_withCASDoublePredicate_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoublePredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleDropWhile *create_CASDoubleDropWhile_initWithCASPrimitiveIterator_OfDouble_withCASDoublePredicate_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoublePredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleDropWhile)

@compatibility_alias ComAnnimonStreamOperatorDoubleDropWhile CASDoubleDropWhile;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleDropWhile")
