//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleArray.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleArray")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleArray
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleArray 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleArray 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleArray

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleArray_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleArray || defined(INCLUDE_CASDoubleArray))
#define CASDoubleArray_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class IOSDoubleArray;
@class JavaLangBoolean;
@class JavaLangDouble;

@interface CASDoubleArray : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithDoubleArray:(IOSDoubleArray *)values;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleArray)

FOUNDATION_EXPORT void CASDoubleArray_initWithDoubleArray_(CASDoubleArray *self, IOSDoubleArray *values);

FOUNDATION_EXPORT CASDoubleArray *new_CASDoubleArray_initWithDoubleArray_(IOSDoubleArray *values) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleArray *create_CASDoubleArray_initWithDoubleArray_(IOSDoubleArray *values);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleArray)

@compatibility_alias ComAnnimonStreamOperatorDoubleArray CASDoubleArray;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleArray")
