//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoublePeek.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoublePeek")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoublePeek
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoublePeek 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoublePeek 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoublePeek

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoublePeek_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoublePeek || defined(INCLUDE_CASDoublePeek))
#define CASDoublePeek_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@protocol CASDoubleConsumer;

@interface CASDoublePeek : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                         withCASDoubleConsumer:(id<CASDoubleConsumer>)action;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoublePeek)

FOUNDATION_EXPORT void CASDoublePeek_initWithCASPrimitiveIterator_OfDouble_withCASDoubleConsumer_(CASDoublePeek *self, CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleConsumer> action);

FOUNDATION_EXPORT CASDoublePeek *new_CASDoublePeek_initWithCASPrimitiveIterator_OfDouble_withCASDoubleConsumer_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleConsumer> action) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoublePeek *create_CASDoublePeek_initWithCASPrimitiveIterator_OfDouble_withCASDoubleConsumer_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleConsumer> action);

J2OBJC_TYPE_LITERAL_HEADER(CASDoublePeek)

@compatibility_alias ComAnnimonStreamOperatorDoublePeek CASDoublePeek;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoublePeek")
