//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleSkip.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSkip")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleSkip
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSkip 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSkip 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleSkip

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleSkip_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSkip || defined(INCLUDE_CASDoubleSkip))
#define CASDoubleSkip_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangLong;

@interface CASDoubleSkip : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                                      withLong:(int64_t)n;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleSkip)

FOUNDATION_EXPORT void CASDoubleSkip_initWithCASPrimitiveIterator_OfDouble_withLong_(CASDoubleSkip *self, CASPrimitiveIterator_OfDouble *iterator, int64_t n);

FOUNDATION_EXPORT CASDoubleSkip *new_CASDoubleSkip_initWithCASPrimitiveIterator_OfDouble_withLong_(CASPrimitiveIterator_OfDouble *iterator, int64_t n) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleSkip *create_CASDoubleSkip_initWithCASPrimitiveIterator_OfDouble_withLong_(CASPrimitiveIterator_OfDouble *iterator, int64_t n);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleSkip)

@compatibility_alias ComAnnimonStreamOperatorDoubleSkip CASDoubleSkip;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSkip")
