//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleMapToInt.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToInt")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleMapToInt
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToInt 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToInt 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleMapToInt

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleMapToInt_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToInt || defined(INCLUDE_CASDoubleMapToInt))
#define CASDoubleMapToInt_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class CASPrimitiveIterator_OfDouble;
@class JavaLangBoolean;
@class JavaLangInteger;
@protocol CASDoubleToIntFunction;

@interface CASDoubleMapToInt : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                    withCASDoubleToIntFunction:(id<CASDoubleToIntFunction>)mapper;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleMapToInt)

FOUNDATION_EXPORT void CASDoubleMapToInt_initWithCASPrimitiveIterator_OfDouble_withCASDoubleToIntFunction_(CASDoubleMapToInt *self, CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleToIntFunction> mapper);

FOUNDATION_EXPORT CASDoubleMapToInt *new_CASDoubleMapToInt_initWithCASPrimitiveIterator_OfDouble_withCASDoubleToIntFunction_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleToIntFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleMapToInt *create_CASDoubleMapToInt_initWithCASPrimitiveIterator_OfDouble_withCASDoubleToIntFunction_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleToIntFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleMapToInt)

@compatibility_alias ComAnnimonStreamOperatorDoubleMapToInt CASDoubleMapToInt;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToInt")
