//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleFlatMap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleFlatMap")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleFlatMap
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleFlatMap 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleFlatMap 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleFlatMap

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleFlatMap_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleFlatMap || defined(INCLUDE_CASDoubleFlatMap))
#define CASDoubleFlatMap_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@protocol CASDoubleFunction;

@interface CASDoubleFlatMap : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                         withCASDoubleFunction:(id<CASDoubleFunction>)mapper;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleFlatMap)

FOUNDATION_EXPORT void CASDoubleFlatMap_initWithCASPrimitiveIterator_OfDouble_withCASDoubleFunction_(CASDoubleFlatMap *self, CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleFunction> mapper);

FOUNDATION_EXPORT CASDoubleFlatMap *new_CASDoubleFlatMap_initWithCASPrimitiveIterator_OfDouble_withCASDoubleFunction_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleFlatMap *create_CASDoubleFlatMap_initWithCASPrimitiveIterator_OfDouble_withCASDoubleFunction_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleFlatMap)

@compatibility_alias ComAnnimonStreamOperatorDoubleFlatMap CASDoubleFlatMap;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleFlatMap")
