//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntFlatMap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntFlatMap")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntFlatMap
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntFlatMap 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntFlatMap 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntFlatMap

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntFlatMap_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntFlatMap || defined(INCLUDE_CASIntFlatMap))
#define CASIntFlatMap_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@protocol CASIntFunction;

@interface CASIntFlatMap : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator
                                         withCASIntFunction:(id<CASIntFunction>)mapper;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntFlatMap)

FOUNDATION_EXPORT void CASIntFlatMap_initWithCASPrimitiveIterator_OfInt_withCASIntFunction_(CASIntFlatMap *self, CASPrimitiveIterator_OfInt *iterator, id<CASIntFunction> mapper);

FOUNDATION_EXPORT CASIntFlatMap *new_CASIntFlatMap_initWithCASPrimitiveIterator_OfInt_withCASIntFunction_(CASPrimitiveIterator_OfInt *iterator, id<CASIntFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntFlatMap *create_CASIntFlatMap_initWithCASPrimitiveIterator_OfInt_withCASIntFunction_(CASPrimitiveIterator_OfInt *iterator, id<CASIntFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASIntFlatMap)

@compatibility_alias ComAnnimonStreamOperatorIntFlatMap CASIntFlatMap;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntFlatMap")
