//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntMapToLong.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntMapToLong")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntMapToLong
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntMapToLong 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntMapToLong 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntMapToLong

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntMapToLong_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntMapToLong || defined(INCLUDE_CASIntMapToLong))
#define CASIntMapToLong_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class CASPrimitiveIterator_OfInt;
@class JavaLangBoolean;
@class JavaLangLong;
@protocol CASIntToLongFunction;

@interface CASIntMapToLong : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator
                                   withCASIntToLongFunction:(id<CASIntToLongFunction>)mapper;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntMapToLong)

FOUNDATION_EXPORT void CASIntMapToLong_initWithCASPrimitiveIterator_OfInt_withCASIntToLongFunction_(CASIntMapToLong *self, CASPrimitiveIterator_OfInt *iterator, id<CASIntToLongFunction> mapper);

FOUNDATION_EXPORT CASIntMapToLong *new_CASIntMapToLong_initWithCASPrimitiveIterator_OfInt_withCASIntToLongFunction_(CASPrimitiveIterator_OfInt *iterator, id<CASIntToLongFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntMapToLong *create_CASIntMapToLong_initWithCASPrimitiveIterator_OfInt_withCASIntToLongFunction_(CASPrimitiveIterator_OfInt *iterator, id<CASIntToLongFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASIntMapToLong)

@compatibility_alias ComAnnimonStreamOperatorIntMapToLong CASIntMapToLong;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntMapToLong")
