//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntMap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntMap")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntMap
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntMap 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntMap 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntMap

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntMap_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntMap || defined(INCLUDE_CASIntMap))
#define CASIntMap_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@protocol CASIntUnaryOperator;

@interface CASIntMap : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator
                                    withCASIntUnaryOperator:(id<CASIntUnaryOperator>)mapper;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntMap)

FOUNDATION_EXPORT void CASIntMap_initWithCASPrimitiveIterator_OfInt_withCASIntUnaryOperator_(CASIntMap *self, CASPrimitiveIterator_OfInt *iterator, id<CASIntUnaryOperator> mapper);

FOUNDATION_EXPORT CASIntMap *new_CASIntMap_initWithCASPrimitiveIterator_OfInt_withCASIntUnaryOperator_(CASPrimitiveIterator_OfInt *iterator, id<CASIntUnaryOperator> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntMap *create_CASIntMap_initWithCASPrimitiveIterator_OfInt_withCASIntUnaryOperator_(CASPrimitiveIterator_OfInt *iterator, id<CASIntUnaryOperator> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASIntMap)

@compatibility_alias ComAnnimonStreamOperatorIntMap CASIntMap;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntMap")
