//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntScan.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntScan")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntScan
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntScan 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntScan 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntScan

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntScan_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntScan || defined(INCLUDE_CASIntScan))
#define CASIntScan_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@class CASPrimitiveIterator_OfInt;
@protocol CASIntBinaryOperator;

@interface CASIntScan : CASPrimitiveExtIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator
                                   withCASIntBinaryOperator:(id<CASIntBinaryOperator>)accumulator;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntScan)

FOUNDATION_EXPORT void CASIntScan_initWithCASPrimitiveIterator_OfInt_withCASIntBinaryOperator_(CASIntScan *self, CASPrimitiveIterator_OfInt *iterator, id<CASIntBinaryOperator> accumulator);

FOUNDATION_EXPORT CASIntScan *new_CASIntScan_initWithCASPrimitiveIterator_OfInt_withCASIntBinaryOperator_(CASPrimitiveIterator_OfInt *iterator, id<CASIntBinaryOperator> accumulator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntScan *create_CASIntScan_initWithCASPrimitiveIterator_OfInt_withCASIntBinaryOperator_(CASPrimitiveIterator_OfInt *iterator, id<CASIntBinaryOperator> accumulator);

J2OBJC_TYPE_LITERAL_HEADER(CASIntScan)

@compatibility_alias ComAnnimonStreamOperatorIntScan CASIntScan;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntScan")
