//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntSorted.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntSorted")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntSorted
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntSorted 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntSorted 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntSorted

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntSorted_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntSorted || defined(INCLUDE_CASIntSorted))
#define CASIntSorted_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@class CASPrimitiveIterator_OfInt;

@interface CASIntSorted : CASPrimitiveExtIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntSorted)

FOUNDATION_EXPORT void CASIntSorted_initWithCASPrimitiveIterator_OfInt_(CASIntSorted *self, CASPrimitiveIterator_OfInt *iterator);

FOUNDATION_EXPORT CASIntSorted *new_CASIntSorted_initWithCASPrimitiveIterator_OfInt_(CASPrimitiveIterator_OfInt *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntSorted *create_CASIntSorted_initWithCASPrimitiveIterator_OfInt_(CASPrimitiveIterator_OfInt *iterator);

J2OBJC_TYPE_LITERAL_HEADER(CASIntSorted)

@compatibility_alias ComAnnimonStreamOperatorIntSorted CASIntSorted;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntSorted")
