//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongTakeWhile.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongTakeWhile")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongTakeWhile
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongTakeWhile 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongTakeWhile 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongTakeWhile

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongTakeWhile_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongTakeWhile || defined(INCLUDE_CASLongTakeWhile))
#define CASLongTakeWhile_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@class CASPrimitiveIterator_OfLong;
@protocol CASLongPredicate;

@interface CASLongTakeWhile : CASPrimitiveExtIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator
                                        withCASLongPredicate:(id<CASLongPredicate>)predicate;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongTakeWhile)

FOUNDATION_EXPORT void CASLongTakeWhile_initWithCASPrimitiveIterator_OfLong_withCASLongPredicate_(CASLongTakeWhile *self, CASPrimitiveIterator_OfLong *iterator, id<CASLongPredicate> predicate);

FOUNDATION_EXPORT CASLongTakeWhile *new_CASLongTakeWhile_initWithCASPrimitiveIterator_OfLong_withCASLongPredicate_(CASPrimitiveIterator_OfLong *iterator, id<CASLongPredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongTakeWhile *create_CASLongTakeWhile_initWithCASPrimitiveIterator_OfLong_withCASLongPredicate_(CASPrimitiveIterator_OfLong *iterator, id<CASLongPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASLongTakeWhile)

@compatibility_alias ComAnnimonStreamOperatorLongTakeWhile CASLongTakeWhile;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongTakeWhile")
