//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongLimit.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongLimit")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongLimit
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongLimit 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongLimit 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongLimit

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongLimit_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongLimit || defined(INCLUDE_CASLongLimit))
#define CASLongLimit_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;

@interface CASLongLimit : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator
                                                    withLong:(int64_t)maxSize;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongLimit)

FOUNDATION_EXPORT void CASLongLimit_initWithCASPrimitiveIterator_OfLong_withLong_(CASLongLimit *self, CASPrimitiveIterator_OfLong *iterator, int64_t maxSize);

FOUNDATION_EXPORT CASLongLimit *new_CASLongLimit_initWithCASPrimitiveIterator_OfLong_withLong_(CASPrimitiveIterator_OfLong *iterator, int64_t maxSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongLimit *create_CASLongLimit_initWithCASPrimitiveIterator_OfLong_withLong_(CASPrimitiveIterator_OfLong *iterator, int64_t maxSize);

J2OBJC_TYPE_LITERAL_HEADER(CASLongLimit)

@compatibility_alias ComAnnimonStreamOperatorLongLimit CASLongLimit;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongLimit")
