//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongGenerate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongGenerate")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongGenerate
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongGenerate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongGenerate 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongGenerate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongGenerate_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongGenerate || defined(INCLUDE_CASLongGenerate))
#define CASLongGenerate_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;
@protocol CASLongSupplier;

@interface CASLongGenerate : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASLongSupplier:(id<CASLongSupplier>)supplier;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongGenerate)

FOUNDATION_EXPORT void CASLongGenerate_initWithCASLongSupplier_(CASLongGenerate *self, id<CASLongSupplier> supplier);

FOUNDATION_EXPORT CASLongGenerate *new_CASLongGenerate_initWithCASLongSupplier_(id<CASLongSupplier> supplier) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongGenerate *create_CASLongGenerate_initWithCASLongSupplier_(id<CASLongSupplier> supplier);

J2OBJC_TYPE_LITERAL_HEADER(CASLongGenerate)

@compatibility_alias ComAnnimonStreamOperatorLongGenerate CASLongGenerate;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongGenerate")
