//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongArray.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongArray")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongArray
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongArray 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongArray 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongArray

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongArray_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongArray || defined(INCLUDE_CASLongArray))
#define CASLongArray_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class IOSLongArray;
@class JavaLangBoolean;
@class JavaLangLong;

@interface CASLongArray : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithLongArray:(IOSLongArray *)values;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongArray)

FOUNDATION_EXPORT void CASLongArray_initWithLongArray_(CASLongArray *self, IOSLongArray *values);

FOUNDATION_EXPORT CASLongArray *new_CASLongArray_initWithLongArray_(IOSLongArray *values) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongArray *create_CASLongArray_initWithLongArray_(IOSLongArray *values);

J2OBJC_TYPE_LITERAL_HEADER(CASLongArray)

@compatibility_alias ComAnnimonStreamOperatorLongArray CASLongArray;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongArray")
