//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongMap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongMap")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongMap
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongMap 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongMap 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongMap

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongMap_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongMap || defined(INCLUDE_CASLongMap))
#define CASLongMap_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;
@protocol CASLongUnaryOperator;

@interface CASLongMap : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator
                                    withCASLongUnaryOperator:(id<CASLongUnaryOperator>)mapper;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongMap)

FOUNDATION_EXPORT void CASLongMap_initWithCASPrimitiveIterator_OfLong_withCASLongUnaryOperator_(CASLongMap *self, CASPrimitiveIterator_OfLong *iterator, id<CASLongUnaryOperator> mapper);

FOUNDATION_EXPORT CASLongMap *new_CASLongMap_initWithCASPrimitiveIterator_OfLong_withCASLongUnaryOperator_(CASPrimitiveIterator_OfLong *iterator, id<CASLongUnaryOperator> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongMap *create_CASLongMap_initWithCASPrimitiveIterator_OfLong_withCASLongUnaryOperator_(CASPrimitiveIterator_OfLong *iterator, id<CASLongUnaryOperator> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASLongMap)

@compatibility_alias ComAnnimonStreamOperatorLongMap CASLongMap;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongMap")
