//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongMapToInt.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongMapToInt")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongMapToInt
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongMapToInt 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongMapToInt 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongMapToInt

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongMapToInt_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongMapToInt || defined(INCLUDE_CASLongMapToInt))
#define CASLongMapToInt_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class CASPrimitiveIterator_OfLong;
@class JavaLangBoolean;
@class JavaLangInteger;
@protocol CASLongToIntFunction;

@interface CASLongMapToInt : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator
                                    withCASLongToIntFunction:(id<CASLongToIntFunction>)mapper;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongMapToInt)

FOUNDATION_EXPORT void CASLongMapToInt_initWithCASPrimitiveIterator_OfLong_withCASLongToIntFunction_(CASLongMapToInt *self, CASPrimitiveIterator_OfLong *iterator, id<CASLongToIntFunction> mapper);

FOUNDATION_EXPORT CASLongMapToInt *new_CASLongMapToInt_initWithCASPrimitiveIterator_OfLong_withCASLongToIntFunction_(CASPrimitiveIterator_OfLong *iterator, id<CASLongToIntFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongMapToInt *create_CASLongMapToInt_initWithCASPrimitiveIterator_OfLong_withCASLongToIntFunction_(CASPrimitiveIterator_OfLong *iterator, id<CASLongToIntFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASLongMapToInt)

@compatibility_alias ComAnnimonStreamOperatorLongMapToInt CASLongMapToInt;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongMapToInt")
