//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongIterate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongIterate")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongIterate
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongIterate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongIterate 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongIterate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongIterate_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongIterate || defined(INCLUDE_CASLongIterate))
#define CASLongIterate_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;
@protocol CASLongUnaryOperator;

@interface CASLongIterate : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithLong:(int64_t)seed
             withCASLongUnaryOperator:(id<CASLongUnaryOperator>)f;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongIterate)

FOUNDATION_EXPORT void CASLongIterate_initWithLong_withCASLongUnaryOperator_(CASLongIterate *self, int64_t seed, id<CASLongUnaryOperator> f);

FOUNDATION_EXPORT CASLongIterate *new_CASLongIterate_initWithLong_withCASLongUnaryOperator_(int64_t seed, id<CASLongUnaryOperator> f) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongIterate *create_CASLongIterate_initWithLong_withCASLongUnaryOperator_(int64_t seed, id<CASLongUnaryOperator> f);

J2OBJC_TYPE_LITERAL_HEADER(CASLongIterate)

@compatibility_alias ComAnnimonStreamOperatorLongIterate CASLongIterate;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongIterate")
