//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjArray.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjArray")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjArray
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjArray 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjArray 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjArray

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjArray_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjArray || defined(INCLUDE_CASObjArray))
#define CASObjArray_

#define RESTRICT_ComAnnimonStreamIteratorLsaIterator 1
#define INCLUDE_CASLsaIterator 1
#include "com/annimon/stream/iterator/LsaIterator.h"

@class IOSObjectArray;
@class JavaLangBoolean;

@interface CASObjArray : CASLsaIterator

#pragma mark Public

- (instancetype _Nonnull)initWithNSObjectArray:(IOSObjectArray *)elements;

- (bool)hasNext;

- (id)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjArray)

FOUNDATION_EXPORT void CASObjArray_initWithNSObjectArray_(CASObjArray *self, IOSObjectArray *elements);

FOUNDATION_EXPORT CASObjArray *new_CASObjArray_initWithNSObjectArray_(IOSObjectArray *elements) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjArray *create_CASObjArray_initWithNSObjectArray_(IOSObjectArray *elements);

J2OBJC_TYPE_LITERAL_HEADER(CASObjArray)

@compatibility_alias ComAnnimonStreamOperatorObjArray CASObjArray;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjArray")
