//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjDistinct.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjDistinct")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjDistinct
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjDistinct 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjDistinct 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjDistinct

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjDistinct_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjDistinct || defined(INCLUDE_CASObjDistinct))
#define CASObjDistinct_

#define RESTRICT_ComAnnimonStreamIteratorLsaExtIterator 1
#define INCLUDE_CASLsaExtIterator 1
#include "com/annimon/stream/iterator/LsaExtIterator.h"

@protocol JavaUtilIterator;

@interface CASObjDistinct : CASLsaExtIterator

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjDistinct)

FOUNDATION_EXPORT void CASObjDistinct_initWithJavaUtilIterator_(CASObjDistinct *self, id<JavaUtilIterator> iterator);

FOUNDATION_EXPORT CASObjDistinct *new_CASObjDistinct_initWithJavaUtilIterator_(id<JavaUtilIterator> iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjDistinct *create_CASObjDistinct_initWithJavaUtilIterator_(id<JavaUtilIterator> iterator);

J2OBJC_TYPE_LITERAL_HEADER(CASObjDistinct)

@compatibility_alias ComAnnimonStreamOperatorObjDistinct CASObjDistinct;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjDistinct")
