//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjFlatMapToDouble.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToDouble")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjFlatMapToDouble
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToDouble 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToDouble 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjFlatMapToDouble

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjFlatMapToDouble_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToDouble || defined(INCLUDE_CASObjFlatMapToDouble))
#define CASObjFlatMapToDouble_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@protocol CASFunction;
@protocol JavaUtilIterator;

@interface CASObjFlatMapToDouble : CASPrimitiveExtIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                  withCASFunction:(id<CASFunction>)mapper;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjFlatMapToDouble)

FOUNDATION_EXPORT void CASObjFlatMapToDouble_initWithJavaUtilIterator_withCASFunction_(CASObjFlatMapToDouble *self, id<JavaUtilIterator> iterator, id<CASFunction> mapper);

FOUNDATION_EXPORT CASObjFlatMapToDouble *new_CASObjFlatMapToDouble_initWithJavaUtilIterator_withCASFunction_(id<JavaUtilIterator> iterator, id<CASFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjFlatMapToDouble *create_CASObjFlatMapToDouble_initWithJavaUtilIterator_withCASFunction_(id<JavaUtilIterator> iterator, id<CASFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASObjFlatMapToDouble)

@compatibility_alias ComAnnimonStreamOperatorObjFlatMapToDouble CASObjFlatMapToDouble;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToDouble")
