//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjFlatMapToLong.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToLong")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjFlatMapToLong
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToLong 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToLong 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjFlatMapToLong

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjFlatMapToLong_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToLong || defined(INCLUDE_CASObjFlatMapToLong))
#define CASObjFlatMapToLong_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@protocol CASFunction;
@protocol JavaUtilIterator;

@interface CASObjFlatMapToLong : CASPrimitiveExtIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                  withCASFunction:(id<CASFunction>)mapper;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjFlatMapToLong)

FOUNDATION_EXPORT void CASObjFlatMapToLong_initWithJavaUtilIterator_withCASFunction_(CASObjFlatMapToLong *self, id<JavaUtilIterator> iterator, id<CASFunction> mapper);

FOUNDATION_EXPORT CASObjFlatMapToLong *new_CASObjFlatMapToLong_initWithJavaUtilIterator_withCASFunction_(id<JavaUtilIterator> iterator, id<CASFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjFlatMapToLong *create_CASObjFlatMapToLong_initWithJavaUtilIterator_withCASFunction_(id<JavaUtilIterator> iterator, id<CASFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASObjFlatMapToLong)

@compatibility_alias ComAnnimonStreamOperatorObjFlatMapToLong CASObjFlatMapToLong;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMapToLong")
