//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjIterate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjIterate")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjIterate
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjIterate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjIterate 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjIterate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjIterate_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjIterate || defined(INCLUDE_CASObjIterate))
#define CASObjIterate_

#define RESTRICT_ComAnnimonStreamIteratorLsaIterator 1
#define INCLUDE_CASLsaIterator 1
#include "com/annimon/stream/iterator/LsaIterator.h"

@class JavaLangBoolean;
@protocol CASUnaryOperator;

@interface CASObjIterate : CASLsaIterator

#pragma mark Public

- (instancetype _Nonnull)initWithId:(id)seed
               withCASUnaryOperator:(id<CASUnaryOperator>)op;

- (bool)hasNext;

- (id)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjIterate)

FOUNDATION_EXPORT void CASObjIterate_initWithId_withCASUnaryOperator_(CASObjIterate *self, id seed, id<CASUnaryOperator> op);

FOUNDATION_EXPORT CASObjIterate *new_CASObjIterate_initWithId_withCASUnaryOperator_(id seed, id<CASUnaryOperator> op) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjIterate *create_CASObjIterate_initWithId_withCASUnaryOperator_(id seed, id<CASUnaryOperator> op);

J2OBJC_TYPE_LITERAL_HEADER(CASObjIterate)

@compatibility_alias ComAnnimonStreamOperatorObjIterate CASObjIterate;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjIterate")
