//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjMapToInt.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToInt")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjMapToInt
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToInt 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToInt 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjMapToInt

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjMapToInt_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToInt || defined(INCLUDE_CASObjMapToInt))
#define CASObjMapToInt_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@protocol CASToIntFunction;
@protocol JavaUtilIterator;

@interface CASObjMapToInt : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                             withCASToIntFunction:(id<CASToIntFunction>)mapper;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjMapToInt)

FOUNDATION_EXPORT void CASObjMapToInt_initWithJavaUtilIterator_withCASToIntFunction_(CASObjMapToInt *self, id<JavaUtilIterator> iterator, id<CASToIntFunction> mapper);

FOUNDATION_EXPORT CASObjMapToInt *new_CASObjMapToInt_initWithJavaUtilIterator_withCASToIntFunction_(id<JavaUtilIterator> iterator, id<CASToIntFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjMapToInt *create_CASObjMapToInt_initWithJavaUtilIterator_withCASToIntFunction_(id<JavaUtilIterator> iterator, id<CASToIntFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASObjMapToInt)

@compatibility_alias ComAnnimonStreamOperatorObjMapToInt CASObjMapToInt;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToInt")
