//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjMapToLong.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToLong")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjMapToLong
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToLong 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToLong 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjMapToLong

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjMapToLong_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToLong || defined(INCLUDE_CASObjMapToLong))
#define CASObjMapToLong_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;
@protocol CASToLongFunction;
@protocol JavaUtilIterator;

@interface CASObjMapToLong : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                            withCASToLongFunction:(id<CASToLongFunction>)mapper;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjMapToLong)

FOUNDATION_EXPORT void CASObjMapToLong_initWithJavaUtilIterator_withCASToLongFunction_(CASObjMapToLong *self, id<JavaUtilIterator> iterator, id<CASToLongFunction> mapper);

FOUNDATION_EXPORT CASObjMapToLong *new_CASObjMapToLong_initWithJavaUtilIterator_withCASToLongFunction_(id<JavaUtilIterator> iterator, id<CASToLongFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjMapToLong *create_CASObjMapToLong_initWithJavaUtilIterator_withCASToLongFunction_(id<JavaUtilIterator> iterator, id<CASToLongFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASObjMapToLong)

@compatibility_alias ComAnnimonStreamOperatorObjMapToLong CASObjMapToLong;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjMapToLong")
