//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjMap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjMap")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjMap
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjMap 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjMap 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjMap

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjMap_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjMap || defined(INCLUDE_CASObjMap))
#define CASObjMap_

#define RESTRICT_ComAnnimonStreamIteratorLsaIterator 1
#define INCLUDE_CASLsaIterator 1
#include "com/annimon/stream/iterator/LsaIterator.h"

@class JavaLangBoolean;
@protocol CASFunction;
@protocol JavaUtilIterator;

@interface CASObjMap : CASLsaIterator

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                  withCASFunction:(id<CASFunction>)mapper;

- (bool)hasNext;

- (id)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjMap)

FOUNDATION_EXPORT void CASObjMap_initWithJavaUtilIterator_withCASFunction_(CASObjMap *self, id<JavaUtilIterator> iterator, id<CASFunction> mapper);

FOUNDATION_EXPORT CASObjMap *new_CASObjMap_initWithJavaUtilIterator_withCASFunction_(id<JavaUtilIterator> iterator, id<CASFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjMap *create_CASObjMap_initWithJavaUtilIterator_withCASFunction_(id<JavaUtilIterator> iterator, id<CASFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASObjMap)

@compatibility_alias ComAnnimonStreamOperatorObjMap CASObjMap;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjMap")
