//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjSlidingWindow.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjSlidingWindow")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjSlidingWindow
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjSlidingWindow 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjSlidingWindow 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjSlidingWindow

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjSlidingWindow_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjSlidingWindow || defined(INCLUDE_CASObjSlidingWindow))
#define CASObjSlidingWindow_

#define RESTRICT_ComAnnimonStreamIteratorLsaIterator 1
#define INCLUDE_CASLsaIterator 1
#include "com/annimon/stream/iterator/LsaIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@protocol JavaUtilIterator;
@protocol JavaUtilList;

@interface CASObjSlidingWindow : CASLsaIterator

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                          withInt:(int32_t)windowSize
                                          withInt:(int32_t)stepWidth;

- (bool)hasNext;

- (id<JavaUtilList>)next;

- (id<JavaUtilList>)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjSlidingWindow)

FOUNDATION_EXPORT void CASObjSlidingWindow_initWithJavaUtilIterator_withInt_withInt_(CASObjSlidingWindow *self, id<JavaUtilIterator> iterator, int32_t windowSize, int32_t stepWidth);

FOUNDATION_EXPORT CASObjSlidingWindow *new_CASObjSlidingWindow_initWithJavaUtilIterator_withInt_withInt_(id<JavaUtilIterator> iterator, int32_t windowSize, int32_t stepWidth) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjSlidingWindow *create_CASObjSlidingWindow_initWithJavaUtilIterator_withInt_withInt_(id<JavaUtilIterator> iterator, int32_t windowSize, int32_t stepWidth);

J2OBJC_TYPE_LITERAL_HEADER(CASObjSlidingWindow)

@compatibility_alias ComAnnimonStreamOperatorObjSlidingWindow CASObjSlidingWindow;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjSlidingWindow")
