//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjTakeUntil.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeUntil")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjTakeUntil
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeUntil 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeUntil 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjTakeUntil

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjTakeUntil_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeUntil || defined(INCLUDE_CASObjTakeUntil))
#define CASObjTakeUntil_

#define RESTRICT_ComAnnimonStreamIteratorLsaExtIterator 1
#define INCLUDE_CASLsaExtIterator 1
#include "com/annimon/stream/iterator/LsaExtIterator.h"

@protocol CASPredicate;
@protocol JavaUtilIterator;

@interface CASObjTakeUntil : CASLsaExtIterator

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                 withCASPredicate:(id<CASPredicate>)predicate;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjTakeUntil)

FOUNDATION_EXPORT void CASObjTakeUntil_initWithJavaUtilIterator_withCASPredicate_(CASObjTakeUntil *self, id<JavaUtilIterator> iterator, id<CASPredicate> predicate);

FOUNDATION_EXPORT CASObjTakeUntil *new_CASObjTakeUntil_initWithJavaUtilIterator_withCASPredicate_(id<JavaUtilIterator> iterator, id<CASPredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjTakeUntil *create_CASObjTakeUntil_initWithJavaUtilIterator_withCASPredicate_(id<JavaUtilIterator> iterator, id<CASPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASObjTakeUntil)

@compatibility_alias ComAnnimonStreamOperatorObjTakeUntil CASObjTakeUntil;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeUntil")
