//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjTakeWhile.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhile")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjTakeWhile
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhile 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhile 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjTakeWhile

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjTakeWhile_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhile || defined(INCLUDE_CASObjTakeWhile))
#define CASObjTakeWhile_

#define RESTRICT_ComAnnimonStreamIteratorLsaExtIterator 1
#define INCLUDE_CASLsaExtIterator 1
#include "com/annimon/stream/iterator/LsaExtIterator.h"

@protocol CASPredicate;
@protocol JavaUtilIterator;

@interface CASObjTakeWhile : CASLsaExtIterator

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                 withCASPredicate:(id<CASPredicate>)predicate;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjTakeWhile)

FOUNDATION_EXPORT void CASObjTakeWhile_initWithJavaUtilIterator_withCASPredicate_(CASObjTakeWhile *self, id<JavaUtilIterator> iterator, id<CASPredicate> predicate);

FOUNDATION_EXPORT CASObjTakeWhile *new_CASObjTakeWhile_initWithJavaUtilIterator_withCASPredicate_(id<JavaUtilIterator> iterator, id<CASPredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjTakeWhile *create_CASObjTakeWhile_initWithJavaUtilIterator_withCASPredicate_(id<JavaUtilIterator> iterator, id<CASPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASObjTakeWhile)

@compatibility_alias ComAnnimonStreamOperatorObjTakeWhile CASObjTakeWhile;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhile")
