//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjTakeWhileIndexed.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhileIndexed")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjTakeWhileIndexed
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhileIndexed 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhileIndexed 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjTakeWhileIndexed

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjTakeWhileIndexed_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhileIndexed || defined(INCLUDE_CASObjTakeWhileIndexed))
#define CASObjTakeWhileIndexed_

#define RESTRICT_ComAnnimonStreamIteratorLsaExtIterator 1
#define INCLUDE_CASLsaExtIterator 1
#include "com/annimon/stream/iterator/LsaExtIterator.h"

@class CASIndexedIterator;
@protocol CASIndexedPredicate;

@interface CASObjTakeWhileIndexed : CASLsaExtIterator

#pragma mark Public

- (instancetype _Nonnull)initWithCASIndexedIterator:(CASIndexedIterator *)iterator
                            withCASIndexedPredicate:(id<CASIndexedPredicate>)predicate;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjTakeWhileIndexed)

FOUNDATION_EXPORT void CASObjTakeWhileIndexed_initWithCASIndexedIterator_withCASIndexedPredicate_(CASObjTakeWhileIndexed *self, CASIndexedIterator *iterator, id<CASIndexedPredicate> predicate);

FOUNDATION_EXPORT CASObjTakeWhileIndexed *new_CASObjTakeWhileIndexed_initWithCASIndexedIterator_withCASIndexedPredicate_(CASIndexedIterator *iterator, id<CASIndexedPredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjTakeWhileIndexed *create_CASObjTakeWhileIndexed_initWithCASIndexedIterator_withCASIndexedPredicate_(CASIndexedIterator *iterator, id<CASIndexedPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASObjTakeWhileIndexed)

@compatibility_alias ComAnnimonStreamOperatorObjTakeWhileIndexed CASObjTakeWhileIndexed;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjTakeWhileIndexed")
