//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleTakeUntil.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleTakeUntil")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleTakeUntil
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleTakeUntil 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleTakeUntil 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleTakeUntil

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleTakeUntil_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleTakeUntil || defined(INCLUDE_CASDoubleTakeUntil))
#define CASDoubleTakeUntil_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@class CASPrimitiveIterator_OfDouble;
@protocol CASDoublePredicate;

@interface CASDoubleTakeUntil : CASPrimitiveExtIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                        withCASDoublePredicate:(id<CASDoublePredicate>)stopPredicate;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleTakeUntil)

FOUNDATION_EXPORT void CASDoubleTakeUntil_initWithCASPrimitiveIterator_OfDouble_withCASDoublePredicate_(CASDoubleTakeUntil *self, CASPrimitiveIterator_OfDouble *iterator, id<CASDoublePredicate> stopPredicate);

FOUNDATION_EXPORT CASDoubleTakeUntil *new_CASDoubleTakeUntil_initWithCASPrimitiveIterator_OfDouble_withCASDoublePredicate_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoublePredicate> stopPredicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleTakeUntil *create_CASDoubleTakeUntil_initWithCASPrimitiveIterator_OfDouble_withCASDoublePredicate_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoublePredicate> stopPredicate);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleTakeUntil)

@compatibility_alias ComAnnimonStreamOperatorDoubleTakeUntil CASDoubleTakeUntil;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleTakeUntil")
