//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleMap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMap")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleMap
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMap 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMap 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleMap

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleMap_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMap || defined(INCLUDE_CASDoubleMap))
#define CASDoubleMap_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@protocol CASDoubleUnaryOperator;

@interface CASDoubleMap : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                    withCASDoubleUnaryOperator:(id<CASDoubleUnaryOperator>)mapper;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleMap)

FOUNDATION_EXPORT void CASDoubleMap_initWithCASPrimitiveIterator_OfDouble_withCASDoubleUnaryOperator_(CASDoubleMap *self, CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleUnaryOperator> mapper);

FOUNDATION_EXPORT CASDoubleMap *new_CASDoubleMap_initWithCASPrimitiveIterator_OfDouble_withCASDoubleUnaryOperator_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleUnaryOperator> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleMap *create_CASDoubleMap_initWithCASPrimitiveIterator_OfDouble_withCASDoubleUnaryOperator_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleUnaryOperator> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleMap)

@compatibility_alias ComAnnimonStreamOperatorDoubleMap CASDoubleMap;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMap")
