//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleGenerate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleGenerate")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleGenerate
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleGenerate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleGenerate 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleGenerate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleGenerate_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleGenerate || defined(INCLUDE_CASDoubleGenerate))
#define CASDoubleGenerate_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@protocol CASDoubleSupplier;

@interface CASDoubleGenerate : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASDoubleSupplier:(id<CASDoubleSupplier>)supplier;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleGenerate)

FOUNDATION_EXPORT void CASDoubleGenerate_initWithCASDoubleSupplier_(CASDoubleGenerate *self, id<CASDoubleSupplier> supplier);

FOUNDATION_EXPORT CASDoubleGenerate *new_CASDoubleGenerate_initWithCASDoubleSupplier_(id<CASDoubleSupplier> supplier) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleGenerate *create_CASDoubleGenerate_initWithCASDoubleSupplier_(id<CASDoubleSupplier> supplier);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleGenerate)

@compatibility_alias ComAnnimonStreamOperatorDoubleGenerate CASDoubleGenerate;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleGenerate")
