//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleIterate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleIterate")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleIterate
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleIterate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleIterate 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleIterate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleIterate_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleIterate || defined(INCLUDE_CASDoubleIterate))
#define CASDoubleIterate_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@protocol CASDoubleUnaryOperator;

@interface CASDoubleIterate : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithDouble:(double)seed
             withCASDoubleUnaryOperator:(id<CASDoubleUnaryOperator>)f;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleIterate)

FOUNDATION_EXPORT void CASDoubleIterate_initWithDouble_withCASDoubleUnaryOperator_(CASDoubleIterate *self, double seed, id<CASDoubleUnaryOperator> f);

FOUNDATION_EXPORT CASDoubleIterate *new_CASDoubleIterate_initWithDouble_withCASDoubleUnaryOperator_(double seed, id<CASDoubleUnaryOperator> f) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleIterate *create_CASDoubleIterate_initWithDouble_withCASDoubleUnaryOperator_(double seed, id<CASDoubleUnaryOperator> f);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleIterate)

@compatibility_alias ComAnnimonStreamOperatorDoubleIterate CASDoubleIterate;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleIterate")
