//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleLimit.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleLimit")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleLimit
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleLimit 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleLimit 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleLimit

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleLimit_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleLimit || defined(INCLUDE_CASDoubleLimit))
#define CASDoubleLimit_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangLong;

@interface CASDoubleLimit : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                                      withLong:(int64_t)maxSize;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleLimit)

FOUNDATION_EXPORT void CASDoubleLimit_initWithCASPrimitiveIterator_OfDouble_withLong_(CASDoubleLimit *self, CASPrimitiveIterator_OfDouble *iterator, int64_t maxSize);

FOUNDATION_EXPORT CASDoubleLimit *new_CASDoubleLimit_initWithCASPrimitiveIterator_OfDouble_withLong_(CASPrimitiveIterator_OfDouble *iterator, int64_t maxSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleLimit *create_CASDoubleLimit_initWithCASPrimitiveIterator_OfDouble_withLong_(CASPrimitiveIterator_OfDouble *iterator, int64_t maxSize);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleLimit)

@compatibility_alias ComAnnimonStreamOperatorDoubleLimit CASDoubleLimit;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleLimit")
