//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleMapToLong.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToLong")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleMapToLong
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToLong 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToLong 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleMapToLong

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleMapToLong_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToLong || defined(INCLUDE_CASDoubleMapToLong))
#define CASDoubleMapToLong_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class CASPrimitiveIterator_OfDouble;
@class JavaLangBoolean;
@class JavaLangLong;
@protocol CASDoubleToLongFunction;

@interface CASDoubleMapToLong : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                   withCASDoubleToLongFunction:(id<CASDoubleToLongFunction>)mapper;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleMapToLong)

FOUNDATION_EXPORT void CASDoubleMapToLong_initWithCASPrimitiveIterator_OfDouble_withCASDoubleToLongFunction_(CASDoubleMapToLong *self, CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleToLongFunction> mapper);

FOUNDATION_EXPORT CASDoubleMapToLong *new_CASDoubleMapToLong_initWithCASPrimitiveIterator_OfDouble_withCASDoubleToLongFunction_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleToLongFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleMapToLong *create_CASDoubleMapToLong_initWithCASPrimitiveIterator_OfDouble_withCASDoubleToLongFunction_(CASPrimitiveIterator_OfDouble *iterator, id<CASDoubleToLongFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleMapToLong)

@compatibility_alias ComAnnimonStreamOperatorDoubleMapToLong CASDoubleMapToLong;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapToLong")
