//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleSample.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSample")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleSample
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSample 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSample 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleSample

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleSample_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSample || defined(INCLUDE_CASDoubleSample))
#define CASDoubleSample_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangInteger;

@interface CASDoubleSample : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator
                                                       withInt:(int32_t)stepWidth;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleSample)

FOUNDATION_EXPORT void CASDoubleSample_initWithCASPrimitiveIterator_OfDouble_withInt_(CASDoubleSample *self, CASPrimitiveIterator_OfDouble *iterator, int32_t stepWidth);

FOUNDATION_EXPORT CASDoubleSample *new_CASDoubleSample_initWithCASPrimitiveIterator_OfDouble_withInt_(CASPrimitiveIterator_OfDouble *iterator, int32_t stepWidth) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleSample *create_CASDoubleSample_initWithCASPrimitiveIterator_OfDouble_withInt_(CASPrimitiveIterator_OfDouble *iterator, int32_t stepWidth);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleSample)

@compatibility_alias ComAnnimonStreamOperatorDoubleSample CASDoubleSample;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleSample")
