//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/DoubleMapIndexed.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapIndexed")
#ifdef RESTRICT_ComAnnimonStreamOperatorDoubleMapIndexed
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapIndexed 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapIndexed 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorDoubleMapIndexed

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleMapIndexed_) && (INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapIndexed || defined(INCLUDE_CASDoubleMapIndexed))
#define CASDoubleMapIndexed_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class CASPrimitiveIndexedIterator_OfDouble;
@class JavaLangBoolean;
@class JavaLangDouble;
@protocol CASIndexedDoubleUnaryOperator;

@interface CASDoubleMapIndexed : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIndexedIterator_OfDouble:(CASPrimitiveIndexedIterator_OfDouble *)iterator
                                    withCASIndexedDoubleUnaryOperator:(id<CASIndexedDoubleUnaryOperator>)mapper;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleMapIndexed)

FOUNDATION_EXPORT void CASDoubleMapIndexed_initWithCASPrimitiveIndexedIterator_OfDouble_withCASIndexedDoubleUnaryOperator_(CASDoubleMapIndexed *self, CASPrimitiveIndexedIterator_OfDouble *iterator, id<CASIndexedDoubleUnaryOperator> mapper);

FOUNDATION_EXPORT CASDoubleMapIndexed *new_CASDoubleMapIndexed_initWithCASPrimitiveIndexedIterator_OfDouble_withCASIndexedDoubleUnaryOperator_(CASPrimitiveIndexedIterator_OfDouble *iterator, id<CASIndexedDoubleUnaryOperator> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASDoubleMapIndexed *create_CASDoubleMapIndexed_initWithCASPrimitiveIndexedIterator_OfDouble_withCASIndexedDoubleUnaryOperator_(CASPrimitiveIndexedIterator_OfDouble *iterator, id<CASIndexedDoubleUnaryOperator> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleMapIndexed)

@compatibility_alias ComAnnimonStreamOperatorDoubleMapIndexed CASDoubleMapIndexed;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorDoubleMapIndexed")
