//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntArray.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntArray")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntArray
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntArray 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntArray 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntArray

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntArray_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntArray || defined(INCLUDE_CASIntArray))
#define CASIntArray_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class IOSIntArray;
@class JavaLangBoolean;
@class JavaLangInteger;

@interface CASIntArray : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithIntArray:(IOSIntArray *)values;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntArray)

FOUNDATION_EXPORT void CASIntArray_initWithIntArray_(CASIntArray *self, IOSIntArray *values);

FOUNDATION_EXPORT CASIntArray *new_CASIntArray_initWithIntArray_(IOSIntArray *values) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntArray *create_CASIntArray_initWithIntArray_(IOSIntArray *values);

J2OBJC_TYPE_LITERAL_HEADER(CASIntArray)

@compatibility_alias ComAnnimonStreamOperatorIntArray CASIntArray;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntArray")
