//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntCodePoints.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntCodePoints")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntCodePoints
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntCodePoints 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntCodePoints 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntCodePoints

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntCodePoints_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntCodePoints || defined(INCLUDE_CASIntCodePoints))
#define CASIntCodePoints_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@protocol JavaLangCharSequence;

@interface CASIntCodePoints : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithJavaLangCharSequence:(id<JavaLangCharSequence>)charSequence;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntCodePoints)

FOUNDATION_EXPORT void CASIntCodePoints_initWithJavaLangCharSequence_(CASIntCodePoints *self, id<JavaLangCharSequence> charSequence);

FOUNDATION_EXPORT CASIntCodePoints *new_CASIntCodePoints_initWithJavaLangCharSequence_(id<JavaLangCharSequence> charSequence) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntCodePoints *create_CASIntCodePoints_initWithJavaLangCharSequence_(id<JavaLangCharSequence> charSequence);

J2OBJC_TYPE_LITERAL_HEADER(CASIntCodePoints)

@compatibility_alias ComAnnimonStreamOperatorIntCodePoints CASIntCodePoints;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntCodePoints")
