//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntFilter.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntFilter")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntFilter
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntFilter 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntFilter 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntFilter

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntFilter_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntFilter || defined(INCLUDE_CASIntFilter))
#define CASIntFilter_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@protocol CASIntPredicate;

@interface CASIntFilter : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator
                                        withCASIntPredicate:(id<CASIntPredicate>)predicate;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntFilter)

FOUNDATION_EXPORT void CASIntFilter_initWithCASPrimitiveIterator_OfInt_withCASIntPredicate_(CASIntFilter *self, CASPrimitiveIterator_OfInt *iterator, id<CASIntPredicate> predicate);

FOUNDATION_EXPORT CASIntFilter *new_CASIntFilter_initWithCASPrimitiveIterator_OfInt_withCASIntPredicate_(CASPrimitiveIterator_OfInt *iterator, id<CASIntPredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntFilter *create_CASIntFilter_initWithCASPrimitiveIterator_OfInt_withCASIntPredicate_(CASPrimitiveIterator_OfInt *iterator, id<CASIntPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASIntFilter)

@compatibility_alias ComAnnimonStreamOperatorIntFilter CASIntFilter;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntFilter")
