//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntFilterIndexed.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntFilterIndexed")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntFilterIndexed
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntFilterIndexed 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntFilterIndexed 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntFilterIndexed

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntFilterIndexed_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntFilterIndexed || defined(INCLUDE_CASIntFilterIndexed))
#define CASIntFilterIndexed_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class CASPrimitiveIndexedIterator_OfInt;
@class JavaLangBoolean;
@class JavaLangInteger;
@protocol CASIndexedIntPredicate;

@interface CASIntFilterIndexed : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIndexedIterator_OfInt:(CASPrimitiveIndexedIterator_OfInt *)iterator
                                        withCASIndexedIntPredicate:(id<CASIndexedIntPredicate>)predicate;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntFilterIndexed)

FOUNDATION_EXPORT void CASIntFilterIndexed_initWithCASPrimitiveIndexedIterator_OfInt_withCASIndexedIntPredicate_(CASIntFilterIndexed *self, CASPrimitiveIndexedIterator_OfInt *iterator, id<CASIndexedIntPredicate> predicate);

FOUNDATION_EXPORT CASIntFilterIndexed *new_CASIntFilterIndexed_initWithCASPrimitiveIndexedIterator_OfInt_withCASIndexedIntPredicate_(CASPrimitiveIndexedIterator_OfInt *iterator, id<CASIndexedIntPredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntFilterIndexed *create_CASIntFilterIndexed_initWithCASPrimitiveIndexedIterator_OfInt_withCASIndexedIntPredicate_(CASPrimitiveIndexedIterator_OfInt *iterator, id<CASIndexedIntPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASIntFilterIndexed)

@compatibility_alias ComAnnimonStreamOperatorIntFilterIndexed CASIntFilterIndexed;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntFilterIndexed")
