//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntLimit.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntLimit")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntLimit
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntLimit 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntLimit 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntLimit

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntLimit_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntLimit || defined(INCLUDE_CASIntLimit))
#define CASIntLimit_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;

@interface CASIntLimit : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator
                                                   withLong:(int64_t)maxSize;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntLimit)

FOUNDATION_EXPORT void CASIntLimit_initWithCASPrimitiveIterator_OfInt_withLong_(CASIntLimit *self, CASPrimitiveIterator_OfInt *iterator, int64_t maxSize);

FOUNDATION_EXPORT CASIntLimit *new_CASIntLimit_initWithCASPrimitiveIterator_OfInt_withLong_(CASPrimitiveIterator_OfInt *iterator, int64_t maxSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntLimit *create_CASIntLimit_initWithCASPrimitiveIterator_OfInt_withLong_(CASPrimitiveIterator_OfInt *iterator, int64_t maxSize);

J2OBJC_TYPE_LITERAL_HEADER(CASIntLimit)

@compatibility_alias ComAnnimonStreamOperatorIntLimit CASIntLimit;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntLimit")
