//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntSample.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntSample")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntSample
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntSample 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntSample 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntSample

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntSample_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntSample || defined(INCLUDE_CASIntSample))
#define CASIntSample_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;

@interface CASIntSample : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator
                                                    withInt:(int32_t)stepWidth;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntSample)

FOUNDATION_EXPORT void CASIntSample_initWithCASPrimitiveIterator_OfInt_withInt_(CASIntSample *self, CASPrimitiveIterator_OfInt *iterator, int32_t stepWidth);

FOUNDATION_EXPORT CASIntSample *new_CASIntSample_initWithCASPrimitiveIterator_OfInt_withInt_(CASPrimitiveIterator_OfInt *iterator, int32_t stepWidth) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntSample *create_CASIntSample_initWithCASPrimitiveIterator_OfInt_withInt_(CASPrimitiveIterator_OfInt *iterator, int32_t stepWidth);

J2OBJC_TYPE_LITERAL_HEADER(CASIntSample)

@compatibility_alias ComAnnimonStreamOperatorIntSample CASIntSample;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntSample")
