//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/IntScanIdentity.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntScanIdentity")
#ifdef RESTRICT_ComAnnimonStreamOperatorIntScanIdentity
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntScanIdentity 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorIntScanIdentity 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorIntScanIdentity

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntScanIdentity_) && (INCLUDE_ALL_ComAnnimonStreamOperatorIntScanIdentity || defined(INCLUDE_CASIntScanIdentity))
#define CASIntScanIdentity_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@class CASPrimitiveIterator_OfInt;
@class JavaLangInteger;
@protocol CASIntBinaryOperator;

@interface CASIntScanIdentity : CASPrimitiveExtIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator
                                                    withInt:(int32_t)identity
                                   withCASIntBinaryOperator:(id<CASIntBinaryOperator>)accumulator;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntScanIdentity)

FOUNDATION_EXPORT void CASIntScanIdentity_initWithCASPrimitiveIterator_OfInt_withInt_withCASIntBinaryOperator_(CASIntScanIdentity *self, CASPrimitiveIterator_OfInt *iterator, int32_t identity, id<CASIntBinaryOperator> accumulator);

FOUNDATION_EXPORT CASIntScanIdentity *new_CASIntScanIdentity_initWithCASPrimitiveIterator_OfInt_withInt_withCASIntBinaryOperator_(CASPrimitiveIterator_OfInt *iterator, int32_t identity, id<CASIntBinaryOperator> accumulator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntScanIdentity *create_CASIntScanIdentity_initWithCASPrimitiveIterator_OfInt_withInt_withCASIntBinaryOperator_(CASPrimitiveIterator_OfInt *iterator, int32_t identity, id<CASIntBinaryOperator> accumulator);

J2OBJC_TYPE_LITERAL_HEADER(CASIntScanIdentity)

@compatibility_alias ComAnnimonStreamOperatorIntScanIdentity CASIntScanIdentity;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorIntScanIdentity")
