//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongConcat.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongConcat")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongConcat
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongConcat 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongConcat 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongConcat

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongConcat_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongConcat || defined(INCLUDE_CASLongConcat))
#define CASLongConcat_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;

@interface CASLongConcat : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator1
                             withCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator2;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongConcat)

FOUNDATION_EXPORT void CASLongConcat_initWithCASPrimitiveIterator_OfLong_withCASPrimitiveIterator_OfLong_(CASLongConcat *self, CASPrimitiveIterator_OfLong *iterator1, CASPrimitiveIterator_OfLong *iterator2);

FOUNDATION_EXPORT CASLongConcat *new_CASLongConcat_initWithCASPrimitiveIterator_OfLong_withCASPrimitiveIterator_OfLong_(CASPrimitiveIterator_OfLong *iterator1, CASPrimitiveIterator_OfLong *iterator2) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongConcat *create_CASLongConcat_initWithCASPrimitiveIterator_OfLong_withCASPrimitiveIterator_OfLong_(CASPrimitiveIterator_OfLong *iterator1, CASPrimitiveIterator_OfLong *iterator2);

J2OBJC_TYPE_LITERAL_HEADER(CASLongConcat)

@compatibility_alias ComAnnimonStreamOperatorLongConcat CASLongConcat;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongConcat")
