//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongPeek.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongPeek")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongPeek
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongPeek 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongPeek 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongPeek

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongPeek_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongPeek || defined(INCLUDE_CASLongPeek))
#define CASLongPeek_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;
@protocol CASLongConsumer;

@interface CASLongPeek : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator
                                         withCASLongConsumer:(id<CASLongConsumer>)action;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongPeek)

FOUNDATION_EXPORT void CASLongPeek_initWithCASPrimitiveIterator_OfLong_withCASLongConsumer_(CASLongPeek *self, CASPrimitiveIterator_OfLong *iterator, id<CASLongConsumer> action);

FOUNDATION_EXPORT CASLongPeek *new_CASLongPeek_initWithCASPrimitiveIterator_OfLong_withCASLongConsumer_(CASPrimitiveIterator_OfLong *iterator, id<CASLongConsumer> action) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongPeek *create_CASLongPeek_initWithCASPrimitiveIterator_OfLong_withCASLongConsumer_(CASPrimitiveIterator_OfLong *iterator, id<CASLongConsumer> action);

J2OBJC_TYPE_LITERAL_HEADER(CASLongPeek)

@compatibility_alias ComAnnimonStreamOperatorLongPeek CASLongPeek;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongPeek")
