//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongFilter.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongFilter")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongFilter
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongFilter 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongFilter 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongFilter

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongFilter_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongFilter || defined(INCLUDE_CASLongFilter))
#define CASLongFilter_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;
@protocol CASLongPredicate;

@interface CASLongFilter : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator
                                        withCASLongPredicate:(id<CASLongPredicate>)predicate;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongFilter)

FOUNDATION_EXPORT void CASLongFilter_initWithCASPrimitiveIterator_OfLong_withCASLongPredicate_(CASLongFilter *self, CASPrimitiveIterator_OfLong *iterator, id<CASLongPredicate> predicate);

FOUNDATION_EXPORT CASLongFilter *new_CASLongFilter_initWithCASPrimitiveIterator_OfLong_withCASLongPredicate_(CASPrimitiveIterator_OfLong *iterator, id<CASLongPredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongFilter *create_CASLongFilter_initWithCASPrimitiveIterator_OfLong_withCASLongPredicate_(CASPrimitiveIterator_OfLong *iterator, id<CASLongPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASLongFilter)

@compatibility_alias ComAnnimonStreamOperatorLongFilter CASLongFilter;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongFilter")
