//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongScanIdentity.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongScanIdentity")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongScanIdentity
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongScanIdentity 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongScanIdentity 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongScanIdentity

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongScanIdentity_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongScanIdentity || defined(INCLUDE_CASLongScanIdentity))
#define CASLongScanIdentity_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@class CASPrimitiveIterator_OfLong;
@class JavaLangLong;
@protocol CASLongBinaryOperator;

@interface CASLongScanIdentity : CASPrimitiveExtIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator
                                                    withLong:(int64_t)identity
                                   withCASLongBinaryOperator:(id<CASLongBinaryOperator>)accumulator;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongScanIdentity)

FOUNDATION_EXPORT void CASLongScanIdentity_initWithCASPrimitiveIterator_OfLong_withLong_withCASLongBinaryOperator_(CASLongScanIdentity *self, CASPrimitiveIterator_OfLong *iterator, int64_t identity, id<CASLongBinaryOperator> accumulator);

FOUNDATION_EXPORT CASLongScanIdentity *new_CASLongScanIdentity_initWithCASPrimitiveIterator_OfLong_withLong_withCASLongBinaryOperator_(CASPrimitiveIterator_OfLong *iterator, int64_t identity, id<CASLongBinaryOperator> accumulator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongScanIdentity *create_CASLongScanIdentity_initWithCASPrimitiveIterator_OfLong_withLong_withCASLongBinaryOperator_(CASPrimitiveIterator_OfLong *iterator, int64_t identity, id<CASLongBinaryOperator> accumulator);

J2OBJC_TYPE_LITERAL_HEADER(CASLongScanIdentity)

@compatibility_alias ComAnnimonStreamOperatorLongScanIdentity CASLongScanIdentity;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongScanIdentity")
