//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongSkip.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongSkip")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongSkip
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongSkip 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongSkip 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongSkip

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongSkip_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongSkip || defined(INCLUDE_CASLongSkip))
#define CASLongSkip_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;

@interface CASLongSkip : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator
                                                    withLong:(int64_t)n;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongSkip)

FOUNDATION_EXPORT void CASLongSkip_initWithCASPrimitiveIterator_OfLong_withLong_(CASLongSkip *self, CASPrimitiveIterator_OfLong *iterator, int64_t n);

FOUNDATION_EXPORT CASLongSkip *new_CASLongSkip_initWithCASPrimitiveIterator_OfLong_withLong_(CASPrimitiveIterator_OfLong *iterator, int64_t n) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongSkip *create_CASLongSkip_initWithCASPrimitiveIterator_OfLong_withLong_(CASPrimitiveIterator_OfLong *iterator, int64_t n);

J2OBJC_TYPE_LITERAL_HEADER(CASLongSkip)

@compatibility_alias ComAnnimonStreamOperatorLongSkip CASLongSkip;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongSkip")
