//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongRangeClosed.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongRangeClosed")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongRangeClosed
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongRangeClosed 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongRangeClosed 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongRangeClosed

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongRangeClosed_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongRangeClosed || defined(INCLUDE_CASLongRangeClosed))
#define CASLongRangeClosed_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;

@interface CASLongRangeClosed : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithLong:(int64_t)startInclusive
                             withLong:(int64_t)endInclusive;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongRangeClosed)

FOUNDATION_EXPORT void CASLongRangeClosed_initWithLong_withLong_(CASLongRangeClosed *self, int64_t startInclusive, int64_t endInclusive);

FOUNDATION_EXPORT CASLongRangeClosed *new_CASLongRangeClosed_initWithLong_withLong_(int64_t startInclusive, int64_t endInclusive) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongRangeClosed *create_CASLongRangeClosed_initWithLong_withLong_(int64_t startInclusive, int64_t endInclusive);

J2OBJC_TYPE_LITERAL_HEADER(CASLongRangeClosed)

@compatibility_alias ComAnnimonStreamOperatorLongRangeClosed CASLongRangeClosed;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongRangeClosed")
