//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongDropWhile.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongDropWhile")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongDropWhile
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongDropWhile 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongDropWhile 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongDropWhile

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongDropWhile_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongDropWhile || defined(INCLUDE_CASLongDropWhile))
#define CASLongDropWhile_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@class CASPrimitiveIterator_OfLong;
@protocol CASLongPredicate;

@interface CASLongDropWhile : CASPrimitiveExtIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator
                                        withCASLongPredicate:(id<CASLongPredicate>)predicate;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongDropWhile)

FOUNDATION_EXPORT void CASLongDropWhile_initWithCASPrimitiveIterator_OfLong_withCASLongPredicate_(CASLongDropWhile *self, CASPrimitiveIterator_OfLong *iterator, id<CASLongPredicate> predicate);

FOUNDATION_EXPORT CASLongDropWhile *new_CASLongDropWhile_initWithCASPrimitiveIterator_OfLong_withCASLongPredicate_(CASPrimitiveIterator_OfLong *iterator, id<CASLongPredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongDropWhile *create_CASLongDropWhile_initWithCASPrimitiveIterator_OfLong_withCASLongPredicate_(CASPrimitiveIterator_OfLong *iterator, id<CASLongPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASLongDropWhile)

@compatibility_alias ComAnnimonStreamOperatorLongDropWhile CASLongDropWhile;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongDropWhile")
