//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/LongSorted.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongSorted")
#ifdef RESTRICT_ComAnnimonStreamOperatorLongSorted
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongSorted 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorLongSorted 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorLongSorted

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongSorted_) && (INCLUDE_ALL_ComAnnimonStreamOperatorLongSorted || defined(INCLUDE_CASLongSorted))
#define CASLongSorted_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#define INCLUDE_CASPrimitiveExtIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveExtIterator.h"

@class CASPrimitiveIterator_OfLong;

@interface CASLongSorted : CASPrimitiveExtIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongSorted)

FOUNDATION_EXPORT void CASLongSorted_initWithCASPrimitiveIterator_OfLong_(CASLongSorted *self, CASPrimitiveIterator_OfLong *iterator);

FOUNDATION_EXPORT CASLongSorted *new_CASLongSorted_initWithCASPrimitiveIterator_OfLong_(CASPrimitiveIterator_OfLong *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongSorted *create_CASLongSorted_initWithCASPrimitiveIterator_OfLong_(CASPrimitiveIterator_OfLong *iterator);

J2OBJC_TYPE_LITERAL_HEADER(CASLongSorted)

@compatibility_alias ComAnnimonStreamOperatorLongSorted CASLongSorted;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorLongSorted")
