//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjFilter.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjFilter")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjFilter
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjFilter 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjFilter 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjFilter

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjFilter_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjFilter || defined(INCLUDE_CASObjFilter))
#define CASObjFilter_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class JavaLangBoolean;
@protocol CASPredicate;
@protocol JavaUtilFunctionConsumer;

@interface CASObjFilter : NSObject < JavaUtilIterator >

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                 withCASPredicate:(id<CASPredicate>)predicate;

- (bool)hasNext;

- (id)next;

- (void)remove;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjFilter)

FOUNDATION_EXPORT void CASObjFilter_initWithJavaUtilIterator_withCASPredicate_(CASObjFilter *self, id<JavaUtilIterator> iterator, id<CASPredicate> predicate);

FOUNDATION_EXPORT CASObjFilter *new_CASObjFilter_initWithJavaUtilIterator_withCASPredicate_(id<JavaUtilIterator> iterator, id<CASPredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjFilter *create_CASObjFilter_initWithJavaUtilIterator_withCASPredicate_(id<JavaUtilIterator> iterator, id<CASPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASObjFilter)

@compatibility_alias ComAnnimonStreamOperatorObjFilter CASObjFilter;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjFilter")
