//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjFlatMap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMap")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjFlatMap
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMap 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMap 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjFlatMap

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjFlatMap_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMap || defined(INCLUDE_CASObjFlatMap))
#define CASObjFlatMap_

#define RESTRICT_ComAnnimonStreamIteratorLsaExtIterator 1
#define INCLUDE_CASLsaExtIterator 1
#include "com/annimon/stream/iterator/LsaExtIterator.h"

@protocol CASFunction;
@protocol JavaUtilIterator;

@interface CASObjFlatMap : CASLsaExtIterator

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                  withCASFunction:(id<CASFunction>)mapper;

#pragma mark Protected

- (void)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjFlatMap)

FOUNDATION_EXPORT void CASObjFlatMap_initWithJavaUtilIterator_withCASFunction_(CASObjFlatMap *self, id<JavaUtilIterator> iterator, id<CASFunction> mapper);

FOUNDATION_EXPORT CASObjFlatMap *new_CASObjFlatMap_initWithJavaUtilIterator_withCASFunction_(id<JavaUtilIterator> iterator, id<CASFunction> mapper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjFlatMap *create_CASObjFlatMap_initWithJavaUtilIterator_withCASFunction_(id<JavaUtilIterator> iterator, id<CASFunction> mapper);

J2OBJC_TYPE_LITERAL_HEADER(CASObjFlatMap)

@compatibility_alias ComAnnimonStreamOperatorObjFlatMap CASObjFlatMap;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjFlatMap")
