//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjPeek.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjPeek")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjPeek
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjPeek 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjPeek 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjPeek

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjPeek_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjPeek || defined(INCLUDE_CASObjPeek))
#define CASObjPeek_

#define RESTRICT_ComAnnimonStreamIteratorLsaIterator 1
#define INCLUDE_CASLsaIterator 1
#include "com/annimon/stream/iterator/LsaIterator.h"

@class JavaLangBoolean;
@protocol CASConsumer;
@protocol JavaUtilIterator;

@interface CASObjPeek : CASLsaIterator

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                  withCASConsumer:(id<CASConsumer>)action;

- (bool)hasNext;

- (id)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjPeek)

FOUNDATION_EXPORT void CASObjPeek_initWithJavaUtilIterator_withCASConsumer_(CASObjPeek *self, id<JavaUtilIterator> iterator, id<CASConsumer> action);

FOUNDATION_EXPORT CASObjPeek *new_CASObjPeek_initWithJavaUtilIterator_withCASConsumer_(id<JavaUtilIterator> iterator, id<CASConsumer> action) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjPeek *create_CASObjPeek_initWithJavaUtilIterator_withCASConsumer_(id<JavaUtilIterator> iterator, id<CASConsumer> action);

J2OBJC_TYPE_LITERAL_HEADER(CASObjPeek)

@compatibility_alias ComAnnimonStreamOperatorObjPeek CASObjPeek;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjPeek")
