//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/operator/ObjSkip.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjSkip")
#ifdef RESTRICT_ComAnnimonStreamOperatorObjSkip
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjSkip 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOperatorObjSkip 1
#endif
#undef RESTRICT_ComAnnimonStreamOperatorObjSkip

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjSkip_) && (INCLUDE_ALL_ComAnnimonStreamOperatorObjSkip || defined(INCLUDE_CASObjSkip))
#define CASObjSkip_

#define RESTRICT_ComAnnimonStreamIteratorLsaIterator 1
#define INCLUDE_CASLsaIterator 1
#include "com/annimon/stream/iterator/LsaIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;
@protocol JavaUtilIterator;

@interface CASObjSkip : CASLsaIterator

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                                         withLong:(int64_t)n;

- (bool)hasNext;

- (id)nextIteration;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjSkip)

FOUNDATION_EXPORT void CASObjSkip_initWithJavaUtilIterator_withLong_(CASObjSkip *self, id<JavaUtilIterator> iterator, int64_t n);

FOUNDATION_EXPORT CASObjSkip *new_CASObjSkip_initWithJavaUtilIterator_withLong_(id<JavaUtilIterator> iterator, int64_t n) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASObjSkip *create_CASObjSkip_initWithJavaUtilIterator_withLong_(id<JavaUtilIterator> iterator, int64_t n);

J2OBJC_TYPE_LITERAL_HEADER(CASObjSkip)

@compatibility_alias ComAnnimonStreamOperatorObjSkip CASObjSkip;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOperatorObjSkip")
