//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/internal/SpinedBuffer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamInternalSpinedBuffer")
#ifdef RESTRICT_ComAnnimonStreamInternalSpinedBuffer
#define INCLUDE_ALL_ComAnnimonStreamInternalSpinedBuffer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamInternalSpinedBuffer 1
#endif
#undef RESTRICT_ComAnnimonStreamInternalSpinedBuffer
#ifdef INCLUDE_CASSpinedBuffer_OfDouble
#define INCLUDE_CASSpinedBuffer_OfPrimitive 1
#endif
#ifdef INCLUDE_CASSpinedBuffer_OfLong
#define INCLUDE_CASSpinedBuffer_OfPrimitive 1
#endif
#ifdef INCLUDE_CASSpinedBuffer_OfInt
#define INCLUDE_CASSpinedBuffer_OfPrimitive 1
#endif

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASSpinedBuffer_) && (INCLUDE_ALL_ComAnnimonStreamInternalSpinedBuffer || defined(INCLUDE_CASSpinedBuffer))
#define CASSpinedBuffer_

@class JavaLangInteger;

@interface CASSpinedBuffer : NSObject
@property (readonly, class) int32_t MIN_CHUNK_POWER NS_SWIFT_NAME(MIN_CHUNK_POWER);
@property (readonly, class) int32_t MIN_CHUNK_SIZE NS_SWIFT_NAME(MIN_CHUNK_SIZE);
@property (readonly, class) int32_t MIN_SPINE_SIZE NS_SWIFT_NAME(MIN_SPINE_SIZE);

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASSpinedBuffer)

/*!
 @brief Minimum power-of-two for the first chunk.
 */
inline int32_t CASSpinedBuffer_get_MIN_CHUNK_POWER(void);
#define CASSpinedBuffer_MIN_CHUNK_POWER 4
J2OBJC_STATIC_FIELD_CONSTANT(CASSpinedBuffer, MIN_CHUNK_POWER, int32_t)

/*!
 @brief Minimum size for the first chunk.
 */
inline int32_t CASSpinedBuffer_get_MIN_CHUNK_SIZE(void);
#define CASSpinedBuffer_MIN_CHUNK_SIZE 16
J2OBJC_STATIC_FIELD_CONSTANT(CASSpinedBuffer, MIN_CHUNK_SIZE, int32_t)

/*!
 @brief Minimum array size for array-of-chunks.
 */
inline int32_t CASSpinedBuffer_get_MIN_SPINE_SIZE(void);
#define CASSpinedBuffer_MIN_SPINE_SIZE 8
J2OBJC_STATIC_FIELD_CONSTANT(CASSpinedBuffer, MIN_SPINE_SIZE, int32_t)

J2OBJC_TYPE_LITERAL_HEADER(CASSpinedBuffer)

@compatibility_alias ComAnnimonStreamInternalSpinedBuffer CASSpinedBuffer;


#endif

#if !defined (CASSpinedBuffer_OfPrimitive_) && (INCLUDE_ALL_ComAnnimonStreamInternalSpinedBuffer || defined(INCLUDE_CASSpinedBuffer_OfPrimitive))
#define CASSpinedBuffer_OfPrimitive_

#define RESTRICT_JavaLangIterable 1
#define INCLUDE_JavaLangIterable 1
#include "java/lang/Iterable.h"

@class IOSLongArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilIterator;
@protocol JavaUtilSpliterator;

/*!
 @brief Base class for a data structure for gathering elements into a buffer and then
  iterating them.Maintains an array of increasingly sized arrays, so there is
  no copying cost associated with growing the data structure.
 */
@interface CASSpinedBuffer_OfPrimitive : NSObject < JavaLangIterable > {
 @public
  /*!
   @brief log2 of the size of the first chunk.
   */
  int32_t initialChunkPower_;
  /*!
   @brief Index of the *next* element to write; may point into, or just outside of,
  the current chunk.
   */
  int32_t elementIndex_;
  /*!
   @brief Index of the *current* chunk in the spine array, if the spine array is
  non-null.
   */
  int32_t spineIndex_;
  /*!
   @brief Count of elements in all prior chunks.
   */
  IOSLongArray *priorElementCount_;
  id curChunk_;
  IOSObjectArray *spine_;
}

#pragma mark Public

- (id)asPrimitiveArray;

/*!
 @brief Remove all data from the buffer
 */
- (void)clear;

/*!
 @brief How many elements are currently in the buffer?
 */
- (int64_t)count;

/*!
 @brief Is the buffer currently empty?
 */
- (bool)isEmpty;

- (id<JavaUtilIterator>)iterator;

#pragma mark Protected

- (int32_t)arrayLengthWithId:(id)array;

- (id)newArrayWithInt:(int32_t)size OBJC_METHOD_FAMILY_NONE;

- (IOSObjectArray *)newArrayArrayWithInt:(int32_t)size OBJC_METHOD_FAMILY_NONE;

#pragma mark Package-Private

- (instancetype _Nonnull)init;

/*!
 @brief Construct with a specified initial capacity.
 @param initialCapacity The minimum expected number of elements
 */
- (instancetype _Nonnull)initWithInt:(int32_t)initialCapacity;

- (int64_t)capacity;

- (int32_t)chunkForWithLong:(int64_t)index;

/*!
 @brief How big should the nth chunk be?
 */
- (int32_t)chunkSizeWithInt:(int32_t)n;

- (void)copyIntoWithId:(id)array
               withInt:(int32_t)offset OBJC_METHOD_FAMILY_NONE;

- (void)ensureCapacityWithLong:(int64_t)targetSize;

- (void)increaseCapacity;

- (void)preAccept;

@end

J2OBJC_EMPTY_STATIC_INIT(CASSpinedBuffer_OfPrimitive)

J2OBJC_FIELD_SETTER(CASSpinedBuffer_OfPrimitive, priorElementCount_, IOSLongArray *)
J2OBJC_FIELD_SETTER(CASSpinedBuffer_OfPrimitive, curChunk_, id)
J2OBJC_FIELD_SETTER(CASSpinedBuffer_OfPrimitive, spine_, IOSObjectArray *)

FOUNDATION_EXPORT void CASSpinedBuffer_OfPrimitive_initWithInt_(CASSpinedBuffer_OfPrimitive *self, int32_t initialCapacity);

FOUNDATION_EXPORT void CASSpinedBuffer_OfPrimitive_init(CASSpinedBuffer_OfPrimitive *self);

J2OBJC_TYPE_LITERAL_HEADER(CASSpinedBuffer_OfPrimitive)


#endif

#if !defined (CASSpinedBuffer_OfInt_) && (INCLUDE_ALL_ComAnnimonStreamInternalSpinedBuffer || defined(INCLUDE_CASSpinedBuffer_OfInt))
#define CASSpinedBuffer_OfInt_

#define RESTRICT_ComAnnimonStreamFunctionIntConsumer 1
#define INCLUDE_CASIntConsumer 1
#include "com/annimon/stream/function/IntConsumer.h"

@class CASPrimitiveIterator_OfInt;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangInteger;
@class JavaLangLong;

@interface CASSpinedBuffer_OfInt : CASSpinedBuffer_OfPrimitive < CASIntConsumer >

#pragma mark Public

- (void)acceptWithInt:(int32_t)i;

- (IOSIntArray *)asPrimitiveArray;

- (int32_t)getWithLong:(int64_t)index;

- (CASPrimitiveIterator_OfInt *)iterator;

- (IOSIntArray *)newArrayWithInt:(int32_t)size OBJC_METHOD_FAMILY_NONE;

#pragma mark Protected

- (int32_t)arrayLengthWithId:(IOSIntArray *)array;

- (IOSObjectArray *)newArrayArrayWithInt:(int32_t)size OBJC_METHOD_FAMILY_NONE;

#pragma mark Package-Private

- (instancetype _Nonnull)init;

- (instancetype _Nonnull)initWithInt:(int32_t)initialCapacity;

@end

J2OBJC_EMPTY_STATIC_INIT(CASSpinedBuffer_OfInt)

FOUNDATION_EXPORT void CASSpinedBuffer_OfInt_init(CASSpinedBuffer_OfInt *self);

FOUNDATION_EXPORT CASSpinedBuffer_OfInt *new_CASSpinedBuffer_OfInt_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASSpinedBuffer_OfInt *create_CASSpinedBuffer_OfInt_init(void);

FOUNDATION_EXPORT void CASSpinedBuffer_OfInt_initWithInt_(CASSpinedBuffer_OfInt *self, int32_t initialCapacity);

FOUNDATION_EXPORT CASSpinedBuffer_OfInt *new_CASSpinedBuffer_OfInt_initWithInt_(int32_t initialCapacity) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASSpinedBuffer_OfInt *create_CASSpinedBuffer_OfInt_initWithInt_(int32_t initialCapacity);

J2OBJC_TYPE_LITERAL_HEADER(CASSpinedBuffer_OfInt)


#endif

#if !defined (CASSpinedBuffer_OfLong_) && (INCLUDE_ALL_ComAnnimonStreamInternalSpinedBuffer || defined(INCLUDE_CASSpinedBuffer_OfLong))
#define CASSpinedBuffer_OfLong_

#define RESTRICT_ComAnnimonStreamFunctionLongConsumer 1
#define INCLUDE_CASLongConsumer 1
#include "com/annimon/stream/function/LongConsumer.h"

@class CASPrimitiveIterator_OfLong;
@class IOSLongArray;
@class IOSObjectArray;
@class JavaLangInteger;
@class JavaLangLong;

@interface CASSpinedBuffer_OfLong : CASSpinedBuffer_OfPrimitive < CASLongConsumer >

#pragma mark Public

- (void)acceptWithLong:(int64_t)i;

- (IOSLongArray *)asPrimitiveArray;

- (int64_t)getWithLong:(int64_t)index;

- (CASPrimitiveIterator_OfLong *)iterator;

- (IOSLongArray *)newArrayWithInt:(int32_t)size OBJC_METHOD_FAMILY_NONE;

#pragma mark Protected

- (int32_t)arrayLengthWithId:(IOSLongArray *)array;

- (IOSObjectArray *)newArrayArrayWithInt:(int32_t)size OBJC_METHOD_FAMILY_NONE;

#pragma mark Package-Private

- (instancetype _Nonnull)init;

- (instancetype _Nonnull)initWithInt:(int32_t)initialCapacity;

@end

J2OBJC_EMPTY_STATIC_INIT(CASSpinedBuffer_OfLong)

FOUNDATION_EXPORT void CASSpinedBuffer_OfLong_init(CASSpinedBuffer_OfLong *self);

FOUNDATION_EXPORT CASSpinedBuffer_OfLong *new_CASSpinedBuffer_OfLong_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASSpinedBuffer_OfLong *create_CASSpinedBuffer_OfLong_init(void);

FOUNDATION_EXPORT void CASSpinedBuffer_OfLong_initWithInt_(CASSpinedBuffer_OfLong *self, int32_t initialCapacity);

FOUNDATION_EXPORT CASSpinedBuffer_OfLong *new_CASSpinedBuffer_OfLong_initWithInt_(int32_t initialCapacity) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASSpinedBuffer_OfLong *create_CASSpinedBuffer_OfLong_initWithInt_(int32_t initialCapacity);

J2OBJC_TYPE_LITERAL_HEADER(CASSpinedBuffer_OfLong)


#endif

#if !defined (CASSpinedBuffer_OfDouble_) && (INCLUDE_ALL_ComAnnimonStreamInternalSpinedBuffer || defined(INCLUDE_CASSpinedBuffer_OfDouble))
#define CASSpinedBuffer_OfDouble_

#define RESTRICT_ComAnnimonStreamFunctionDoubleConsumer 1
#define INCLUDE_CASDoubleConsumer 1
#include "com/annimon/stream/function/DoubleConsumer.h"

@class CASPrimitiveIterator_OfDouble;
@class IOSDoubleArray;
@class IOSObjectArray;
@class JavaLangDouble;
@class JavaLangInteger;
@class JavaLangLong;

@interface CASSpinedBuffer_OfDouble : CASSpinedBuffer_OfPrimitive < CASDoubleConsumer >

#pragma mark Public

- (void)acceptWithDouble:(double)i;

- (IOSDoubleArray *)asPrimitiveArray;

- (double)getWithLong:(int64_t)index;

- (CASPrimitiveIterator_OfDouble *)iterator;

- (IOSDoubleArray *)newArrayWithInt:(int32_t)size OBJC_METHOD_FAMILY_NONE;

#pragma mark Protected

- (int32_t)arrayLengthWithId:(IOSDoubleArray *)array;

- (IOSObjectArray *)newArrayArrayWithInt:(int32_t)size OBJC_METHOD_FAMILY_NONE;

#pragma mark Package-Private

- (instancetype _Nonnull)init;

- (instancetype _Nonnull)initWithInt:(int32_t)initialCapacity;

@end

J2OBJC_EMPTY_STATIC_INIT(CASSpinedBuffer_OfDouble)

FOUNDATION_EXPORT void CASSpinedBuffer_OfDouble_init(CASSpinedBuffer_OfDouble *self);

FOUNDATION_EXPORT CASSpinedBuffer_OfDouble *new_CASSpinedBuffer_OfDouble_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASSpinedBuffer_OfDouble *create_CASSpinedBuffer_OfDouble_init(void);

FOUNDATION_EXPORT void CASSpinedBuffer_OfDouble_initWithInt_(CASSpinedBuffer_OfDouble *self, int32_t initialCapacity);

FOUNDATION_EXPORT CASSpinedBuffer_OfDouble *new_CASSpinedBuffer_OfDouble_initWithInt_(int32_t initialCapacity) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASSpinedBuffer_OfDouble *create_CASSpinedBuffer_OfDouble_initWithInt_(int32_t initialCapacity);

J2OBJC_TYPE_LITERAL_HEADER(CASSpinedBuffer_OfDouble)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamInternalSpinedBuffer")
