//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/Exceptional.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamExceptional")
#ifdef RESTRICT_ComAnnimonStreamExceptional
#define INCLUDE_ALL_ComAnnimonStreamExceptional 0
#else
#define INCLUDE_ALL_ComAnnimonStreamExceptional 1
#endif
#undef RESTRICT_ComAnnimonStreamExceptional

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASExceptional_) && (INCLUDE_ALL_ComAnnimonStreamExceptional || defined(INCLUDE_CASExceptional))
#define CASExceptional_

@class CASOptional;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangThrowable;
@class NSString;
@protocol CASConsumer;
@protocol CASFunction;
@protocol CASSupplier;
@protocol CASThrowableFunction;
@protocol CASThrowableSupplier;

/*!
 @brief A container for values which provided by <code>ThrowableSupplier</code>.
 Stores value which provided by <code>ThrowableSupplier</code> or an exception which were thrown. 
 @code
<code>
      Exceptional.of(new ThrowableSupplier&lt;String, Throwable&gt;() {
                    &#64;Override
           public String get() throws Throwable {
               return IOUtils.read(inputStream);
           }
       }).ifExceptionIs(IOException.class, new Consumer&lt;IOException&gt;() {
                    &#64;Override
           public void accept(IOException exception) {
               logger.log(Level.WARNING, "read file", exception);
           }
       }).getOrElse("default string");
       Exceptional.of(() -&gt; IOUtils.readBytes(inputStream)).getOrElse(new byte[0]); 
  </code>
@endcode
 */
@interface CASExceptional : NSObject

#pragma mark Public

/*!
 @brief Applies custom operator on <code>Exceptional</code>.
 @param function a transforming function
 @return a result of the transforming function
 @throw NullPointerExceptionif <code>function</code> is null
 @since 1.1.9
 */
- (id)customWithCASFunction:(id<CASFunction>)function;

- (bool)isEqual:(id)obj;

/*!
 @brief Returns inner value.
 @return inner value.
 */
- (id)get;

/*!
 @brief Returns exception.
 @return exception
 */
- (JavaLangThrowable *)getException;

/*!
 @brief Wraps inner value with <code>Optional</code> container
 @return an <code>Optional</code>
 */
- (CASOptional *)getOptional;

/*!
 @brief Returns inner value if there were no exceptions, otherwise returns value produced by supplier function.
 @param other the supplier function that produces value if there were any exception
 @return inner value if there were no exceptions, otherwise value produced by supplier function
 @since 1.1.9
 */
- (id)getOrElseWithCASSupplier:(id<CASSupplier>)other;

/*!
 @brief Returns inner value if there were no exceptions, otherwise returns <code>other</code>.
 @param other the value to be returned if there were any exception
 @return inner value if there were no exceptions, otherwise <code>other</code>
 */
- (id)getOrElseWithId:(id)other;

/*!
 @brief Returns inner value if there were no exceptions, otherwise throws an exception.
 @return inner value if there were no exceptions
 @throw Throwablethat was thrown in supplier function
 */
- (id)getOrThrow;

/*!
 @brief Returns inner value if there were no exceptions, otherwise throws the given <code>exception</code>.
 @param exception an exception to be thrown
 @return inner value if there were no exceptions
 @throw Eif there were exceptions in supplier function
 */
- (id)getOrThrowWithJavaLangThrowable:(JavaLangThrowable *)exception;

/*!
 @brief Returns inner value if there were no exceptions, otherwise throws <code>RuntimeException</code>.
 @return inner value if there were no exceptions
 @throw RuntimeExceptionwith wrapped exception which was thrown in supplier function
 */
- (id)getOrThrowRuntimeException;

- (NSUInteger)hash;

/*!
 @brief Invokes consumer function if there were any exception.
 @param consumer a consumer function
 @return an <code>Exceptional</code>
 */
- (CASExceptional *)ifExceptionWithCASConsumer:(id<CASConsumer>)consumer;

/*!
 @brief Invokes consumer function if exception class matches <code>throwableClass</code>.
 @param throwableClass the class of an exception to be compared
 @param consumer a consumer function
 @return an <code>Exceptional</code>
 */
- (CASExceptional *)ifExceptionIsWithIOSClass:(IOSClass *)throwableClass
                              withCASConsumer:(id<CASConsumer>)consumer;

/*!
 @brief Invokes consumer function with value if present.
 @param consumer a consumer function
 @return this <code>Exceptional</code>
 @since 1.1.2
 */
- (CASExceptional *)ifPresentWithCASConsumer:(id<CASConsumer>)consumer;

/*!
 @brief Checks value present (i.e.there were no exceptions).
 @return <code>true</code> if a value present, <code>false</code> otherwise
 */
- (bool)isPresent;

/*!
 @brief Invokes mapping function on inner value if there were no exceptions.
 @param mapper mapping function
 @return an <code>Exceptional</code> with transformed value if there were no exceptions
 @throw NullPointerExceptionif <code>mapper</code> is null
 */
- (CASExceptional *)mapWithCASThrowableFunction:(id<CASThrowableFunction>)mapper;

/*!
 @brief Returns an <code>Exceptional</code> with throwable already set.
 @param throwable throwable instance
 @return an <code>Exceptional</code>
 */
+ (CASExceptional *)ofWithJavaLangThrowable:(JavaLangThrowable *)throwable;

/*!
 @brief Returns an <code>Exceptional</code> with value provided by given <code>ThrowableSupplier</code> function.
 @param supplier a supplier function
 @return an <code>Exceptional</code>
 */
+ (CASExceptional *)ofWithCASThrowableSupplier:(id<CASThrowableSupplier>)supplier;

/*!
 @brief Returns current <code>Exceptional</code> if there were no exceptions, otherwise
  returns an <code>Exceptional</code> produced by supplier function.
 @param supplier supplier function that produced an <code>Exceptional</code>  to be returned
 @return this <code>Exceptional</code> if there were no exceptions, otherwise
          an <code>Exceptional</code> produced by supplier function
 @throw NullPointerExceptionif <code>supplier</code> or its result is null
 */
- (CASExceptional *)or__WithCASSupplier:(id<CASSupplier>)supplier;

/*!
 @brief Returns current <code>Exceptional</code> if there were no exceptions, otherwise
  calls <code>function</code> and wraps produced result with an <code>Exceptional</code>.
 @param function recovering function
 @return this <code>Exceptional</code> if there were no exceptions, otherwise
          an <code>Exceptional</code> with wrapped recovering function result
 @throw NullPointerExceptionif <code>function</code> is null
 @since 1.1.2
 */
- (CASExceptional *)recoverWithCASThrowableFunction:(id<CASThrowableFunction>)function;

/*!
 @brief Returns current <code>Exceptional</code> if there were no exceptions, otherwise
  returns an <code>Exceptional</code> produced by <code>function</code>.
 @param function recovering function
 @return this <code>Exceptional</code> if there were no exceptions, otherwise
          an <code>Exceptional</code> produced by recovering function
 @throw NullPointerExceptionif <code>function</code> or produced result is null
 @since 1.1.2
 */
- (CASExceptional *)recoverWithWithCASFunction:(id<CASFunction>)function;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASExceptional)

FOUNDATION_EXPORT CASExceptional *CASExceptional_ofWithCASThrowableSupplier_(id<CASThrowableSupplier> supplier);

FOUNDATION_EXPORT CASExceptional *CASExceptional_ofWithJavaLangThrowable_(JavaLangThrowable *throwable);

J2OBJC_TYPE_LITERAL_HEADER(CASExceptional)

@compatibility_alias ComAnnimonStreamExceptional CASExceptional;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamExceptional")
