//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/OptionalBoolean.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOptionalBoolean")
#ifdef RESTRICT_ComAnnimonStreamOptionalBoolean
#define INCLUDE_ALL_ComAnnimonStreamOptionalBoolean 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOptionalBoolean 1
#endif
#undef RESTRICT_ComAnnimonStreamOptionalBoolean

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASOptionalBoolean_) && (INCLUDE_ALL_ComAnnimonStreamOptionalBoolean || defined(INCLUDE_CASOptionalBoolean))
#define CASOptionalBoolean_

@class CASOptional;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol CASBooleanConsumer;
@protocol CASBooleanFunction;
@protocol CASBooleanPredicate;
@protocol CASBooleanSupplier;
@protocol CASFunction;
@protocol CASSupplier;
@protocol JavaLangRunnable;

/*!
 @brief A container object which may or may not contain a <code>boolean</code> value.
 @since 1.1.8
 - seealso: Optional
 */
@interface CASOptionalBoolean : NSObject

#pragma mark Public

/*!
 @brief Applies custom operator on <code>OptionalBoolean</code>.
 @param function a transforming function
 @return a result of the transforming function
 @throw NullPointerExceptionif <code>function</code> is null
 @since 1.1.9
 */
- (id)customWithCASFunction:(id<CASFunction>)function;

/*!
 @brief Returns an empty <code>OptionalBoolean</code> instance.
 @return an empty <code>OptionalBoolean</code>
 */
+ (CASOptionalBoolean *)empty;

- (bool)isEqual:(id)obj;

/*!
 @brief Invokes action function if value is absent.
 @param action action that invokes if value absent
 @return this <code>OptionalBoolean</code>
 */
- (CASOptionalBoolean *)executeIfAbsentWithJavaLangRunnable:(id<JavaLangRunnable>)action;

/*!
 @brief Invokes consumer function with the value if present.
 This method same as <code>ifPresent</code>, but does not breaks chaining
 @param consumer consumer function
 @return this <code>OptionalBoolean</code>
 - seealso: #ifPresent(BooleanConsumer)
 */
- (CASOptionalBoolean *)executeIfPresentWithCASBooleanConsumer:(id<CASBooleanConsumer>)consumer;

/*!
 @brief Performs filtering on inner value if it is present.
 @param predicate a predicate function
 @return this <code>OptionalBoolean</code> if the value is present and matches predicate,
          otherwise an empty <code>OptionalBoolean</code>
 */
- (CASOptionalBoolean *)filterWithCASBooleanPredicate:(id<CASBooleanPredicate>)predicate;

/*!
 @brief Performs negated filtering on inner value if it is present.
 @param predicate a predicate function
 @return this <code>OptionalBoolean</code> if the value is present and doesn't matches predicate,
               otherwise an empty <code>OptionalBoolean</code>
 @since 1.1.9
 */
- (CASOptionalBoolean *)filterNotWithCASBooleanPredicate:(id<CASBooleanPredicate>)predicate;

/*!
 @brief Returns an inner value if present, otherwise throws <code>NoSuchElementException</code>.
 Since 1.2.0 prefer <code>orElseThrow()</code> method as it has readable name.
 @return the inner value of this <code>OptionalBoolean</code>
 @throw NoSuchElementExceptionif there is no value present
 - seealso: OptionalBoolean#isPresent()
 - seealso: #orElseThrow()
 */
- (bool)getAsBoolean;

- (NSUInteger)hash;

/*!
 @brief Invokes consumer function with value if present, otherwise does nothing.
 @param consumer the consumer function to be executed if a value is present
 @throw NullPointerExceptionif value is present and <code>consumer</code> is null
 */
- (void)ifPresentWithCASBooleanConsumer:(id<CASBooleanConsumer>)consumer;

/*!
 @brief If a value is present, performs the given action with the value,
  otherwise performs the empty-based action.
 @param consumer the consumer function to be executed, if a value is present
 @param emptyAction the empty-based action to be performed, if no value is present
 @throw NullPointerExceptionif a value is present and the given consumer function is null,
          or no value is present and the given empty-based action is null.
 */
- (void)ifPresentOrElseWithCASBooleanConsumer:(id<CASBooleanConsumer>)consumer
                         withJavaLangRunnable:(id<JavaLangRunnable>)emptyAction;

/*!
 @brief Checks the value is not present.
 @return <code>true</code> if a value is not present, <code>false</code> otherwise
 @since 1.2.1
 */
- (bool)isEmpty;

/*!
 @brief Checks value present.
 @return <code>true</code> if a value present, <code>false</code> otherwise
 */
- (bool)isPresent;

/*!
 @brief Invokes the given mapping function on inner value if present.
 @param mapper mapping function
 @return an <code>OptionalBoolean</code> with transformed value if present,
          otherwise an empty <code>OptionalBoolean</code>
 @throw NullPointerExceptionif value is present and
          <code>mapper</code> is <code>null</code>
 */
- (CASOptionalBoolean *)mapWithCASBooleanPredicate:(id<CASBooleanPredicate>)mapper;

/*!
 @brief Invokes the given mapping function on inner value if present.
 @param mapper mapping function
 @return an <code>Optional</code> with transformed value if present,
          otherwise an empty <code>Optional</code>
 @throw NullPointerExceptionif value is present and
          <code>mapper</code> is <code>null</code>
 */
- (CASOptional *)mapToObjWithCASBooleanFunction:(id<CASBooleanFunction>)mapper;

/*!
 @brief Returns an <code>OptionalBoolean</code> with the specified value present.
 @param value the value to be present
 @return an <code>OptionalBoolean</code> with the value present
 */
+ (CASOptionalBoolean *)ofWithBoolean:(bool)value;

/*!
 @brief Returns an <code>OptionalBoolean</code> with the specified value, or empty <code>OptionalBoolean</code> if value is null.
 @param value the value which can be null
 @return an <code>OptionalBoolean</code>
 @since 1.2.1
 */
+ (CASOptionalBoolean *)ofNullableWithJavaLangBoolean:(JavaLangBoolean *)value;

/*!
 @brief Returns current <code>OptionalBoolean</code> if value is present, otherwise
  returns an <code>OptionalBoolean</code> produced by supplier function.
 @param supplier supplier function that produces an <code>OptionalBoolean</code>  to be returned
 @return this <code>OptionalBoolean</code> if value is present, otherwise
          an <code>OptionalBoolean</code> produced by supplier function
 @throw NullPointerExceptionif value is not present and
          <code>supplier</code> or value produced by it is <code>null</code>
 */
- (CASOptionalBoolean *)or__WithCASSupplier:(id<CASSupplier>)supplier;

/*!
 @brief Returns inner value if present, otherwise returns <code>other</code>.
 @param other the value to be returned if there is no value present
 @return the value, if present, otherwise <code>other</code>
 */
- (bool)orElseWithBoolean:(bool)other;

/*!
 @brief Returns the value if present, otherwise returns value produced by supplier function.
 @param other supplier function that produces value if inner value is not present
 @return the value if present otherwise the result of <code>other.getAsBoolean()</code>
 @throw NullPointerExceptionif value is not present and <code>other</code> is null
 */
- (bool)orElseGetWithCASBooleanSupplier:(id<CASBooleanSupplier>)other;

/*!
 @brief Returns inner value if present, otherwise throws <code>NoSuchElementException</code>.
 @return inner value if present
 @throw NoSuchElementExceptionif inner value is not present
 @since 1.2.0
 */
- (bool)orElseThrow;

/*!
 @brief Returns the value if present, otherwise throws an exception provided by supplier function.
 @param exceptionSupplier supplier function that produces an exception to be thrown
 @return inner value if present
 @throw Xif inner value is not present
 */
- (bool)orElseThrowWithCASSupplier:(id<CASSupplier>)exceptionSupplier;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(CASOptionalBoolean)

FOUNDATION_EXPORT CASOptionalBoolean *CASOptionalBoolean_empty(void);

FOUNDATION_EXPORT CASOptionalBoolean *CASOptionalBoolean_ofWithBoolean_(bool value);

FOUNDATION_EXPORT CASOptionalBoolean *CASOptionalBoolean_ofNullableWithJavaLangBoolean_(JavaLangBoolean *value);

J2OBJC_TYPE_LITERAL_HEADER(CASOptionalBoolean)

@compatibility_alias ComAnnimonStreamOptionalBoolean CASOptionalBoolean;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOptionalBoolean")
