//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/BinaryOperator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionBinaryOperator")
#ifdef RESTRICT_ComAnnimonStreamFunctionBinaryOperator
#define INCLUDE_ALL_ComAnnimonStreamFunctionBinaryOperator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionBinaryOperator 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionBinaryOperator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASBinaryOperator_) && (INCLUDE_ALL_ComAnnimonStreamFunctionBinaryOperator || defined(INCLUDE_CASBinaryOperator))
#define CASBinaryOperator_

#define RESTRICT_ComAnnimonStreamFunctionBiFunction 1
#define INCLUDE_CASBiFunction 1
#include "com/annimon/stream/function/BiFunction.h"

/*!
 @brief Represents an operation on two operands that produces a result of the
  same type as its operand.
 */
@protocol CASBinaryOperator < CASBiFunction, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(CASBinaryOperator)

J2OBJC_TYPE_LITERAL_HEADER(CASBinaryOperator)

#define ComAnnimonStreamFunctionBinaryOperator CASBinaryOperator


#endif

#if !defined (CASBinaryOperator_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionBinaryOperator || defined(INCLUDE_CASBinaryOperator_Util))
#define CASBinaryOperator_Util_

@protocol CASBinaryOperator;
@protocol JavaUtilComparator;

@interface CASBinaryOperator_Util : NSObject

#pragma mark Public

/*!
 @brief Returns a <code>BinaryOperator</code> which returns greater of two elements
  according to the specified <code>Comparator</code>.
 @param comparator a <code>Comparator</code>  for comparing the two values
 @return a <code>BinaryOperator</code> which returns the greater of its operands,
          according to the supplied <code>Comparator</code>
 @throw NullPointerExceptionif the argument is null
 */
+ (id<CASBinaryOperator>)maxByWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

/*!
 @brief Returns a <code>BinaryOperator</code> which returns lesser of two elements
  according to the specified <code>Comparator</code>.
 @param comparator a <code>Comparator</code>  for comparing the two values
 @return a <code>BinaryOperator</code> which returns the lesser of its operands,
          according to the supplied <code>Comparator</code>
 @throw NullPointerExceptionif the argument is null
 */
+ (id<CASBinaryOperator>)minByWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

@end

J2OBJC_EMPTY_STATIC_INIT(CASBinaryOperator_Util)

FOUNDATION_EXPORT id<CASBinaryOperator> CASBinaryOperator_Util_minByWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT id<CASBinaryOperator> CASBinaryOperator_Util_maxByWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

J2OBJC_TYPE_LITERAL_HEADER(CASBinaryOperator_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionBinaryOperator")
