//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/DoubleToIntFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToIntFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionDoubleToIntFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToIntFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToIntFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionDoubleToIntFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleToIntFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToIntFunction || defined(INCLUDE_CASDoubleToIntFunction))
#define CASDoubleToIntFunction_

@class JavaLangDouble;
@class JavaLangInteger;

/*!
 @brief Represents a function which produces an <code>int</code>-valued result from input argument.
 @since 1.1.4
 - seealso: Function
 */
@protocol CASDoubleToIntFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value an argument
 @return the function result
 */
- (int32_t)applyAsIntWithDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleToIntFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleToIntFunction)

#define ComAnnimonStreamFunctionDoubleToIntFunction CASDoubleToIntFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToIntFunction")
