//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/DoubleFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionDoubleFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionDoubleFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionDoubleFunction || defined(INCLUDE_CASDoubleFunction))
#define CASDoubleFunction_

@class JavaLangDouble;

/*!
 @brief Represents a function which produces result from <code>double</code>-valued input argument.
 @since 1.1.4
 - seealso: Function
 */
@protocol CASDoubleFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value an argument
 @return the function result
 */
- (id)applyWithDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleFunction)

#define ComAnnimonStreamFunctionDoubleFunction CASDoubleFunction


#endif

#if !defined (CASDoubleFunction_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionDoubleFunction || defined(INCLUDE_CASDoubleFunction_Util))
#define CASDoubleFunction_Util_

@protocol CASDoubleFunction;
@protocol CASThrowableDoubleFunction;

@interface CASDoubleFunction_Util : NSObject

#pragma mark Public

/*!
 @brief Creates a safe <code>DoubleFunction</code>,
 @param throwableFunction the function that may throw an exception
 @return the function result or <code>null</code> if exception was thrown
 @throw NullPointerExceptionif <code>throwableFunction</code> is null
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableDoubleFunction, java.lang.Object)
 */
+ (id<CASDoubleFunction>)safeWithCASThrowableDoubleFunction:(id<CASThrowableDoubleFunction>)throwableFunction;

/*!
 @brief Creates a safe <code>DoubleFunction</code>,
 @param throwableFunction the function that may throw an exception
 @param resultIfFailed the result which returned if exception was thrown
 @return the function result or <code>resultIfFailed</code>
 @throw NullPointerExceptionif <code>throwableFunction</code> is null
 @since 1.1.7
 */
+ (id<CASDoubleFunction>)safeWithCASThrowableDoubleFunction:(id<CASThrowableDoubleFunction>)throwableFunction
                                                     withId:(id)resultIfFailed;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleFunction_Util)

FOUNDATION_EXPORT id<CASDoubleFunction> CASDoubleFunction_Util_safeWithCASThrowableDoubleFunction_(id<CASThrowableDoubleFunction> throwableFunction);

FOUNDATION_EXPORT id<CASDoubleFunction> CASDoubleFunction_Util_safeWithCASThrowableDoubleFunction_withId_(id<CASThrowableDoubleFunction> throwableFunction, id resultIfFailed);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleFunction_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleFunction")
