//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/DoubleBinaryOperator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleBinaryOperator")
#ifdef RESTRICT_ComAnnimonStreamFunctionDoubleBinaryOperator
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleBinaryOperator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleBinaryOperator 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionDoubleBinaryOperator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleBinaryOperator_) && (INCLUDE_ALL_ComAnnimonStreamFunctionDoubleBinaryOperator || defined(INCLUDE_CASDoubleBinaryOperator))
#define CASDoubleBinaryOperator_

@class JavaLangDouble;

/*!
 @brief Represents an operation on two <code>double</code>-valued operands
  that produces a <code>double</code>-valued result.
 @since 1.1.4
 - seealso: BinaryOperator
 */
@protocol CASDoubleBinaryOperator < JavaObject >

/*!
 @brief Applies this operator to the given operands.
 @param left the first operand
 @param right the second operand
 @return the operator result
 */
- (double)applyAsDoubleWithDouble:(double)left
                       withDouble:(double)right;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleBinaryOperator)

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleBinaryOperator)

#define ComAnnimonStreamFunctionDoubleBinaryOperator CASDoubleBinaryOperator


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleBinaryOperator")
