//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/DoubleToLongFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToLongFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionDoubleToLongFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToLongFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToLongFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionDoubleToLongFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleToLongFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToLongFunction || defined(INCLUDE_CASDoubleToLongFunction))
#define CASDoubleToLongFunction_

@class JavaLangDouble;
@class JavaLangLong;

/*!
 @brief Represents a function which produces an <code>long</code>-valued result from input argument.
 @since 1.1.4
 - seealso: Function
 */
@protocol CASDoubleToLongFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value an argument
 @return the function result
 */
- (int64_t)applyAsLongWithDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleToLongFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleToLongFunction)

#define ComAnnimonStreamFunctionDoubleToLongFunction CASDoubleToLongFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleToLongFunction")
