//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedDoubleUnaryOperator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleUnaryOperator")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedDoubleUnaryOperator
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleUnaryOperator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleUnaryOperator 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedDoubleUnaryOperator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedDoubleUnaryOperator_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleUnaryOperator || defined(INCLUDE_CASIndexedDoubleUnaryOperator))
#define CASIndexedDoubleUnaryOperator_

@class JavaLangDouble;
@class JavaLangInteger;

/*!
 @brief Represents an operation on index and input <code>double</code>-valued operand
  that produces a <code>double</code>-valued result.
 @since 1.2.1
 - seealso: DoubleUnaryOperator
 */
@protocol CASIndexedDoubleUnaryOperator < JavaObject >

/*!
 @brief Applies this operator to the given operand.
 @param index the index
 @param operand the operand
 @return the operator result
 */
- (double)applyAsDoubleWithInt:(int32_t)index
                    withDouble:(double)operand;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedDoubleUnaryOperator)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedDoubleUnaryOperator)

#define ComAnnimonStreamFunctionIndexedDoubleUnaryOperator CASIndexedDoubleUnaryOperator


#endif

#if !defined (CASIndexedDoubleUnaryOperator_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleUnaryOperator || defined(INCLUDE_CASIndexedDoubleUnaryOperator_Util))
#define CASIndexedDoubleUnaryOperator_Util_

@protocol CASDoubleUnaryOperator;
@protocol CASIndexedDoubleUnaryOperator;

@interface CASIndexedDoubleUnaryOperator_Util : NSObject

#pragma mark Public

/*!
 @brief Wraps <code>DoubleUnaryOperator</code> and returns <code>IndexedDoubleUnaryOperator</code>.
 @param function the function to wrap
 @return a wrapped <code>IndexedDoubleUnaryOperator</code>
 @throw NullPointerExceptionif <code>function</code> is null
 */
+ (id<CASIndexedDoubleUnaryOperator>)wrapWithCASDoubleUnaryOperator:(id<CASDoubleUnaryOperator>)function;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedDoubleUnaryOperator_Util)

FOUNDATION_EXPORT id<CASIndexedDoubleUnaryOperator> CASIndexedDoubleUnaryOperator_Util_wrapWithCASDoubleUnaryOperator_(id<CASDoubleUnaryOperator> function);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedDoubleUnaryOperator_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleUnaryOperator")
