//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedDoubleConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedDoubleConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedDoubleConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedDoubleConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleConsumer || defined(INCLUDE_CASIndexedDoubleConsumer))
#define CASIndexedDoubleConsumer_

@class JavaLangDouble;
@class JavaLangInteger;

/*!
 @brief Represents an operation on index and input argument.
 @since 1.2.1
 */
@protocol CASIndexedDoubleConsumer < JavaObject >

/*!
 @brief Performs operation on argument.
 @param index the index
 @param value the input argument
 */
- (void)acceptWithInt:(int32_t)index
           withDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedDoubleConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedDoubleConsumer)

#define ComAnnimonStreamFunctionIndexedDoubleConsumer CASIndexedDoubleConsumer


#endif

#if !defined (CASIndexedDoubleConsumer_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleConsumer || defined(INCLUDE_CASIndexedDoubleConsumer_Util))
#define CASIndexedDoubleConsumer_Util_

@protocol CASDoubleConsumer;
@protocol CASIndexedDoubleConsumer;
@protocol CASIntConsumer;

@interface CASIndexedDoubleConsumer_Util : NSObject

#pragma mark Public

/*!
 @brief Returns an <code>IndexedDoubleConsumer</code> that accepts <code>IntConsumer</code>
  for index and <code>DoubleConsumer</code> for value.
 @code
<code>
   if (c1 != null)
       c1.accept(index);
   if (c2 != null)
       c2.accept(object); 
  </code>
@endcode
 @param c1 the <code>IntConsumer</code>  for index, can be null
 @param c2 the <code>DoubleConsumer</code>  for value, can be null
 @return an <code>IndexedDoubleConsumer</code>
 */
+ (id<CASIndexedDoubleConsumer>)acceptWithCASIntConsumer:(id<CASIntConsumer>)c1
                                   withCASDoubleConsumer:(id<CASDoubleConsumer>)c2;

/*!
 @brief Composes <code>IndexedDoubleConsumer</code> calls.
 <p><code>c1.accept(index, value); c2.accept(index, value);</code>
 @param c1 the first <code>IndexedDoubleConsumer</code>
 @param c2 the second <code>IndexedDoubleConsumer</code>
 @return a composed <code>IndexedDoubleConsumer</code>
 @throw NullPointerExceptionif <code>c1</code> or <code>c2</code> is null
 */
+ (id<CASIndexedDoubleConsumer>)andThenWithCASIndexedDoubleConsumer:(id<CASIndexedDoubleConsumer>)c1
                                       withCASIndexedDoubleConsumer:(id<CASIndexedDoubleConsumer>)c2;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedDoubleConsumer_Util)

FOUNDATION_EXPORT id<CASIndexedDoubleConsumer> CASIndexedDoubleConsumer_Util_andThenWithCASIndexedDoubleConsumer_withCASIndexedDoubleConsumer_(id<CASIndexedDoubleConsumer> c1, id<CASIndexedDoubleConsumer> c2);

FOUNDATION_EXPORT id<CASIndexedDoubleConsumer> CASIndexedDoubleConsumer_Util_acceptWithCASIntConsumer_withCASDoubleConsumer_(id<CASIntConsumer> c1, id<CASDoubleConsumer> c2);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedDoubleConsumer_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleConsumer")
