//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedDoubleFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedDoubleFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedDoubleFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedDoubleFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleFunction || defined(INCLUDE_CASIndexedDoubleFunction))
#define CASIndexedDoubleFunction_

@class JavaLangDouble;
@class JavaLangInteger;

/*!
 @brief Represents a function which produces result from index and input argument.
 @since 1.2.1
 */
@protocol CASIndexedDoubleFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param index the index
 @param value an argument
 @return the function result
 */
- (id)applyWithInt:(int32_t)index
        withDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedDoubleFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedDoubleFunction)

#define ComAnnimonStreamFunctionIndexedDoubleFunction CASIndexedDoubleFunction


#endif

#if !defined (CASIndexedDoubleFunction_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleFunction || defined(INCLUDE_CASIndexedDoubleFunction_Util))
#define CASIndexedDoubleFunction_Util_

@protocol CASDoubleFunction;
@protocol CASIndexedDoubleFunction;

@interface CASIndexedDoubleFunction_Util : NSObject

#pragma mark Public

/*!
 @brief Wraps <code>DoubleFunction</code> and returns <code>IndexedDoubleFunction</code>.
 @param function the function to wrap
 @return a wrapped <code>IndexedDoubleFunction</code>
 @throw NullPointerExceptionif <code>function</code> is null
 */
+ (id<CASIndexedDoubleFunction>)wrapWithCASDoubleFunction:(id<CASDoubleFunction>)function;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedDoubleFunction_Util)

FOUNDATION_EXPORT id<CASIndexedDoubleFunction> CASIndexedDoubleFunction_Util_wrapWithCASDoubleFunction_(id<CASDoubleFunction> function);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedDoubleFunction_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoubleFunction")
