//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedIntFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedIntFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedIntFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedIntFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntFunction || defined(INCLUDE_CASIndexedIntFunction))
#define CASIndexedIntFunction_

@class JavaLangInteger;

/*!
 @brief Represents a function which produces result from index and input argument.
 @since 1.2.1
 */
@protocol CASIndexedIntFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param index the index
 @param value an argument
 @return the function result
 */
- (id)applyWithInt:(int32_t)index
           withInt:(int32_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedIntFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedIntFunction)

#define ComAnnimonStreamFunctionIndexedIntFunction CASIndexedIntFunction


#endif

#if !defined (CASIndexedIntFunction_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntFunction || defined(INCLUDE_CASIndexedIntFunction_Util))
#define CASIndexedIntFunction_Util_

@protocol CASIndexedIntFunction;
@protocol CASIntFunction;

@interface CASIndexedIntFunction_Util : NSObject

#pragma mark Public

/*!
 @brief Wraps <code>IntFunction</code> and returns <code>IndexedIntFunction</code>.
 @param function the function to wrap
 @return a wrapped <code>IndexedIntFunction</code>
 @throw NullPointerExceptionif <code>function</code> is null
 */
+ (id<CASIndexedIntFunction>)wrapWithCASIntFunction:(id<CASIntFunction>)function;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedIntFunction_Util)

FOUNDATION_EXPORT id<CASIndexedIntFunction> CASIndexedIntFunction_Util_wrapWithCASIntFunction_(id<CASIntFunction> function);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedIntFunction_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntFunction")
