//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedLongUnaryOperator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongUnaryOperator")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedLongUnaryOperator
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongUnaryOperator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongUnaryOperator 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedLongUnaryOperator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedLongUnaryOperator_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongUnaryOperator || defined(INCLUDE_CASIndexedLongUnaryOperator))
#define CASIndexedLongUnaryOperator_

@class JavaLangInteger;
@class JavaLangLong;

/*!
 @brief Represents an operation on index and input <code>long</code>-valued operand
  that produces a <code>long</code>-valued result.
 @since 1.2.1
 - seealso: LongUnaryOperator
 */
@protocol CASIndexedLongUnaryOperator < JavaObject >

/*!
 @brief Applies this operator to the given operand.
 @param index the index
 @param operand the operand
 @return the operator result
 */
- (int64_t)applyAsLongWithInt:(int32_t)index
                     withLong:(int64_t)operand;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedLongUnaryOperator)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedLongUnaryOperator)

#define ComAnnimonStreamFunctionIndexedLongUnaryOperator CASIndexedLongUnaryOperator


#endif

#if !defined (CASIndexedLongUnaryOperator_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongUnaryOperator || defined(INCLUDE_CASIndexedLongUnaryOperator_Util))
#define CASIndexedLongUnaryOperator_Util_

@protocol CASIndexedLongUnaryOperator;
@protocol CASLongUnaryOperator;

@interface CASIndexedLongUnaryOperator_Util : NSObject

#pragma mark Public

/*!
 @brief Wraps <code>LongUnaryOperator</code> and returns <code>IndexedLongUnaryOperator</code>.
 @param function the function to wrap
 @return a wrapped <code>IndexedLongUnaryOperator</code>
 @throw NullPointerExceptionif <code>function</code> is null
 */
+ (id<CASIndexedLongUnaryOperator>)wrapWithCASLongUnaryOperator:(id<CASLongUnaryOperator>)function;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedLongUnaryOperator_Util)

FOUNDATION_EXPORT id<CASIndexedLongUnaryOperator> CASIndexedLongUnaryOperator_Util_wrapWithCASLongUnaryOperator_(id<CASLongUnaryOperator> function);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedLongUnaryOperator_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongUnaryOperator")
