//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedBiFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedBiFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedBiFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedBiFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedBiFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedBiFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedBiFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedBiFunction || defined(INCLUDE_CASIndexedBiFunction))
#define CASIndexedBiFunction_

@class JavaLangInteger;

/*!
 @brief Represents a function which produces result from index and two input arguments.
 @since 1.1.6
 */
@protocol CASIndexedBiFunction < JavaObject >

/*!
 @brief Applies this function to the given arguments.
 @param index the index
 @param value1 the first argument
 @param value2 the second argument
 @return the function result
 */
- (id)applyWithInt:(int32_t)index
            withId:(id)value1
            withId:(id)value2;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedBiFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedBiFunction)

#define ComAnnimonStreamFunctionIndexedBiFunction CASIndexedBiFunction


#endif

#if !defined (CASIndexedBiFunction_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedBiFunction || defined(INCLUDE_CASIndexedBiFunction_Util))
#define CASIndexedBiFunction_Util_

@protocol CASBiFunction;
@protocol CASIndexedBiFunction;

@interface CASIndexedBiFunction_Util : NSObject

#pragma mark Public

/*!
 @brief Wraps <code>BiFunction</code> and returns <code>IndexedBiFunction</code>.
 @param function the <code>BiFunction</code>  to wrap
 @return a wrapped <code>IndexedBiFunction</code>
 @throw NullPointerExceptionif <code>function</code> is null
 */
+ (id<CASIndexedBiFunction>)wrapWithCASBiFunction:(id<CASBiFunction>)function;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedBiFunction_Util)

FOUNDATION_EXPORT id<CASIndexedBiFunction> CASIndexedBiFunction_Util_wrapWithCASBiFunction_(id<CASBiFunction> function);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedBiFunction_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedBiFunction")
