//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedDoublePredicate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoublePredicate")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedDoublePredicate
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoublePredicate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoublePredicate 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedDoublePredicate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedDoublePredicate_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoublePredicate || defined(INCLUDE_CASIndexedDoublePredicate))
#define CASIndexedDoublePredicate_

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangInteger;

/*!
 @brief Represents a predicate (function with boolean type result) with additional index argument.
 @since 1.2.1
 */
@protocol CASIndexedDoublePredicate < JavaObject >

/*!
 @brief Tests the value for satisfying predicate.
 @param index the index
 @param value the value to be tested
 @return <code>true</code> if the value matches the predicate, otherwise <code>false</code>
 */
- (bool)testWithInt:(int32_t)index
         withDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedDoublePredicate)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedDoublePredicate)

#define ComAnnimonStreamFunctionIndexedDoublePredicate CASIndexedDoublePredicate


#endif

#if !defined (CASIndexedDoublePredicate_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoublePredicate || defined(INCLUDE_CASIndexedDoublePredicate_Util))
#define CASIndexedDoublePredicate_Util_

@protocol CASDoublePredicate;
@protocol CASIndexedDoublePredicate;

@interface CASIndexedDoublePredicate_Util : NSObject

#pragma mark Public

/*!
 @brief Wraps <code>DoublePredicate</code> and returns <code>IndexedLongPredicate</code>.
 @param predicate the predicate to wrap
 @return a wrapped <code>IndexedDoublePredicate</code>
 @throw NullPointerExceptionif <code>predicate</code> is null
 */
+ (id<CASIndexedDoublePredicate>)wrapWithCASDoublePredicate:(id<CASDoublePredicate>)predicate;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedDoublePredicate_Util)

FOUNDATION_EXPORT id<CASIndexedDoublePredicate> CASIndexedDoublePredicate_Util_wrapWithCASDoublePredicate_(id<CASDoublePredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedDoublePredicate_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedDoublePredicate")
