//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedLongFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedLongFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedLongFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedLongFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongFunction || defined(INCLUDE_CASIndexedLongFunction))
#define CASIndexedLongFunction_

@class JavaLangInteger;
@class JavaLangLong;

/*!
 @brief Represents a function which produces result from index and input argument.
 @since 1.2.1
 */
@protocol CASIndexedLongFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param index the index
 @param value an argument
 @return the function result
 */
- (id)applyWithInt:(int32_t)index
          withLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedLongFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedLongFunction)

#define ComAnnimonStreamFunctionIndexedLongFunction CASIndexedLongFunction


#endif

#if !defined (CASIndexedLongFunction_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongFunction || defined(INCLUDE_CASIndexedLongFunction_Util))
#define CASIndexedLongFunction_Util_

@protocol CASIndexedLongFunction;
@protocol CASLongFunction;

@interface CASIndexedLongFunction_Util : NSObject

#pragma mark Public

/*!
 @brief Wraps <code>LongFunction</code> and returns <code>IndexedLongFunction</code>.
 @param function the function to wrap
 @return a wrapped <code>IndexedLongFunction</code>
 @throw NullPointerExceptionif <code>function</code> is null
 */
+ (id<CASIndexedLongFunction>)wrapWithCASLongFunction:(id<CASLongFunction>)function;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedLongFunction_Util)

FOUNDATION_EXPORT id<CASIndexedLongFunction> CASIndexedLongFunction_Util_wrapWithCASLongFunction_(id<CASLongFunction> function);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedLongFunction_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongFunction")
