//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IntConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionIntConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIntConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIntConsumer || defined(INCLUDE_CASIntConsumer))
#define CASIntConsumer_

@class JavaLangInteger;

/*!
 @brief Represents an operation that accepts a single <code>int</code>-valued argument and
  returns no result.This is the primitive type specialization of 
 <code>com.annimon.stream.function.Consumer</code> for <code>int</code>.
 Unlike most other
  functional interfaces, <code>IntConsumer</code> is expected to operate via side-effects. 
 <p>This is a functional interface whose functional method is <code>accept(int)</code>
 - seealso: com.annimon.stream.function.Consumer
 */
@protocol CASIntConsumer < JavaObject >

/*!
 @brief Performs this operation on the given argument.
 @param value the input argument
 */
- (void)acceptWithInt:(int32_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASIntConsumer)

#define ComAnnimonStreamFunctionIntConsumer CASIntConsumer


#endif

#if !defined (CASIntConsumer_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIntConsumer || defined(INCLUDE_CASIntConsumer_Util))
#define CASIntConsumer_Util_

@protocol CASIntConsumer;
@protocol CASThrowableIntConsumer;

@interface CASIntConsumer_Util : NSObject

#pragma mark Public

/*!
 @brief Composes <code>IntConsumer</code> calls.
 <p><code>c1.accept(value); c2.accept(value);</code>
 @param c1 the first <code>IntConsumer</code>
 @param c2 the second <code>IntConsumer</code>
 @return a composed <code>IntConsumer</code>
 @throw NullPointerExceptionif <code>c1</code> or <code>c2</code> is null
 */
+ (id<CASIntConsumer>)andThenWithCASIntConsumer:(id<CASIntConsumer>)c1
                             withCASIntConsumer:(id<CASIntConsumer>)c2;

/*!
 @brief Creates a safe <code>IntConsumer</code>.
 @param throwableConsumer the consumer that may throw an exception
 @return an <code>IntConsumer</code>
 @throw NullPointerExceptionif <code>throwableConsumer</code> is null
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableIntConsumer, com.annimon.stream.function.IntConsumer)
 */
+ (id<CASIntConsumer>)safeWithCASThrowableIntConsumer:(id<CASThrowableIntConsumer>)throwableConsumer;

/*!
 @brief Creates a safe <code>IntConsumer</code>.
 @param throwableConsumer the consumer that may throw an exception
 @param onFailedConsumer the consumer which applies if exception was thrown
 @return an <code>IntConsumer</code>
 @throw NullPointerExceptionif <code>throwableConsumer</code> is null
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableIntConsumer)
 */
+ (id<CASIntConsumer>)safeWithCASThrowableIntConsumer:(id<CASThrowableIntConsumer>)throwableConsumer
                                   withCASIntConsumer:(id<CASIntConsumer>)onFailedConsumer;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntConsumer_Util)

FOUNDATION_EXPORT id<CASIntConsumer> CASIntConsumer_Util_andThenWithCASIntConsumer_withCASIntConsumer_(id<CASIntConsumer> c1, id<CASIntConsumer> c2);

FOUNDATION_EXPORT id<CASIntConsumer> CASIntConsumer_Util_safeWithCASThrowableIntConsumer_(id<CASThrowableIntConsumer> throwableConsumer);

FOUNDATION_EXPORT id<CASIntConsumer> CASIntConsumer_Util_safeWithCASThrowableIntConsumer_withCASIntConsumer_(id<CASThrowableIntConsumer> throwableConsumer, id<CASIntConsumer> onFailedConsumer);

J2OBJC_TYPE_LITERAL_HEADER(CASIntConsumer_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntConsumer")
