//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IntPredicate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntPredicate")
#ifdef RESTRICT_ComAnnimonStreamFunctionIntPredicate
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntPredicate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntPredicate 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIntPredicate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntPredicate_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIntPredicate || defined(INCLUDE_CASIntPredicate))
#define CASIntPredicate_

@class JavaLangBoolean;
@class JavaLangInteger;

/*!
 @brief Represents a predicate (function with boolean type result).
 */
@protocol CASIntPredicate < JavaObject >

/*!
 @brief Tests the value for satisfying predicate.
 @param value the value to be tested
 @return <code>true</code> if the value matches the predicate, otherwise <code>false</code>
 */
- (bool)testWithInt:(int32_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntPredicate)

J2OBJC_TYPE_LITERAL_HEADER(CASIntPredicate)

#define ComAnnimonStreamFunctionIntPredicate CASIntPredicate


#endif

#if !defined (CASIntPredicate_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIntPredicate || defined(INCLUDE_CASIntPredicate_Util))
#define CASIntPredicate_Util_

@class JavaLangBoolean;
@protocol CASIntPredicate;
@protocol CASThrowableIntPredicate;

@interface CASIntPredicate_Util : NSObject

#pragma mark Public

/*!
 @brief Applies logical AND to predicates.
 @param p1 the first predicate
 @param p2 the second predicate
 @return a composed <code>IntPredicate</code>
 @throw NullPointerExceptionif <code>p1</code> or <code>p2</code> is null
 */
+ (id<CASIntPredicate>)and__WithCASIntPredicate:(id<CASIntPredicate>)p1
                            withCASIntPredicate:(id<CASIntPredicate>)p2;

/*!
 @brief Applies logical negation to predicate.
 @param p1 the predicate to be negated
 @return a composed <code>IntPredicate</code>
 @throw NullPointerExceptionif <code>p1</code> is null
 */
+ (id<CASIntPredicate>)negateWithCASIntPredicate:(id<CASIntPredicate>)p1;

/*!
 @brief Applies logical OR to predicates.
 @param p1 the first predicate
 @param p2 the second predicate
 @return a composed <code>IntPredicate</code>
 @throw NullPointerExceptionif <code>p1</code> or <code>p2</code> is null
 */
+ (id<CASIntPredicate>)or__WithCASIntPredicate:(id<CASIntPredicate>)p1
                           withCASIntPredicate:(id<CASIntPredicate>)p2;

/*!
 @brief Creates a safe <code>IntPredicate</code>.
 @param throwablePredicate the predicate that may throw an exception
 @return an <code>IntPredicate</code> or <code>false</code> if exception was thrown
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableIntPredicate, boolean)
 */
+ (id<CASIntPredicate>)safeWithCASThrowableIntPredicate:(id<CASThrowableIntPredicate>)throwablePredicate;

/*!
 @brief Creates a safe <code>IntPredicate</code>.
 @param throwablePredicate the predicate that may throw an exception
 @param resultIfFailed the result which returned if exception was thrown
 @return an <code>IntPredicate</code> or <code>resultIfFailed</code>
 @throw NullPointerExceptionif <code>throwablePredicate</code> is null
 @since 1.1.7
 */
+ (id<CASIntPredicate>)safeWithCASThrowableIntPredicate:(id<CASThrowableIntPredicate>)throwablePredicate
                                            withBoolean:(bool)resultIfFailed;

/*!
 @brief Applies logical XOR to predicates.
 @param p1 the first predicate
 @param p2 the second predicate
 @return a composed <code>IntPredicate</code>
 @throw NullPointerExceptionif <code>p1</code> or <code>p2</code> is null
 */
+ (id<CASIntPredicate>)xor__WithCASIntPredicate:(id<CASIntPredicate>)p1
                            withCASIntPredicate:(id<CASIntPredicate>)p2;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntPredicate_Util)

FOUNDATION_EXPORT id<CASIntPredicate> CASIntPredicate_Util_and__WithCASIntPredicate_withCASIntPredicate_(id<CASIntPredicate> p1, id<CASIntPredicate> p2);

FOUNDATION_EXPORT id<CASIntPredicate> CASIntPredicate_Util_or__WithCASIntPredicate_withCASIntPredicate_(id<CASIntPredicate> p1, id<CASIntPredicate> p2);

FOUNDATION_EXPORT id<CASIntPredicate> CASIntPredicate_Util_xor__WithCASIntPredicate_withCASIntPredicate_(id<CASIntPredicate> p1, id<CASIntPredicate> p2);

FOUNDATION_EXPORT id<CASIntPredicate> CASIntPredicate_Util_negateWithCASIntPredicate_(id<CASIntPredicate> p1);

FOUNDATION_EXPORT id<CASIntPredicate> CASIntPredicate_Util_safeWithCASThrowableIntPredicate_(id<CASThrowableIntPredicate> throwablePredicate);

FOUNDATION_EXPORT id<CASIntPredicate> CASIntPredicate_Util_safeWithCASThrowableIntPredicate_withBoolean_(id<CASThrowableIntPredicate> throwablePredicate, bool resultIfFailed);

J2OBJC_TYPE_LITERAL_HEADER(CASIntPredicate_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntPredicate")
