//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IntSupplier.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntSupplier")
#ifdef RESTRICT_ComAnnimonStreamFunctionIntSupplier
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntSupplier 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntSupplier 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIntSupplier

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntSupplier_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIntSupplier || defined(INCLUDE_CASIntSupplier))
#define CASIntSupplier_

@class JavaLangInteger;

/*!
 @brief Represents a supplier of <code>int</code>-valued results.This is the 
 <code>int</code>-producing primitive specialization of <code>Supplier</code>.
 <p>There is no requirement that a distinct result be returned each
  time the supplier is invoked.
 */
@protocol CASIntSupplier < JavaObject >

/*!
 @brief Gets a result.
 @return a result
 */
- (int32_t)getAsInt;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntSupplier)

J2OBJC_TYPE_LITERAL_HEADER(CASIntSupplier)

#define ComAnnimonStreamFunctionIntSupplier CASIntSupplier


#endif

#if !defined (CASIntSupplier_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIntSupplier || defined(INCLUDE_CASIntSupplier_Util))
#define CASIntSupplier_Util_

@class JavaLangInteger;
@protocol CASIntSupplier;
@protocol CASThrowableIntSupplier;

@interface CASIntSupplier_Util : NSObject

#pragma mark Public

/*!
 @brief Creates a safe <code>IntSupplier</code>.
 @param throwableSupplier the supplier that may throw an exception
 @return an <code>IntSupplier</code>
 @throw NullPointerExceptionif <code>throwableSupplier</code> is null
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableIntSupplier, int)
 */
+ (id<CASIntSupplier>)safeWithCASThrowableIntSupplier:(id<CASThrowableIntSupplier>)throwableSupplier;

/*!
 @brief Creates a safe <code>IntSupplier</code>.
 @param throwableSupplier the supplier that may throw an exception
 @param resultIfFailed the result which returned if exception was thrown
 @return an <code>IntSupplier</code>
 @throw NullPointerExceptionif <code>throwableSupplier</code> is null
 @since 1.1.7
 */
+ (id<CASIntSupplier>)safeWithCASThrowableIntSupplier:(id<CASThrowableIntSupplier>)throwableSupplier
                                              withInt:(int32_t)resultIfFailed;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntSupplier_Util)

FOUNDATION_EXPORT id<CASIntSupplier> CASIntSupplier_Util_safeWithCASThrowableIntSupplier_(id<CASThrowableIntSupplier> throwableSupplier);

FOUNDATION_EXPORT id<CASIntSupplier> CASIntSupplier_Util_safeWithCASThrowableIntSupplier_withInt_(id<CASThrowableIntSupplier> throwableSupplier, int32_t resultIfFailed);

J2OBJC_TYPE_LITERAL_HEADER(CASIntSupplier_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntSupplier")
