//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IntToDoubleFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntToDoubleFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionIntToDoubleFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntToDoubleFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntToDoubleFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIntToDoubleFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntToDoubleFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIntToDoubleFunction || defined(INCLUDE_CASIntToDoubleFunction))
#define CASIntToDoubleFunction_

@class JavaLangDouble;
@class JavaLangInteger;

/*!
 @brief Represents a function which produces an <code>double</code>-valued result from input argument.
 @since 1.1.4
 - seealso: Function
 */
@protocol CASIntToDoubleFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value an argument
 @return the function result
 */
- (double)applyAsDoubleWithInt:(int32_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntToDoubleFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASIntToDoubleFunction)

#define ComAnnimonStreamFunctionIntToDoubleFunction CASIntToDoubleFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntToDoubleFunction")
