//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IntToLongFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntToLongFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionIntToLongFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntToLongFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIntToLongFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIntToLongFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntToLongFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIntToLongFunction || defined(INCLUDE_CASIntToLongFunction))
#define CASIntToLongFunction_

@class JavaLangInteger;
@class JavaLangLong;

/*!
 @brief Represents a function which produces an <code>long</code>-valued result from input argument.
 @since 1.1.4
 - seealso: Function
 */
@protocol CASIntToLongFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value an argument
 @return the function result
 */
- (int64_t)applyAsLongWithInt:(int32_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIntToLongFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASIntToLongFunction)

#define ComAnnimonStreamFunctionIntToLongFunction CASIntToLongFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIntToLongFunction")
