//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/LongSupplier.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongSupplier")
#ifdef RESTRICT_ComAnnimonStreamFunctionLongSupplier
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongSupplier 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongSupplier 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionLongSupplier

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongSupplier_) && (INCLUDE_ALL_ComAnnimonStreamFunctionLongSupplier || defined(INCLUDE_CASLongSupplier))
#define CASLongSupplier_

@class JavaLangLong;

/*!
 @brief Represents a supplier of <code>long</code>-valued results.
 @since 1.1.4
 - seealso: Supplier
 */
@protocol CASLongSupplier < JavaObject >

/*!
 @brief Gets a result.
 @return a result
 */
- (int64_t)getAsLong;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongSupplier)

J2OBJC_TYPE_LITERAL_HEADER(CASLongSupplier)

#define ComAnnimonStreamFunctionLongSupplier CASLongSupplier


#endif

#if !defined (CASLongSupplier_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionLongSupplier || defined(INCLUDE_CASLongSupplier_Util))
#define CASLongSupplier_Util_

@class JavaLangLong;
@protocol CASLongSupplier;
@protocol CASThrowableLongSupplier;

@interface CASLongSupplier_Util : NSObject

#pragma mark Public

/*!
 @brief Creates a safe <code>LongSupplier</code>.
 @param throwableSupplier the supplier that may throw an exception
 @return a <code>LongSupplier</code>
 @throw NullPointerExceptionif <code>throwableSupplier</code> is null
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableLongSupplier, long)
 */
+ (id<CASLongSupplier>)safeWithCASThrowableLongSupplier:(id<CASThrowableLongSupplier>)throwableSupplier;

/*!
 @brief Creates a safe <code>LongSupplier</code>.
 @param throwableSupplier the supplier that may throw an exception
 @param resultIfFailed the result which returned if exception was thrown
 @return a <code>LongSupplier</code>
 @throw NullPointerExceptionif <code>throwableSupplier</code> is null
 @since 1.1.7
 */
+ (id<CASLongSupplier>)safeWithCASThrowableLongSupplier:(id<CASThrowableLongSupplier>)throwableSupplier
                                               withLong:(int64_t)resultIfFailed;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongSupplier_Util)

FOUNDATION_EXPORT id<CASLongSupplier> CASLongSupplier_Util_safeWithCASThrowableLongSupplier_(id<CASThrowableLongSupplier> throwableSupplier);

FOUNDATION_EXPORT id<CASLongSupplier> CASLongSupplier_Util_safeWithCASThrowableLongSupplier_withLong_(id<CASThrowableLongSupplier> throwableSupplier, int64_t resultIfFailed);

J2OBJC_TYPE_LITERAL_HEADER(CASLongSupplier_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongSupplier")
