//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/LongFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionLongFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionLongFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionLongFunction || defined(INCLUDE_CASLongFunction))
#define CASLongFunction_

@class JavaLangLong;

/*!
 @brief Represents a function which produces result from <code>long</code>-valued input argument.
 @since 1.1.4
 - seealso: Function
 */
@protocol CASLongFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value an argument
 @return the function result
 */
- (id)applyWithLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASLongFunction)

#define ComAnnimonStreamFunctionLongFunction CASLongFunction


#endif

#if !defined (CASLongFunction_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionLongFunction || defined(INCLUDE_CASLongFunction_Util))
#define CASLongFunction_Util_

@protocol CASLongFunction;
@protocol CASThrowableLongFunction;

@interface CASLongFunction_Util : NSObject

#pragma mark Public

/*!
 @brief Creates a safe <code>LongFunction</code>,
 @param throwableFunction the function that may throw an exception
 @return the function result or <code>null</code> if exception was thrown
 @throw NullPointerExceptionif <code>throwableFunction</code> is null
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableLongFunction, java.lang.Object)
 */
+ (id<CASLongFunction>)safeWithCASThrowableLongFunction:(id<CASThrowableLongFunction>)throwableFunction;

/*!
 @brief Creates a safe <code>LongFunction</code>,
 @param throwableFunction the function that may throw an exception
 @param resultIfFailed the result which returned if exception was thrown
 @return the function result or <code>resultIfFailed</code>
 @throw NullPointerExceptionif <code>throwableFunction</code> is null
 @since 1.1.7
 */
+ (id<CASLongFunction>)safeWithCASThrowableLongFunction:(id<CASThrowableLongFunction>)throwableFunction
                                                 withId:(id)resultIfFailed;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongFunction_Util)

FOUNDATION_EXPORT id<CASLongFunction> CASLongFunction_Util_safeWithCASThrowableLongFunction_(id<CASThrowableLongFunction> throwableFunction);

FOUNDATION_EXPORT id<CASLongFunction> CASLongFunction_Util_safeWithCASThrowableLongFunction_withId_(id<CASThrowableLongFunction> throwableFunction, id resultIfFailed);

J2OBJC_TYPE_LITERAL_HEADER(CASLongFunction_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongFunction")
