//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ObjDoubleConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionObjDoubleConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionObjDoubleConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionObjDoubleConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionObjDoubleConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionObjDoubleConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjDoubleConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionObjDoubleConsumer || defined(INCLUDE_CASObjDoubleConsumer))
#define CASObjDoubleConsumer_

@class JavaLangDouble;

/*!
 @brief Represents an operation on two input arguments.
 @since 1.1.4
 - seealso: BiConsumer
 */
@protocol CASObjDoubleConsumer < JavaObject >

/*!
 @brief Performs operation on two arguments.
 @param t the first argument
 @param value the second argument
 */
- (void)acceptWithId:(id)t
          withDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjDoubleConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASObjDoubleConsumer)

#define ComAnnimonStreamFunctionObjDoubleConsumer CASObjDoubleConsumer


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionObjDoubleConsumer")
