//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ObjIntConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionObjIntConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionObjIntConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionObjIntConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionObjIntConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionObjIntConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjIntConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionObjIntConsumer || defined(INCLUDE_CASObjIntConsumer))
#define CASObjIntConsumer_

@class JavaLangInteger;

/*!
 @brief Represents an operation on two input arguments.
 - seealso: BiConsumer
 */
@protocol CASObjIntConsumer < JavaObject >

/*!
 @brief Performs operation on two arguments.
 @param t the first argument
 @param value the second argument
 */
- (void)acceptWithId:(id)t
             withInt:(int32_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjIntConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASObjIntConsumer)

#define ComAnnimonStreamFunctionObjIntConsumer CASObjIntConsumer


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionObjIntConsumer")
