//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/Supplier.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionSupplier")
#ifdef RESTRICT_ComAnnimonStreamFunctionSupplier
#define INCLUDE_ALL_ComAnnimonStreamFunctionSupplier 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionSupplier 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionSupplier

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASSupplier_) && (INCLUDE_ALL_ComAnnimonStreamFunctionSupplier || defined(INCLUDE_CASSupplier))
#define CASSupplier_

/*!
 @brief Represents a function which supply a result.
 */
@protocol CASSupplier < JavaObject >

/*!
 @brief Gets a result.
 @return a result
 */
- (id)get;

@end

J2OBJC_EMPTY_STATIC_INIT(CASSupplier)

J2OBJC_TYPE_LITERAL_HEADER(CASSupplier)

#define ComAnnimonStreamFunctionSupplier CASSupplier


#endif

#if !defined (CASSupplier_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionSupplier || defined(INCLUDE_CASSupplier_Util))
#define CASSupplier_Util_

@protocol CASSupplier;
@protocol CASThrowableSupplier;

@interface CASSupplier_Util : NSObject

#pragma mark Public

/*!
 @brief Creates a safe <code>Supplier</code>.
 @param throwableSupplier the supplier that may throw an exception
 @return a <code>Supplier</code>
 @throw NullPointerExceptionif <code>throwableSupplier</code> is null
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableSupplier, java.lang.Object)
 */
+ (id<CASSupplier>)safeWithCASThrowableSupplier:(id<CASThrowableSupplier>)throwableSupplier;

/*!
 @brief Creates a safe <code>Supplier</code>.
 @param throwableSupplier the supplier that may throw an exception
 @param resultIfFailed the result which returned if exception was thrown
 @return a <code>Supplier</code>
 @throw NullPointerExceptionif <code>throwableSupplier</code> is null
 @since 1.1.7
 */
+ (id<CASSupplier>)safeWithCASThrowableSupplier:(id<CASThrowableSupplier>)throwableSupplier
                                         withId:(id)resultIfFailed;

@end

J2OBJC_EMPTY_STATIC_INIT(CASSupplier_Util)

FOUNDATION_EXPORT id<CASSupplier> CASSupplier_Util_safeWithCASThrowableSupplier_(id<CASThrowableSupplier> throwableSupplier);

FOUNDATION_EXPORT id<CASSupplier> CASSupplier_Util_safeWithCASThrowableSupplier_withId_(id<CASThrowableSupplier> throwableSupplier, id resultIfFailed);

J2OBJC_TYPE_LITERAL_HEADER(CASSupplier_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionSupplier")
