//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableLongFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableLongFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableLongFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableLongFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongFunction || defined(INCLUDE_CASThrowableLongFunction))
#define CASThrowableLongFunction_

@class JavaLangLong;

/*!
 @brief Represents a function which produces result from <code>long</code>-valued input argument.
 @since 1.1.7
 - seealso: LongFunction
 */
@protocol CASThrowableLongFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value the function argument
 @return the function result
 @throw Ean exception
 */
- (id)applyWithLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableLongFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableLongFunction)

#define ComAnnimonStreamFunctionThrowableLongFunction CASThrowableLongFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongFunction")
