//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableIntPredicate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntPredicate")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableIntPredicate
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntPredicate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntPredicate 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableIntPredicate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableIntPredicate_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntPredicate || defined(INCLUDE_CASThrowableIntPredicate))
#define CASThrowableIntPredicate_

@class JavaLangBoolean;
@class JavaLangInteger;

/*!
 @brief Represents an <code>int</code>-valued predicate (function with boolean type result).
 @since 1.1.7
 - seealso: IntPredicate
 */
@protocol CASThrowableIntPredicate < JavaObject >

/*!
 @brief Tests the value for satisfying predicate.
 @param value the value to be tested
 @return <code>true</code> if the value matches the predicate, otherwise <code>false</code>
 @throw Ean exception
 */
- (bool)testWithInt:(int32_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableIntPredicate)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableIntPredicate)

#define ComAnnimonStreamFunctionThrowableIntPredicate CASThrowableIntPredicate


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntPredicate")
