//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableDoublePredicate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoublePredicate")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableDoublePredicate
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoublePredicate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoublePredicate 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableDoublePredicate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableDoublePredicate_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoublePredicate || defined(INCLUDE_CASThrowableDoublePredicate))
#define CASThrowableDoublePredicate_

@class JavaLangBoolean;
@class JavaLangDouble;

/*!
 @brief Represents a <code>double</code>-valued predicate (function with boolean type result).
 @since 1.1.7
 - seealso: DoublePredicate
 */
@protocol CASThrowableDoublePredicate < JavaObject >

/*!
 @brief Tests the value for satisfying predicate.
 @param value the value to be tested
 @return <code>true</code> if the value matches the predicate, otherwise <code>false</code>
 @throw Ean exception
 */
- (bool)testWithDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableDoublePredicate)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableDoublePredicate)

#define ComAnnimonStreamFunctionThrowableDoublePredicate CASThrowableDoublePredicate


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoublePredicate")
