//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableSupplier.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableSupplier")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableSupplier
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableSupplier 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableSupplier 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableSupplier

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableSupplier_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableSupplier || defined(INCLUDE_CASThrowableSupplier))
#define CASThrowableSupplier_

/*!
 @brief Represents a function for supplying result which can throw an exception.
 - seealso: Supplier
 */
@protocol CASThrowableSupplier < JavaObject >

/*!
 @brief Gets a result.
 @return a result
 @throw Ean exception
 */
- (id)get;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableSupplier)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableSupplier)

#define ComAnnimonStreamFunctionThrowableSupplier CASThrowableSupplier


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableSupplier")
