//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableFunction || defined(INCLUDE_CASThrowableFunction))
#define CASThrowableFunction_

/*!
 @brief Represents a function which produces result from input arguments and can throw an exception.
 - seealso: Function
 */
@protocol CASThrowableFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param i an argument
 @return the function result
 @throw Ean exception
 */
- (id)applyWithId:(id)i;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableFunction)

#define ComAnnimonStreamFunctionThrowableFunction CASThrowableFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableFunction")
