//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ToDoubleFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionToDoubleFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionToDoubleFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionToDoubleFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionToDoubleFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionToDoubleFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASToDoubleFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionToDoubleFunction || defined(INCLUDE_CASToDoubleFunction))
#define CASToDoubleFunction_

@class JavaLangDouble;

/*!
 @brief Represents a function which produces an <code>double</code>-valued result from input argument.
 @since 1.1.3
 - seealso: Function
 */
@protocol CASToDoubleFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param t an argument
 @return the function result
 */
- (double)applyAsDoubleWithId:(id)t;

@end

J2OBJC_EMPTY_STATIC_INIT(CASToDoubleFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASToDoubleFunction)

#define ComAnnimonStreamFunctionToDoubleFunction CASToDoubleFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionToDoubleFunction")
