//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ToIntFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionToIntFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionToIntFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionToIntFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionToIntFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionToIntFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASToIntFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionToIntFunction || defined(INCLUDE_CASToIntFunction))
#define CASToIntFunction_

@class JavaLangInteger;

/*!
 @brief Represents a function which produces an <code>int</code>-valued result from input argument.
 - seealso: Function
 */
@protocol CASToIntFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param t an argument
 @return the function result
 */
- (int32_t)applyAsIntWithId:(id)t;

@end

J2OBJC_EMPTY_STATIC_INIT(CASToIntFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASToIntFunction)

#define ComAnnimonStreamFunctionToIntFunction CASToIntFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionToIntFunction")
