//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/iterator/LazyIterator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamIteratorLazyIterator")
#ifdef RESTRICT_ComAnnimonStreamIteratorLazyIterator
#define INCLUDE_ALL_ComAnnimonStreamIteratorLazyIterator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamIteratorLazyIterator 1
#endif
#undef RESTRICT_ComAnnimonStreamIteratorLazyIterator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLazyIterator_) && (INCLUDE_ALL_ComAnnimonStreamIteratorLazyIterator || defined(INCLUDE_CASLazyIterator))
#define CASLazyIterator_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class JavaLangBoolean;
@protocol JavaLangIterable;
@protocol JavaUtilFunctionConsumer;

/*!
 @brief Lazily gets <code>Iterator</code> from the given <code>Iterable</code>.
 */
@interface CASLazyIterator : NSObject < JavaUtilIterator >

#pragma mark Public

- (instancetype _Nonnull)initWithJavaLangIterable:(id<JavaLangIterable>)iterable;

- (bool)hasNext;

- (id)next;

- (void)remove;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLazyIterator)

FOUNDATION_EXPORT void CASLazyIterator_initWithJavaLangIterable_(CASLazyIterator *self, id<JavaLangIterable> iterable);

FOUNDATION_EXPORT CASLazyIterator *new_CASLazyIterator_initWithJavaLangIterable_(id<JavaLangIterable> iterable) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLazyIterator *create_CASLazyIterator_initWithJavaLangIterable_(id<JavaLangIterable> iterable);

J2OBJC_TYPE_LITERAL_HEADER(CASLazyIterator)

@compatibility_alias ComAnnimonStreamIteratorLazyIterator CASLazyIterator;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamIteratorLazyIterator")
