//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/iterator/LsaExtIterator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamIteratorLsaExtIterator")
#ifdef RESTRICT_ComAnnimonStreamIteratorLsaExtIterator
#define INCLUDE_ALL_ComAnnimonStreamIteratorLsaExtIterator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamIteratorLsaExtIterator 1
#endif
#undef RESTRICT_ComAnnimonStreamIteratorLsaExtIterator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLsaExtIterator_) && (INCLUDE_ALL_ComAnnimonStreamIteratorLsaExtIterator || defined(INCLUDE_CASLsaExtIterator))
#define CASLsaExtIterator_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class JavaLangBoolean;
@protocol JavaUtilFunctionConsumer;

/*!
 @brief Extended iterator for common purposes.
 */
@interface CASLsaExtIterator : NSObject < JavaUtilIterator > {
 @public
  id next_;
  bool hasNext_;
  bool isInit_;
}

#pragma mark Public

- (instancetype _Nonnull)init;

- (bool)hasNext;

- (id)next;

- (void)remove;

#pragma mark Protected

- (void)nextIteration;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLsaExtIterator)

J2OBJC_FIELD_SETTER(CASLsaExtIterator, next_, id)

FOUNDATION_EXPORT void CASLsaExtIterator_init(CASLsaExtIterator *self);

J2OBJC_TYPE_LITERAL_HEADER(CASLsaExtIterator)

@compatibility_alias ComAnnimonStreamIteratorLsaExtIterator CASLsaExtIterator;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamIteratorLsaExtIterator")
