//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/iterator/PrimitiveIndexedIterator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveIndexedIterator")
#ifdef RESTRICT_ComAnnimonStreamIteratorPrimitiveIndexedIterator
#define INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveIndexedIterator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveIndexedIterator 1
#endif
#undef RESTRICT_ComAnnimonStreamIteratorPrimitiveIndexedIterator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASPrimitiveIndexedIterator_) && (INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveIndexedIterator || defined(INCLUDE_CASPrimitiveIndexedIterator))
#define CASPrimitiveIndexedIterator_

/*!
 @brief PrimitiveIterator wrapper that supports indexing.
 @since 1.2.1
 */
@interface CASPrimitiveIndexedIterator : NSObject

@end

J2OBJC_EMPTY_STATIC_INIT(CASPrimitiveIndexedIterator)

J2OBJC_TYPE_LITERAL_HEADER(CASPrimitiveIndexedIterator)

@compatibility_alias ComAnnimonStreamIteratorPrimitiveIndexedIterator CASPrimitiveIndexedIterator;


#endif

#if !defined (CASPrimitiveIndexedIterator_OfInt_) && (INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveIndexedIterator || defined(INCLUDE_CASPrimitiveIndexedIterator_OfInt))
#define CASPrimitiveIndexedIterator_OfInt_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;

@interface CASPrimitiveIndexedIterator_OfInt : CASPrimitiveIterator_OfInt

#pragma mark Public

- (instancetype _Nonnull)initWithInt:(int32_t)start
                             withInt:(int32_t)step
      withCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator;

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator;

- (int32_t)getIndex;

- (bool)hasNext;

- (int32_t)nextInt;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASPrimitiveIndexedIterator_OfInt)

FOUNDATION_EXPORT void CASPrimitiveIndexedIterator_OfInt_initWithCASPrimitiveIterator_OfInt_(CASPrimitiveIndexedIterator_OfInt *self, CASPrimitiveIterator_OfInt *iterator);

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfInt *new_CASPrimitiveIndexedIterator_OfInt_initWithCASPrimitiveIterator_OfInt_(CASPrimitiveIterator_OfInt *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfInt *create_CASPrimitiveIndexedIterator_OfInt_initWithCASPrimitiveIterator_OfInt_(CASPrimitiveIterator_OfInt *iterator);

FOUNDATION_EXPORT void CASPrimitiveIndexedIterator_OfInt_initWithInt_withInt_withCASPrimitiveIterator_OfInt_(CASPrimitiveIndexedIterator_OfInt *self, int32_t start, int32_t step, CASPrimitiveIterator_OfInt *iterator);

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfInt *new_CASPrimitiveIndexedIterator_OfInt_initWithInt_withInt_withCASPrimitiveIterator_OfInt_(int32_t start, int32_t step, CASPrimitiveIterator_OfInt *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfInt *create_CASPrimitiveIndexedIterator_OfInt_initWithInt_withInt_withCASPrimitiveIterator_OfInt_(int32_t start, int32_t step, CASPrimitiveIterator_OfInt *iterator);

J2OBJC_TYPE_LITERAL_HEADER(CASPrimitiveIndexedIterator_OfInt)


#endif

#if !defined (CASPrimitiveIndexedIterator_OfLong_) && (INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveIndexedIterator || defined(INCLUDE_CASPrimitiveIndexedIterator_OfLong))
#define CASPrimitiveIndexedIterator_OfLong_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;

@interface CASPrimitiveIndexedIterator_OfLong : CASPrimitiveIterator_OfLong

#pragma mark Public

- (instancetype _Nonnull)initWithInt:(int32_t)start
                             withInt:(int32_t)step
     withCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator;

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator;

- (int32_t)getIndex;

- (bool)hasNext;

- (int64_t)nextLong;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASPrimitiveIndexedIterator_OfLong)

FOUNDATION_EXPORT void CASPrimitiveIndexedIterator_OfLong_initWithCASPrimitiveIterator_OfLong_(CASPrimitiveIndexedIterator_OfLong *self, CASPrimitiveIterator_OfLong *iterator);

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfLong *new_CASPrimitiveIndexedIterator_OfLong_initWithCASPrimitiveIterator_OfLong_(CASPrimitiveIterator_OfLong *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfLong *create_CASPrimitiveIndexedIterator_OfLong_initWithCASPrimitiveIterator_OfLong_(CASPrimitiveIterator_OfLong *iterator);

FOUNDATION_EXPORT void CASPrimitiveIndexedIterator_OfLong_initWithInt_withInt_withCASPrimitiveIterator_OfLong_(CASPrimitiveIndexedIterator_OfLong *self, int32_t start, int32_t step, CASPrimitiveIterator_OfLong *iterator);

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfLong *new_CASPrimitiveIndexedIterator_OfLong_initWithInt_withInt_withCASPrimitiveIterator_OfLong_(int32_t start, int32_t step, CASPrimitiveIterator_OfLong *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfLong *create_CASPrimitiveIndexedIterator_OfLong_initWithInt_withInt_withCASPrimitiveIterator_OfLong_(int32_t start, int32_t step, CASPrimitiveIterator_OfLong *iterator);

J2OBJC_TYPE_LITERAL_HEADER(CASPrimitiveIndexedIterator_OfLong)


#endif

#if !defined (CASPrimitiveIndexedIterator_OfDouble_) && (INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveIndexedIterator || defined(INCLUDE_CASPrimitiveIndexedIterator_OfDouble))
#define CASPrimitiveIndexedIterator_OfDouble_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangInteger;

@interface CASPrimitiveIndexedIterator_OfDouble : CASPrimitiveIterator_OfDouble

#pragma mark Public

- (instancetype _Nonnull)initWithInt:(int32_t)start
                             withInt:(int32_t)step
   withCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator;

- (instancetype _Nonnull)initWithCASPrimitiveIterator_OfDouble:(CASPrimitiveIterator_OfDouble *)iterator;

- (int32_t)getIndex;

- (bool)hasNext;

- (double)nextDouble;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASPrimitiveIndexedIterator_OfDouble)

FOUNDATION_EXPORT void CASPrimitiveIndexedIterator_OfDouble_initWithCASPrimitiveIterator_OfDouble_(CASPrimitiveIndexedIterator_OfDouble *self, CASPrimitiveIterator_OfDouble *iterator);

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfDouble *new_CASPrimitiveIndexedIterator_OfDouble_initWithCASPrimitiveIterator_OfDouble_(CASPrimitiveIterator_OfDouble *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfDouble *create_CASPrimitiveIndexedIterator_OfDouble_initWithCASPrimitiveIterator_OfDouble_(CASPrimitiveIterator_OfDouble *iterator);

FOUNDATION_EXPORT void CASPrimitiveIndexedIterator_OfDouble_initWithInt_withInt_withCASPrimitiveIterator_OfDouble_(CASPrimitiveIndexedIterator_OfDouble *self, int32_t start, int32_t step, CASPrimitiveIterator_OfDouble *iterator);

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfDouble *new_CASPrimitiveIndexedIterator_OfDouble_initWithInt_withInt_withCASPrimitiveIterator_OfDouble_(int32_t start, int32_t step, CASPrimitiveIterator_OfDouble *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASPrimitiveIndexedIterator_OfDouble *create_CASPrimitiveIndexedIterator_OfDouble_initWithInt_withInt_withCASPrimitiveIterator_OfDouble_(int32_t start, int32_t step, CASPrimitiveIterator_OfDouble *iterator);

J2OBJC_TYPE_LITERAL_HEADER(CASPrimitiveIndexedIterator_OfDouble)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveIndexedIterator")
