//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/BiConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionBiConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionBiConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionBiConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionBiConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionBiConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASBiConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionBiConsumer || defined(INCLUDE_CASBiConsumer))
#define CASBiConsumer_

/*!
 @brief Represents an operation on two input arguments.
 - seealso: Consumer
 */
@protocol CASBiConsumer < JavaObject >

/*!
 @brief Performs operation on two arguments.
 @param value1 the first argument
 @param value2 the second argument
 */
- (void)acceptWithId:(id)value1
              withId:(id)value2;

@end

J2OBJC_EMPTY_STATIC_INIT(CASBiConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASBiConsumer)

#define ComAnnimonStreamFunctionBiConsumer CASBiConsumer


#endif

#if !defined (CASBiConsumer_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionBiConsumer || defined(INCLUDE_CASBiConsumer_Util))
#define CASBiConsumer_Util_

@protocol CASBiConsumer;

@interface CASBiConsumer_Util : NSObject

#pragma mark Public

/*!
 @brief Composes <code>BiConsumer</code> calls.
 <p><code>c1.accept(t, u); c2.accept(t, u);</code>
 @param c1 the first <code>BiConsumer</code>
 @param c2 the second <code>BiConsumer</code>
 @return composed <code>BiConsumer</code>
 @throw NullPointerExceptionif <code>c1</code> or <code>c2</code> is null
 */
+ (id<CASBiConsumer>)andThenWithCASBiConsumer:(id<CASBiConsumer>)c1
                            withCASBiConsumer:(id<CASBiConsumer>)c2;

@end

J2OBJC_EMPTY_STATIC_INIT(CASBiConsumer_Util)

FOUNDATION_EXPORT id<CASBiConsumer> CASBiConsumer_Util_andThenWithCASBiConsumer_withCASBiConsumer_(id<CASBiConsumer> c1, id<CASBiConsumer> c2);

J2OBJC_TYPE_LITERAL_HEADER(CASBiConsumer_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionBiConsumer")
