//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/DoubleConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionDoubleConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionDoubleConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionDoubleConsumer || defined(INCLUDE_CASDoubleConsumer))
#define CASDoubleConsumer_

@class JavaLangDouble;

/*!
 @brief Represents an operation on a <code>double</code>-valued input argument.
 @since 1.1.4
 - seealso: Consumer
 */
@protocol CASDoubleConsumer < JavaObject >

/*!
 @brief Performs operation on the given argument.
 @param value the input argument
 */
- (void)acceptWithDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleConsumer)

#define ComAnnimonStreamFunctionDoubleConsumer CASDoubleConsumer


#endif

#if !defined (CASDoubleConsumer_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionDoubleConsumer || defined(INCLUDE_CASDoubleConsumer_Util))
#define CASDoubleConsumer_Util_

@protocol CASDoubleConsumer;
@protocol CASThrowableDoubleConsumer;

@interface CASDoubleConsumer_Util : NSObject

#pragma mark Public

/*!
 @brief Composes <code>DoubleConsumer</code> calls.
 <p><code>c1.accept(value); c2.accept(value);</code>
 @param c1 the first <code>DoubleConsumer</code>
 @param c2 the second <code>DoubleConsumer</code>
 @return a composed <code>DoubleConsumer</code>
 @throw NullPointerExceptionif <code>c1</code> or <code>c2</code> is null
 */
+ (id<CASDoubleConsumer>)andThenWithCASDoubleConsumer:(id<CASDoubleConsumer>)c1
                                withCASDoubleConsumer:(id<CASDoubleConsumer>)c2;

/*!
 @brief Creates a safe <code>DoubleConsumer</code>.
 @param throwableConsumer the consumer that may throw an exception
 @return a <code>DoubleConsumer</code>
 @throw NullPointerExceptionif <code>throwableConsumer</code> is null
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableDoubleConsumer, com.annimon.stream.function.DoubleConsumer)
 */
+ (id<CASDoubleConsumer>)safeWithCASThrowableDoubleConsumer:(id<CASThrowableDoubleConsumer>)throwableConsumer;

/*!
 @brief Creates a safe <code>DoubleConsumer</code>.
 @param throwableConsumer the consumer that may throw an exception
 @param onFailedConsumer the consumer which applies if exception was thrown
 @return a <code>DoubleConsumer</code>
 @throw NullPointerExceptionif <code>throwableConsumer</code> is null
 @since 1.1.7
 - seealso: #safe(com.annimon.stream.function.ThrowableDoubleConsumer)
 */
+ (id<CASDoubleConsumer>)safeWithCASThrowableDoubleConsumer:(id<CASThrowableDoubleConsumer>)throwableConsumer
                                      withCASDoubleConsumer:(id<CASDoubleConsumer>)onFailedConsumer;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleConsumer_Util)

FOUNDATION_EXPORT id<CASDoubleConsumer> CASDoubleConsumer_Util_andThenWithCASDoubleConsumer_withCASDoubleConsumer_(id<CASDoubleConsumer> c1, id<CASDoubleConsumer> c2);

FOUNDATION_EXPORT id<CASDoubleConsumer> CASDoubleConsumer_Util_safeWithCASThrowableDoubleConsumer_(id<CASThrowableDoubleConsumer> throwableConsumer);

FOUNDATION_EXPORT id<CASDoubleConsumer> CASDoubleConsumer_Util_safeWithCASThrowableDoubleConsumer_withCASDoubleConsumer_(id<CASThrowableDoubleConsumer> throwableConsumer, id<CASDoubleConsumer> onFailedConsumer);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleConsumer_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleConsumer")
