//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/DoubleUnaryOperator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleUnaryOperator")
#ifdef RESTRICT_ComAnnimonStreamFunctionDoubleUnaryOperator
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleUnaryOperator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionDoubleUnaryOperator 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionDoubleUnaryOperator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASDoubleUnaryOperator_) && (INCLUDE_ALL_ComAnnimonStreamFunctionDoubleUnaryOperator || defined(INCLUDE_CASDoubleUnaryOperator))
#define CASDoubleUnaryOperator_

@class JavaLangDouble;

/*!
 @brief Represents an operation on a single <code>double</code>-valued operand
  that produces a <code>double</code>-valued result.
 @since 1.1.4
 - seealso: UnaryOperator
 */
@protocol CASDoubleUnaryOperator < JavaObject >

/*!
 @brief Applies this operator to the given operand.
 @param operand the operand
 @return the operator result
 */
- (double)applyAsDoubleWithDouble:(double)operand;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleUnaryOperator)

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleUnaryOperator)

#define ComAnnimonStreamFunctionDoubleUnaryOperator CASDoubleUnaryOperator


#endif

#if !defined (CASDoubleUnaryOperator_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionDoubleUnaryOperator || defined(INCLUDE_CASDoubleUnaryOperator_Util))
#define CASDoubleUnaryOperator_Util_

@protocol CASDoubleUnaryOperator;

@interface CASDoubleUnaryOperator_Util : NSObject

#pragma mark Public

/*!
 @brief Returns a unary operator that always returns its input argument.
 @return a unary operator that always returns its input argument
 */
+ (id<CASDoubleUnaryOperator>)identity;

@end

J2OBJC_EMPTY_STATIC_INIT(CASDoubleUnaryOperator_Util)

FOUNDATION_EXPORT id<CASDoubleUnaryOperator> CASDoubleUnaryOperator_Util_identity(void);

J2OBJC_TYPE_LITERAL_HEADER(CASDoubleUnaryOperator_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionDoubleUnaryOperator")
