//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedLongConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedLongConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedLongConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedLongConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongConsumer || defined(INCLUDE_CASIndexedLongConsumer))
#define CASIndexedLongConsumer_

@class JavaLangInteger;
@class JavaLangLong;

/*!
 @brief Represents an operation on index and input argument.
 @since 1.2.1
 */
@protocol CASIndexedLongConsumer < JavaObject >

/*!
 @brief Performs operation on argument.
 @param index the index
 @param value the input argument
 */
- (void)acceptWithInt:(int32_t)index
             withLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedLongConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedLongConsumer)

#define ComAnnimonStreamFunctionIndexedLongConsumer CASIndexedLongConsumer


#endif

#if !defined (CASIndexedLongConsumer_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongConsumer || defined(INCLUDE_CASIndexedLongConsumer_Util))
#define CASIndexedLongConsumer_Util_

@protocol CASIndexedLongConsumer;
@protocol CASIntConsumer;
@protocol CASLongConsumer;

@interface CASIndexedLongConsumer_Util : NSObject

#pragma mark Public

/*!
 @brief Returns an <code>IndexedLongConsumer</code> that accepts <code>IntConsumer</code>
  for index and <code>LongConsumer</code> for value.
 @code
<code>
   if (c1 != null)
       c1.accept(index);
   if (c2 != null)
       c2.accept(object); 
  </code>
@endcode
 @param c1 the <code>IntConsumer</code>  for index, can be null
 @param c2 the <code>LongConsumer</code>  for value, can be null
 @return an <code>IndexedLongConsumer</code>
 */
+ (id<CASIndexedLongConsumer>)acceptWithCASIntConsumer:(id<CASIntConsumer>)c1
                                   withCASLongConsumer:(id<CASLongConsumer>)c2;

/*!
 @brief Composes <code>IndexedLongConsumer</code> calls.
 <p><code>c1.accept(index, value); c2.accept(index, value);</code>
 @param c1 the first <code>IndexedLongConsumer</code>
 @param c2 the second <code>IndexedLongConsumer</code>
 @return a composed <code>IndexedLongConsumer</code>
 @throw NullPointerExceptionif <code>c1</code> or <code>c2</code> is null
 */
+ (id<CASIndexedLongConsumer>)andThenWithCASIndexedLongConsumer:(id<CASIndexedLongConsumer>)c1
                                     withCASIndexedLongConsumer:(id<CASIndexedLongConsumer>)c2;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedLongConsumer_Util)

FOUNDATION_EXPORT id<CASIndexedLongConsumer> CASIndexedLongConsumer_Util_andThenWithCASIndexedLongConsumer_withCASIndexedLongConsumer_(id<CASIndexedLongConsumer> c1, id<CASIndexedLongConsumer> c2);

FOUNDATION_EXPORT id<CASIndexedLongConsumer> CASIndexedLongConsumer_Util_acceptWithCASIntConsumer_withCASLongConsumer_(id<CASIntConsumer> c1, id<CASLongConsumer> c2);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedLongConsumer_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongConsumer")
