//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedLongPredicate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongPredicate")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedLongPredicate
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongPredicate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongPredicate 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedLongPredicate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedLongPredicate_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongPredicate || defined(INCLUDE_CASIndexedLongPredicate))
#define CASIndexedLongPredicate_

@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;

/*!
 @brief Represents a predicate (function with boolean type result) with additional index argument.
 @since 1.2.1
 */
@protocol CASIndexedLongPredicate < JavaObject >

/*!
 @brief Tests the value for satisfying predicate.
 @param index the index
 @param value the value to be tested
 @return <code>true</code> if the value matches the predicate, otherwise <code>false</code>
 */
- (bool)testWithInt:(int32_t)index
           withLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedLongPredicate)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedLongPredicate)

#define ComAnnimonStreamFunctionIndexedLongPredicate CASIndexedLongPredicate


#endif

#if !defined (CASIndexedLongPredicate_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongPredicate || defined(INCLUDE_CASIndexedLongPredicate_Util))
#define CASIndexedLongPredicate_Util_

@protocol CASIndexedLongPredicate;
@protocol CASLongPredicate;

@interface CASIndexedLongPredicate_Util : NSObject

#pragma mark Public

/*!
 @brief Wraps <code>LongPredicate</code> and returns <code>IndexedLongPredicate</code>.
 @param predicate the predicate to wrap
 @return a wrapped <code>IndexedLongPredicate</code>
 @throw NullPointerExceptionif <code>predicate</code> is null
 */
+ (id<CASIndexedLongPredicate>)wrapWithCASLongPredicate:(id<CASLongPredicate>)predicate;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedLongPredicate_Util)

FOUNDATION_EXPORT id<CASIndexedLongPredicate> CASIndexedLongPredicate_Util_wrapWithCASLongPredicate_(id<CASLongPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedLongPredicate_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedLongPredicate")
