//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedIntPredicate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntPredicate")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedIntPredicate
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntPredicate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntPredicate 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedIntPredicate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedIntPredicate_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntPredicate || defined(INCLUDE_CASIndexedIntPredicate))
#define CASIndexedIntPredicate_

@class JavaLangBoolean;
@class JavaLangInteger;

/*!
 @brief Represents a predicate (function with boolean type result) with additional index argument.
 @since 1.2.1
 */
@protocol CASIndexedIntPredicate < JavaObject >

/*!
 @brief Tests the value for satisfying predicate.
 @param index the index
 @param value the value to be tested
 @return <code>true</code> if the value matches the predicate, otherwise <code>false</code>
 */
- (bool)testWithInt:(int32_t)index
            withInt:(int32_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedIntPredicate)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedIntPredicate)

#define ComAnnimonStreamFunctionIndexedIntPredicate CASIndexedIntPredicate


#endif

#if !defined (CASIndexedIntPredicate_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntPredicate || defined(INCLUDE_CASIndexedIntPredicate_Util))
#define CASIndexedIntPredicate_Util_

@protocol CASIndexedIntPredicate;
@protocol CASIntPredicate;

@interface CASIndexedIntPredicate_Util : NSObject

#pragma mark Public

/*!
 @brief Wraps <code>IntPredicate</code> and returns <code>IndexedIntPredicate</code>.
 @param predicate the predicate to wrap
 @return a wrapped <code>IndexedIntPredicate</code>
 @throw NullPointerExceptionif <code>predicate</code> is null
 */
+ (id<CASIndexedIntPredicate>)wrapWithCASIntPredicate:(id<CASIntPredicate>)predicate;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedIntPredicate_Util)

FOUNDATION_EXPORT id<CASIndexedIntPredicate> CASIndexedIntPredicate_Util_wrapWithCASIntPredicate_(id<CASIntPredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedIntPredicate_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedIntPredicate")
