//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/IndexedConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionIndexedConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionIndexedConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionIndexedConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedConsumer || defined(INCLUDE_CASIndexedConsumer))
#define CASIndexedConsumer_

@class JavaLangInteger;

/*!
 @brief Represents an operation on index and input argument.
 @since 1.1.6
 */
@protocol CASIndexedConsumer < JavaObject >

/*!
 @brief Performs operation on argument.
 @param index the index
 @param t the input argument
 */
- (void)acceptWithInt:(int32_t)index
               withId:(id)t;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedConsumer)

#define ComAnnimonStreamFunctionIndexedConsumer CASIndexedConsumer


#endif

#if !defined (CASIndexedConsumer_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionIndexedConsumer || defined(INCLUDE_CASIndexedConsumer_Util))
#define CASIndexedConsumer_Util_

@protocol CASConsumer;
@protocol CASIndexedConsumer;
@protocol CASIntConsumer;

@interface CASIndexedConsumer_Util : NSObject

#pragma mark Public

/*!
 @brief Returns an <code>IndexedConsumer</code> that accepts <code>IntConsumer</code>
  for index and <code>Consumer</code> for object.
 @code
<code>
   if (c1 != null)
       c1.accept(index);
   if (c2 != null)
       c2.accept(object); 
  </code>
@endcode
 @param c1 the <code>IntConsumer</code>  for index, can be null
 @param c2 the <code>Consumer</code>  for object, can be null
 @return an <code>IndexedConsumer</code>
 */
+ (id<CASIndexedConsumer>)acceptWithCASIntConsumer:(id<CASIntConsumer>)c1
                                   withCASConsumer:(id<CASConsumer>)c2;

/*!
 @brief Wraps a <code>Consumer</code> and returns <code>IndexedConsumer</code>.
 @param consumer the consumer to wrap
 @return a wrapped <code>IndexedConsumer</code>
 @throw NullPointerExceptionif <code>consumer</code> is null
 */
+ (id<CASIndexedConsumer>)wrapWithCASConsumer:(id<CASConsumer>)consumer;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedConsumer_Util)

FOUNDATION_EXPORT id<CASIndexedConsumer> CASIndexedConsumer_Util_wrapWithCASConsumer_(id<CASConsumer> consumer);

FOUNDATION_EXPORT id<CASIndexedConsumer> CASIndexedConsumer_Util_acceptWithCASIntConsumer_withCASConsumer_(id<CASIntConsumer> c1, id<CASConsumer> c2);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedConsumer_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionIndexedConsumer")
