//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/LongUnaryOperator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongUnaryOperator")
#ifdef RESTRICT_ComAnnimonStreamFunctionLongUnaryOperator
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongUnaryOperator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongUnaryOperator 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionLongUnaryOperator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongUnaryOperator_) && (INCLUDE_ALL_ComAnnimonStreamFunctionLongUnaryOperator || defined(INCLUDE_CASLongUnaryOperator))
#define CASLongUnaryOperator_

@class JavaLangLong;

/*!
 @brief Represents an operation on a single <code>long</code>-valued operand
  that produces a <code>long</code>-valued result.
 @since 1.1.4
 - seealso: UnaryOperator
 */
@protocol CASLongUnaryOperator < JavaObject >

/*!
 @brief Applies this operator to the given operand.
 @param operand the operand
 @return the operator result
 */
- (int64_t)applyAsLongWithLong:(int64_t)operand;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongUnaryOperator)

J2OBJC_TYPE_LITERAL_HEADER(CASLongUnaryOperator)

#define ComAnnimonStreamFunctionLongUnaryOperator CASLongUnaryOperator


#endif

#if !defined (CASLongUnaryOperator_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionLongUnaryOperator || defined(INCLUDE_CASLongUnaryOperator_Util))
#define CASLongUnaryOperator_Util_

@protocol CASLongUnaryOperator;

@interface CASLongUnaryOperator_Util : NSObject

#pragma mark Public

/*!
 @brief Returns a unary operator that always returns its input argument.
 @return a unary operator that always returns its input argument
 */
+ (id<CASLongUnaryOperator>)identity;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongUnaryOperator_Util)

FOUNDATION_EXPORT id<CASLongUnaryOperator> CASLongUnaryOperator_Util_identity(void);

J2OBJC_TYPE_LITERAL_HEADER(CASLongUnaryOperator_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongUnaryOperator")
