//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/LongToDoubleFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongToDoubleFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionLongToDoubleFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongToDoubleFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongToDoubleFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionLongToDoubleFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongToDoubleFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionLongToDoubleFunction || defined(INCLUDE_CASLongToDoubleFunction))
#define CASLongToDoubleFunction_

@class JavaLangDouble;
@class JavaLangLong;

/*!
 @brief Represents a function which produces an <code>double</code>-valued result from input argument.
 @since 1.1.4
 - seealso: Function
 */
@protocol CASLongToDoubleFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value an argument
 @return the function result
 */
- (double)applyAsDoubleWithLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongToDoubleFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASLongToDoubleFunction)

#define ComAnnimonStreamFunctionLongToDoubleFunction CASLongToDoubleFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongToDoubleFunction")
