//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/LongToIntFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongToIntFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionLongToIntFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongToIntFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionLongToIntFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionLongToIntFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongToIntFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionLongToIntFunction || defined(INCLUDE_CASLongToIntFunction))
#define CASLongToIntFunction_

@class JavaLangInteger;
@class JavaLangLong;

/*!
 @brief Represents a function which produces an <code>int</code>-valued result from input argument.
 @since 1.1.4
 - seealso: Function
 */
@protocol CASLongToIntFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value an argument
 @return the function result
 */
- (int32_t)applyAsIntWithLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASLongToIntFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASLongToIntFunction)

#define ComAnnimonStreamFunctionLongToIntFunction CASLongToIntFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionLongToIntFunction")
