//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ObjLongConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionObjLongConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionObjLongConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionObjLongConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionObjLongConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionObjLongConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjLongConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionObjLongConsumer || defined(INCLUDE_CASObjLongConsumer))
#define CASObjLongConsumer_

@class JavaLangLong;

/*!
 @brief Represents an operation on two input arguments.
 @since 1.1.4
 - seealso: BiConsumer
 */
@protocol CASObjLongConsumer < JavaObject >

/*!
 @brief Performs operation on two arguments.
 @param t the first argument
 @param value the second argument
 */
- (void)acceptWithId:(id)t
            withLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjLongConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASObjLongConsumer)

#define ComAnnimonStreamFunctionObjLongConsumer CASObjLongConsumer


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionObjLongConsumer")
