//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableIntFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableIntFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableIntFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableIntFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntFunction || defined(INCLUDE_CASThrowableIntFunction))
#define CASThrowableIntFunction_

@class JavaLangInteger;

/*!
 @brief Represents a function which produces result from <code>int</code>-valued input argument.
 @since 1.1.7
 - seealso: IntFunction
 */
@protocol CASThrowableIntFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value the function argument
 @return the function result
 @throw Ean exception
 */
- (id)applyWithInt:(int32_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableIntFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableIntFunction)

#define ComAnnimonStreamFunctionThrowableIntFunction CASThrowableIntFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntFunction")
