//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableDoubleFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableDoubleFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableDoubleFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableDoubleFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleFunction || defined(INCLUDE_CASThrowableDoubleFunction))
#define CASThrowableDoubleFunction_

@class JavaLangDouble;

/*!
 @brief Represents a function which produces result from <code>double</code>-valued input argument.
 @since 1.1.7
 - seealso: DoubleFunction
 */
@protocol CASThrowableDoubleFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param value the function argument
 @return the function result
 @throw Ean exception
 */
- (id)applyWithDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableDoubleFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableDoubleFunction)

#define ComAnnimonStreamFunctionThrowableDoubleFunction CASThrowableDoubleFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleFunction")
