//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableLongPredicate.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongPredicate")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableLongPredicate
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongPredicate 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongPredicate 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableLongPredicate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableLongPredicate_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongPredicate || defined(INCLUDE_CASThrowableLongPredicate))
#define CASThrowableLongPredicate_

@class JavaLangBoolean;
@class JavaLangLong;

/*!
 @brief Represents a <code>long</code>-valued predicate (function with boolean type result).
 @since 1.1.7
 - seealso: LongPredicate
 */
@protocol CASThrowableLongPredicate < JavaObject >

/*!
 @brief Tests the value for satisfying predicate.
 @param value the value to be tested
 @return <code>true</code> if the value matches the predicate, otherwise <code>false</code>
 @throw Ean exception
 */
- (bool)testWithLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableLongPredicate)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableLongPredicate)

#define ComAnnimonStreamFunctionThrowableLongPredicate CASThrowableLongPredicate


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongPredicate")
