//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableLongConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableLongConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableLongConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableLongConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongConsumer || defined(INCLUDE_CASThrowableLongConsumer))
#define CASThrowableLongConsumer_

@class JavaLangLong;

/*!
 @brief Represents an operation on a <code>long</code>-valued input argument.
 @since 1.1.7
 - seealso: LongConsumer
 */
@protocol CASThrowableLongConsumer < JavaObject >

/*!
 @brief Performs operation on the given argument.
 @param value the input argument
 @throw Ean exception
 */
- (void)acceptWithLong:(int64_t)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableLongConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableLongConsumer)

#define ComAnnimonStreamFunctionThrowableLongConsumer CASThrowableLongConsumer


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableLongConsumer")
