//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableDoubleConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableDoubleConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableDoubleConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableDoubleConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleConsumer || defined(INCLUDE_CASThrowableDoubleConsumer))
#define CASThrowableDoubleConsumer_

@class JavaLangDouble;

/*!
 @brief Represents an operation on a <code>double</code>-valued input argument.
 @since 1.1.7
 - seealso: DoubleConsumer
 */
@protocol CASThrowableDoubleConsumer < JavaObject >

/*!
 @brief Performs operation on the given argument.
 @param value the input argument
 @throw Ean exception
 */
- (void)acceptWithDouble:(double)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableDoubleConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableDoubleConsumer)

#define ComAnnimonStreamFunctionThrowableDoubleConsumer CASThrowableDoubleConsumer


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableDoubleConsumer")
