//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableIntSupplier.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntSupplier")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableIntSupplier
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntSupplier 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntSupplier 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableIntSupplier

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableIntSupplier_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntSupplier || defined(INCLUDE_CASThrowableIntSupplier))
#define CASThrowableIntSupplier_

@class JavaLangInteger;

/*!
 @brief Represents a supplier of <code>int</code>-valued results.
 @since 1.1.7
 - seealso: IntSupplier
 */
@protocol CASThrowableIntSupplier < JavaObject >

/*!
 @brief Gets a result.
 @return a result
 @throw Ean exception
 */
- (int32_t)getAsInt;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableIntSupplier)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableIntSupplier)

#define ComAnnimonStreamFunctionThrowableIntSupplier CASThrowableIntSupplier


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableIntSupplier")
