//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ThrowableConsumer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableConsumer")
#ifdef RESTRICT_ComAnnimonStreamFunctionThrowableConsumer
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableConsumer 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionThrowableConsumer 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionThrowableConsumer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASThrowableConsumer_) && (INCLUDE_ALL_ComAnnimonStreamFunctionThrowableConsumer || defined(INCLUDE_CASThrowableConsumer))
#define CASThrowableConsumer_

/*!
 @brief Represents an operation on input argument and can throw an exception.
 - seealso: Consumer
 */
@protocol CASThrowableConsumer < JavaObject >

/*!
 @brief Performs operation on argument.
 @param value the input argument
 @throw Ean exception
 */
- (void)acceptWithId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(CASThrowableConsumer)

J2OBJC_TYPE_LITERAL_HEADER(CASThrowableConsumer)

#define ComAnnimonStreamFunctionThrowableConsumer CASThrowableConsumer


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionThrowableConsumer")
