//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ToBooleanFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionToBooleanFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionToBooleanFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionToBooleanFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionToBooleanFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionToBooleanFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASToBooleanFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionToBooleanFunction || defined(INCLUDE_CASToBooleanFunction))
#define CASToBooleanFunction_

@class JavaLangBoolean;

/*!
 @brief Represents a function which produces an <code>boolean</code>-valued result from input argument.
 - seealso: Function
 */
@protocol CASToBooleanFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param t an argument
 @return the function result
 */
- (bool)applyAsBooleanWithId:(id)t;

@end

J2OBJC_EMPTY_STATIC_INIT(CASToBooleanFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASToBooleanFunction)

#define ComAnnimonStreamFunctionToBooleanFunction CASToBooleanFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionToBooleanFunction")
