//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/ToLongFunction.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionToLongFunction")
#ifdef RESTRICT_ComAnnimonStreamFunctionToLongFunction
#define INCLUDE_ALL_ComAnnimonStreamFunctionToLongFunction 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionToLongFunction 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionToLongFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASToLongFunction_) && (INCLUDE_ALL_ComAnnimonStreamFunctionToLongFunction || defined(INCLUDE_CASToLongFunction))
#define CASToLongFunction_

@class JavaLangLong;

/*!
 @brief Represents a function which produces an <code>long</code>-valued result from input argument.
 @since 1.1.3
 - seealso: Function
 */
@protocol CASToLongFunction < JavaObject >

/*!
 @brief Applies this function to the given argument.
 @param t an argument
 @return the function result
 */
- (int64_t)applyAsLongWithId:(id)t;

@end

J2OBJC_EMPTY_STATIC_INIT(CASToLongFunction)

J2OBJC_TYPE_LITERAL_HEADER(CASToLongFunction)

#define ComAnnimonStreamFunctionToLongFunction CASToLongFunction


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionToLongFunction")
