//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/function/UnaryOperator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamFunctionUnaryOperator")
#ifdef RESTRICT_ComAnnimonStreamFunctionUnaryOperator
#define INCLUDE_ALL_ComAnnimonStreamFunctionUnaryOperator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamFunctionUnaryOperator 1
#endif
#undef RESTRICT_ComAnnimonStreamFunctionUnaryOperator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASUnaryOperator_) && (INCLUDE_ALL_ComAnnimonStreamFunctionUnaryOperator || defined(INCLUDE_CASUnaryOperator))
#define CASUnaryOperator_

#define RESTRICT_ComAnnimonStreamFunctionFunction 1
#define INCLUDE_CASFunction 1
#include "com/annimon/stream/function/Function.h"

/*!
 @brief Operation on a single operand that produces a result of the
  same type as its operand.
 */
@protocol CASUnaryOperator < CASFunction, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(CASUnaryOperator)

J2OBJC_TYPE_LITERAL_HEADER(CASUnaryOperator)

#define ComAnnimonStreamFunctionUnaryOperator CASUnaryOperator


#endif

#if !defined (CASUnaryOperator_Util_) && (INCLUDE_ALL_ComAnnimonStreamFunctionUnaryOperator || defined(INCLUDE_CASUnaryOperator_Util))
#define CASUnaryOperator_Util_

@protocol CASUnaryOperator;

@interface CASUnaryOperator_Util : NSObject

#pragma mark Public

/*!
 @brief Returns a unary operator that always returns its input argument.
 @return a unary operator that always returns its input argument
 */
+ (id<CASUnaryOperator>)identity;

@end

J2OBJC_EMPTY_STATIC_INIT(CASUnaryOperator_Util)

FOUNDATION_EXPORT id<CASUnaryOperator> CASUnaryOperator_Util_identity(void);

J2OBJC_TYPE_LITERAL_HEADER(CASUnaryOperator_Util)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamFunctionUnaryOperator")
