//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/internal/Compose.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamInternalCompose")
#ifdef RESTRICT_ComAnnimonStreamInternalCompose
#define INCLUDE_ALL_ComAnnimonStreamInternalCompose 0
#else
#define INCLUDE_ALL_ComAnnimonStreamInternalCompose 1
#endif
#undef RESTRICT_ComAnnimonStreamInternalCompose

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASCompose_) && (INCLUDE_ALL_ComAnnimonStreamInternalCompose || defined(INCLUDE_CASCompose))
#define CASCompose_

@protocol JavaIoCloseable;
@protocol JavaLangRunnable;

@interface CASCompose : NSObject

#pragma mark Public

+ (id<JavaLangRunnable>)closeablesWithJavaIoCloseable:(id<JavaIoCloseable>)a
                                  withJavaIoCloseable:(id<JavaIoCloseable>)b;

+ (id<JavaLangRunnable>)runnablesWithJavaLangRunnable:(id<JavaLangRunnable>)a
                                 withJavaLangRunnable:(id<JavaLangRunnable>)b;

@end

J2OBJC_EMPTY_STATIC_INIT(CASCompose)

FOUNDATION_EXPORT id<JavaLangRunnable> CASCompose_runnablesWithJavaLangRunnable_withJavaLangRunnable_(id<JavaLangRunnable> a, id<JavaLangRunnable> b);

FOUNDATION_EXPORT id<JavaLangRunnable> CASCompose_closeablesWithJavaIoCloseable_withJavaIoCloseable_(id<JavaIoCloseable> a, id<JavaIoCloseable> b);

J2OBJC_TYPE_LITERAL_HEADER(CASCompose)

@compatibility_alias ComAnnimonStreamInternalCompose CASCompose;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamInternalCompose")
