//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/Collectors.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamCollectors")
#ifdef RESTRICT_ComAnnimonStreamCollectors
#define INCLUDE_ALL_ComAnnimonStreamCollectors 0
#else
#define INCLUDE_ALL_ComAnnimonStreamCollectors 1
#endif
#undef RESTRICT_ComAnnimonStreamCollectors

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASCollectors_) && (INCLUDE_ALL_ComAnnimonStreamCollectors || defined(INCLUDE_CASCollectors))
#define CASCollectors_

@class NSString;
@protocol CASBinaryOperator;
@protocol CASCollector;
@protocol CASFunction;
@protocol CASPredicate;
@protocol CASSupplier;
@protocol CASToDoubleFunction;
@protocol CASToIntFunction;
@protocol CASToLongFunction;
@protocol JavaLangCharSequence;

/*!
 @brief Common implementations of <code>Collector</code> interface.
 - seealso: Collector
 */
@interface CASCollectors : NSObject

#pragma mark Public

/*!
 @brief Returns a <code>Collector</code> that calculates average of input elements.
 @param mapper the mapping function which extracts value from element to calculate result
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)averagingWithCASFunction:(id<CASFunction>)mapper __attribute__((deprecated));

/*!
 @brief Returns a <code>Collector</code> that calculates average of double-valued input elements.
 @param mapper the mapping function which extracts value from element to calculate result
 @return a <code>Collector</code>
 @since 1.1.3
 */
+ (id<CASCollector>)averagingDoubleWithCASToDoubleFunction:(id<CASToDoubleFunction>)mapper;

/*!
 @brief Returns a <code>Collector</code> that calculates average of integer-valued input elements.
 @param mapper the mapping function which extracts value from element to calculate result
 @return a <code>Collector</code>
 @since 1.1.3
 */
+ (id<CASCollector>)averagingIntWithCASToIntFunction:(id<CASToIntFunction>)mapper;

/*!
 @brief Returns a <code>Collector</code> that calculates average of long-valued input elements.
 @param mapper the mapping function which extracts value from element to calculate result
 @return a <code>Collector</code>
 @since 1.1.3
 */
+ (id<CASCollector>)averagingLongWithCASToLongFunction:(id<CASToLongFunction>)mapper;

/*!
 @brief Returns a <code>Collector</code> that performs additional transformation.
 @param c the input <code>Collector</code>
 @param finisher the final transformation function
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)collectingAndThenWithCASCollector:(id<CASCollector>)c
                                      withCASFunction:(id<CASFunction>)finisher;

/*!
 @brief Returns a <code>Collector</code> that counts the number of input elements.
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)counting;

/*!
 @brief Returns a <code>Collector</code> that filters input elements.
 @param predicate a predicate used to filter elements
 @param downstream the collector of filtered elements
 @return a <code>Collector</code>
 @since 1.1.3
 */
+ (id<CASCollector>)filteringWithCASPredicate:(id<CASPredicate>)predicate
                             withCASCollector:(id<CASCollector>)downstream;

/*!
 @brief Returns a <code>Collector</code> that performs flat-mapping before accumulation.
 @param mapper a function that performs flat-mapping to input elements
 @param downstream the collector of flat-mapped elements
 @return a <code>Collector</code>
 @since 1.1.3
 */
+ (id<CASCollector>)flatMappingWithCASFunction:(id<CASFunction>)mapper
                              withCASCollector:(id<CASCollector>)downstream;

/*!
 @brief Returns a <code>Collector</code> that performs grouping operation by given classifier.
 @param classifier the classifier function
 @return a <code>Collector</code>
 - seealso: #groupingBy(com.annimon.stream.function.Function, com.annimon.stream.Collector)
 - seealso: #groupingBy(com.annimon.stream.function.Function, com.annimon.stream.function.Supplier, com.annimon.stream.Collector)
 */
+ (id<CASCollector>)groupingByWithCASFunction:(id<CASFunction>)classifier;

/*!
 @brief Returns a <code>Collector</code> that performs grouping operation by given classifier.
 @param classifier the classifier function
 @param downstream the collector of mapped elements
 @return a <code>Collector</code>
 - seealso: #groupingBy(com.annimon.stream.function.Function)
 - seealso: #groupingBy(com.annimon.stream.function.Function, com.annimon.stream.function.Supplier, com.annimon.stream.Collector)
 */
+ (id<CASCollector>)groupingByWithCASFunction:(id<CASFunction>)classifier
                             withCASCollector:(id<CASCollector>)downstream;

/*!
 @brief Returns a <code>Collector</code> that performs grouping operation by given classifier.
 @param classifier the classifier function
 @param mapFactory a supplier function that provides new <code>Map</code>
 @param downstream the collector of mapped elements
 @return a <code>Collector</code>
 - seealso: #groupingBy(com.annimon.stream.function.Function)
 - seealso: #groupingBy(com.annimon.stream.function.Function, com.annimon.stream.Collector)
 */
+ (id<CASCollector>)groupingByWithCASFunction:(id<CASFunction>)classifier
                              withCASSupplier:(id<CASSupplier>)mapFactory
                             withCASCollector:(id<CASCollector>)downstream;

/*!
 @brief Returns a <code>Collector</code> that concatenates input elements into new string.
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)joining;

/*!
 @brief Returns a <code>Collector</code> that concatenates input elements into new string.
 @param delimiter the delimiter between each element
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)joiningWithJavaLangCharSequence:(id<JavaLangCharSequence>)delimiter;

/*!
 @brief Returns a <code>Collector</code> that concatenates input elements into new string.
 @param delimiter the delimiter between each element
 @param prefix the prefix of result
 @param suffix the suffix of result
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)joiningWithJavaLangCharSequence:(id<JavaLangCharSequence>)delimiter
                           withJavaLangCharSequence:(id<JavaLangCharSequence>)prefix
                           withJavaLangCharSequence:(id<JavaLangCharSequence>)suffix;

/*!
 @brief Returns a <code>Collector</code> that concatenates input elements into new string.
 @param delimiter the delimiter between each element
 @param prefix the prefix of result
 @param suffix the suffix of result
 @param emptyValue the string which replaces empty element if exists
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)joiningWithJavaLangCharSequence:(id<JavaLangCharSequence>)delimiter
                           withJavaLangCharSequence:(id<JavaLangCharSequence>)prefix
                           withJavaLangCharSequence:(id<JavaLangCharSequence>)suffix
                                       withNSString:(NSString *)emptyValue;

/*!
 @brief Returns a <code>Collector</code> that performs mapping before accumulation.
 @param mapper a function that performs mapping to input elements
 @param downstream the collector of mapped elements
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)mappingWithCASFunction:(id<CASFunction>)mapper
                          withCASCollector:(id<CASCollector>)downstream;

/*!
 @brief Returns a <code>Collector</code> that performs partitioning operation according to a predicate.
 The returned <code>Map</code> always contains mappings for both <code>false</code> and <code>true</code> keys.
 @param predicate a predicate used for classifying input elements
 @return a <code>Collector</code>
 @since 1.1.9
 */
+ (id<CASCollector>)partitioningByWithCASPredicate:(id<CASPredicate>)predicate;

/*!
 @brief Returns a <code>Collector</code> that performs partitioning operation according to a predicate.
 The returned <code>Map</code> always contains mappings for both <code>false</code> and <code>true</code> keys.
 @param predicate a predicate used for classifying input elements
 @param downstream the collector of partitioned elements
 @return a <code>Collector</code>
 @since 1.1.9
 */
+ (id<CASCollector>)partitioningByWithCASPredicate:(id<CASPredicate>)predicate
                                  withCASCollector:(id<CASCollector>)downstream;

/*!
 @brief Returns a <code>Collector</code> that reduces input elements.
 @param identity the initial value
 @param mapper the mapping function
 @param op the operator to reduce elements
 @return a <code>Collector</code>
 - seealso: #reducing(java.lang.Object, com.annimon.stream.function.BinaryOperator)
 */
+ (id<CASCollector>)reducingWithId:(id)identity
                   withCASFunction:(id<CASFunction>)mapper
             withCASBinaryOperator:(id<CASBinaryOperator>)op;

/*!
 @brief Returns a <code>Collector</code> that reduces input elements.
 @param identity the initial value
 @param op the operator to reduce elements
 @return a <code>Collector</code>
 - seealso: #reducing(java.lang.Object, com.annimon.stream.function.Function, com.annimon.stream.function.BinaryOperator)
 */
+ (id<CASCollector>)reducingWithId:(id)identity
             withCASBinaryOperator:(id<CASBinaryOperator>)op;

/*!
 @brief Returns a <code>Collector</code> that summing double-valued input elements.
 @param mapper the mapping function which extracts value from element to calculate result
 @return a <code>Collector</code>
 @since 1.1.3
 */
+ (id<CASCollector>)summingDoubleWithCASToDoubleFunction:(id<CASToDoubleFunction>)mapper;

/*!
 @brief Returns a <code>Collector</code> that summing integer-valued input elements.
 @param mapper the mapping function which extracts value from element to calculate result
 @return a <code>Collector</code>
 @since 1.1.3
 */
+ (id<CASCollector>)summingIntWithCASToIntFunction:(id<CASToIntFunction>)mapper;

/*!
 @brief Returns a <code>Collector</code> that summing long-valued input elements.
 @param mapper the mapping function which extracts value from element to calculate result
 @return a <code>Collector</code>
 @since 1.1.3
 */
+ (id<CASCollector>)summingLongWithCASToLongFunction:(id<CASToLongFunction>)mapper;

/*!
 @brief Returns a <code>Collector</code> that fills new <code>Collection</code>, provided by <code>collectionSupplier</code>,
  with input elements.
 @param collectionSupplier a supplier function that provides new collection
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)toCollectionWithCASSupplier:(id<CASSupplier>)collectionSupplier;

/*!
 @brief Returns a <code>Collector</code> that fills new <code>List</code> with input elements.
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)toList;

/*!
 @brief Returns a <code>Collector</code> that fills new <code>Map</code> with input elements.
 If the mapped keys contain duplicates, an <code>IllegalStateException</code> is thrown.
  Use <code>toMap(Function, Function, BinaryOperator)</code> to handle merging of the values.
 @param keyMapper a mapping function to produce keys
 @return a <code>Collector</code>
 @since 1.1.3
 - seealso: #toMap(Function, Function, BinaryOperator)
 */
+ (id<CASCollector>)toMapWithCASFunction:(id<CASFunction>)keyMapper;

/*!
 @brief Returns a <code>Collector</code> that fills new <code>Map</code> with input elements.
 If the mapped keys contain duplicates, an <code>IllegalStateException</code> is thrown.
  Use <code>toMap(Function, Function, BinaryOperator)</code> to handle merging of the values.
 @param keyMapper a mapping function to produce keys
 @param valueMapper a mapping function to produce values
 @return a <code>Collector</code>
 - seealso: #toMap(Function, Function, BinaryOperator)
 */
+ (id<CASCollector>)toMapWithCASFunction:(id<CASFunction>)keyMapper
                         withCASFunction:(id<CASFunction>)valueMapper;

/*!
 @brief Returns a <code>Collector</code> that fills new <code>Map</code> with input elements.
 If the mapped keys contain duplicates, the value mapping function is applied
  to each equal element, and the results are merged using the provided merging function.
 @param keyMapper a mapping function to produce keys
 @param valueMapper a mapping function to produce values
 @param mergeFunction a merge function, used to resolve collisions between                        values associated with the same key
 @return a <code>Collector</code>
 @since 1.2.0
 */
+ (id<CASCollector>)toMapWithCASFunction:(id<CASFunction>)keyMapper
                         withCASFunction:(id<CASFunction>)valueMapper
                   withCASBinaryOperator:(id<CASBinaryOperator>)mergeFunction;

/*!
 @brief Returns a <code>Collector</code> that fills new <code>Map</code> with input elements.
 If the mapped keys contain duplicates, the value mapping function is applied
  to each equal element, and the results are merged using the provided merging function.
 @param keyMapper a mapping function to produce keys
 @param valueMapper a mapping function to produce values
 @param mergeFunction a merge function, used to resolve collisions between                        values associated with the same key
 @param mapFactory a supplier function that provides new <code>Map</code>
 @return a <code>Collector</code>
 @since 1.2.0
 */
+ (id<CASCollector>)toMapWithCASFunction:(id<CASFunction>)keyMapper
                         withCASFunction:(id<CASFunction>)valueMapper
                   withCASBinaryOperator:(id<CASBinaryOperator>)mergeFunction
                         withCASSupplier:(id<CASSupplier>)mapFactory;

/*!
 @brief Returns a <code>Collector</code> that fills new <code>Map</code> with input elements.
 If the mapped keys contain duplicates, an <code>IllegalStateException</code> is thrown.
  Use <code>toMap(Function, Function, BinaryOperator, Supplier)</code> to handle merging of the values.
 @param keyMapper a mapping function to produce keys
 @param valueMapper a mapping function to produce values
 @param mapFactory a supplier function that provides new <code>Map</code>
 @return a <code>Collector</code>
 - seealso: #toMap(Function, Function, BinaryOperator, Supplier)
 */
+ (id<CASCollector>)toMapWithCASFunction:(id<CASFunction>)keyMapper
                         withCASFunction:(id<CASFunction>)valueMapper
                         withCASSupplier:(id<CASSupplier>)mapFactory;

/*!
 @brief Returns a <code>Collector</code> that fills new <code>Set</code> with input elements.
 @return a <code>Collector</code>
 */
+ (id<CASCollector>)toSet;

/*!
 @brief Returns a <code>Collector</code> that fills new unmodifiable <code>List</code> with input elements.
 The returned <code>Collector</code> disallows <code>null</code>s
  and throws <code>NullPointerException</code> if it is presented with a null value.
 @return a <code>Collector</code>
 @since 1.2.0
 */
+ (id<CASCollector>)toUnmodifiableList;

/*!
 @brief Returns a <code>Collector</code> that fills new unmodifiable <code>Map</code> with input elements.
 The returned <code>Collector</code> disallows <code>null</code> keys and values.
  If the mapped keys contain duplicates, an <code>IllegalStateException</code> is thrown,
  see <code>toUnmodifiableMap(Function, Function, BinaryOperator)</code>.
 @param keyMapper a mapping function to produce keys
 @param valueMapper a mapping function to produce values
 @return a <code>Collector</code>
 - seealso: #toUnmodifiableMap(Function, Function, BinaryOperator)
 @since 1.2.0
 */
+ (id<CASCollector>)toUnmodifiableMapWithCASFunction:(id<CASFunction>)keyMapper
                                     withCASFunction:(id<CASFunction>)valueMapper;

/*!
 @brief Returns a <code>Collector</code> that fills new unmodifiable <code>Map</code> with input elements.
 The returned <code>Collector</code> disallows <code>null</code> keys and values.
 @param keyMapper a mapping function to produce keys
 @param valueMapper a mapping function to produce values
 @param mergeFunction a merge function, used to resolve collisions between                        values associated with the same key
 @return a <code>Collector</code>
 @since 1.2.0
 */
+ (id<CASCollector>)toUnmodifiableMapWithCASFunction:(id<CASFunction>)keyMapper
                                     withCASFunction:(id<CASFunction>)valueMapper
                               withCASBinaryOperator:(id<CASBinaryOperator>)mergeFunction;

/*!
 @brief Returns a <code>Collector</code> that fills new unmodifiable <code>Set</code> with input elements.
 The returned <code>Collector</code> disallows <code>null</code>s
  and throws <code>NullPointerException</code> if it is presented with a null value.
  If elements contain duplicates, an arbitrary element of the duplicates is preserved.
 @return a <code>Collector</code>
 @since 1.2.0
 */
+ (id<CASCollector>)toUnmodifiableSet;

#pragma mark Package-Private

+ (id<CASFunction>)castIdentity;

@end

J2OBJC_STATIC_INIT(CASCollectors)

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toCollectionWithCASSupplier_(id<CASSupplier> collectionSupplier);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toList(void);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toUnmodifiableList(void);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toSet(void);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toUnmodifiableSet(void);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toMapWithCASFunction_(id<CASFunction> keyMapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toMapWithCASFunction_withCASFunction_(id<CASFunction> keyMapper, id<CASFunction> valueMapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toMapWithCASFunction_withCASFunction_withCASSupplier_(id<CASFunction> keyMapper, id<CASFunction> valueMapper, id<CASSupplier> mapFactory);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toUnmodifiableMapWithCASFunction_withCASFunction_(id<CASFunction> keyMapper, id<CASFunction> valueMapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toMapWithCASFunction_withCASFunction_withCASBinaryOperator_(id<CASFunction> keyMapper, id<CASFunction> valueMapper, id<CASBinaryOperator> mergeFunction);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toMapWithCASFunction_withCASFunction_withCASBinaryOperator_withCASSupplier_(id<CASFunction> keyMapper, id<CASFunction> valueMapper, id<CASBinaryOperator> mergeFunction, id<CASSupplier> mapFactory);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_toUnmodifiableMapWithCASFunction_withCASFunction_withCASBinaryOperator_(id<CASFunction> keyMapper, id<CASFunction> valueMapper, id<CASBinaryOperator> mergeFunction);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_joining(void);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_joiningWithJavaLangCharSequence_(id<JavaLangCharSequence> delimiter);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_joiningWithJavaLangCharSequence_withJavaLangCharSequence_withJavaLangCharSequence_(id<JavaLangCharSequence> delimiter, id<JavaLangCharSequence> prefix, id<JavaLangCharSequence> suffix);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_joiningWithJavaLangCharSequence_withJavaLangCharSequence_withJavaLangCharSequence_withNSString_(id<JavaLangCharSequence> delimiter, id<JavaLangCharSequence> prefix, id<JavaLangCharSequence> suffix, NSString *emptyValue);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_averagingWithCASFunction_(id<CASFunction> mapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_averagingIntWithCASToIntFunction_(id<CASToIntFunction> mapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_averagingLongWithCASToLongFunction_(id<CASToLongFunction> mapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_averagingDoubleWithCASToDoubleFunction_(id<CASToDoubleFunction> mapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_summingIntWithCASToIntFunction_(id<CASToIntFunction> mapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_summingLongWithCASToLongFunction_(id<CASToLongFunction> mapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_summingDoubleWithCASToDoubleFunction_(id<CASToDoubleFunction> mapper);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_counting(void);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_reducingWithId_withCASBinaryOperator_(id identity, id<CASBinaryOperator> op);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_reducingWithId_withCASFunction_withCASBinaryOperator_(id identity, id<CASFunction> mapper, id<CASBinaryOperator> op);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_filteringWithCASPredicate_withCASCollector_(id<CASPredicate> predicate, id<CASCollector> downstream);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_mappingWithCASFunction_withCASCollector_(id<CASFunction> mapper, id<CASCollector> downstream);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_flatMappingWithCASFunction_withCASCollector_(id<CASFunction> mapper, id<CASCollector> downstream);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_collectingAndThenWithCASCollector_withCASFunction_(id<CASCollector> c, id<CASFunction> finisher);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_groupingByWithCASFunction_(id<CASFunction> classifier);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_groupingByWithCASFunction_withCASCollector_(id<CASFunction> classifier, id<CASCollector> downstream);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_groupingByWithCASFunction_withCASSupplier_withCASCollector_(id<CASFunction> classifier, id<CASSupplier> mapFactory, id<CASCollector> downstream);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_partitioningByWithCASPredicate_(id<CASPredicate> predicate);

FOUNDATION_EXPORT id<CASCollector> CASCollectors_partitioningByWithCASPredicate_withCASCollector_(id<CASPredicate> predicate, id<CASCollector> downstream);

FOUNDATION_EXPORT id<CASFunction> CASCollectors_castIdentity(void);

J2OBJC_TYPE_LITERAL_HEADER(CASCollectors)

@compatibility_alias ComAnnimonStreamCollectors CASCollectors;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamCollectors")
