//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/ComparatorCompat.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamComparatorCompat")
#ifdef RESTRICT_ComAnnimonStreamComparatorCompat
#define INCLUDE_ALL_ComAnnimonStreamComparatorCompat 0
#else
#define INCLUDE_ALL_ComAnnimonStreamComparatorCompat 1
#endif
#undef RESTRICT_ComAnnimonStreamComparatorCompat

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASComparatorCompat_) && (INCLUDE_ALL_ComAnnimonStreamComparatorCompat || defined(INCLUDE_CASComparatorCompat))
#define CASComparatorCompat_

#define RESTRICT_JavaUtilComparator 1
#define INCLUDE_JavaUtilComparator 1
#include "java/util/Comparator.h"

@class JavaLangInteger;
@protocol CASFunction;
@protocol CASToDoubleFunction;
@protocol CASToIntFunction;
@protocol CASToLongFunction;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilFunctionToDoubleFunction;
@protocol JavaUtilFunctionToIntFunction;
@protocol JavaUtilFunctionToLongFunction;

/*!
 @brief Backported default and static methods from Java 8 <code>java.util.Comparator</code> interface.
 @since 1.1.6
 */
@interface CASComparatorCompat : NSObject < JavaUtilComparator >

#pragma mark Public

- (instancetype _Nonnull)initWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

/*!
 @brief Allows to build comparators with method chaining.
 @param comparator the comparator to be chained
 @return a <code>ComparatorCompat</code> instance
 */
+ (CASComparatorCompat *)chainWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

/*!
 @brief Returns a chained <code>Comparator</code>.
 @return a comparator
 */
- (id<JavaUtilComparator>)comparator __attribute__((deprecated));

- (int32_t)compareWithId:(id)o1
                  withId:(id)o2;

/*!
 @brief Returns a comparator that uses a function that extracts a 
 <code>java.lang.Comparable</code> sort key to be compared.
 @param keyExtractor the function that extracts the sort key
 @return a comparator
 @throw NullPointerExceptionif <code>keyExtractor</code> is null
 */
+ (CASComparatorCompat *)comparingWithCASFunction:(id<CASFunction>)keyExtractor;

/*!
 @brief Returns a comparator that uses a function that extracts a sort key
  to be compared with the specified comparator.
 @param keyExtractor the function that extracts the sort key
 @param keyComparator the comparator used to compare the sort key
 @return a comparator
 @throw NullPointerExceptionif <code>keyExtractor</code> or <code>keyComparator</code> is null
 */
+ (CASComparatorCompat *)comparingWithCASFunction:(id<CASFunction>)keyExtractor
                           withJavaUtilComparator:(id<JavaUtilComparator>)keyComparator;

/*!
 @brief Returns a comparator that uses a function that extracts a 
 <code>double</code> sort key to be compared.
 @param keyExtractor the function that extracts the sort key
 @return a comparator
 @throw NullPointerExceptionif <code>keyExtractor</code> is null
 */
+ (CASComparatorCompat *)comparingDoubleWithCASToDoubleFunction:(id<CASToDoubleFunction>)keyExtractor;

/*!
 @brief Returns a comparator that uses a function that extracts
  an <code>int</code> sort key to be compared.
 @param keyExtractor the function that extracts the sort key
 @return a comparator
 @throw NullPointerExceptionif <code>keyExtractor</code> is null
 */
+ (CASComparatorCompat *)comparingIntWithCASToIntFunction:(id<CASToIntFunction>)keyExtractor;

/*!
 @brief Returns a comparator that uses a function that extracts a 
 <code>long</code> sort key to be compared.
 @param keyExtractor the function that extracts the sort key
 @return a comparator
 @throw NullPointerExceptionif <code>keyExtractor</code> is null
 */
+ (CASComparatorCompat *)comparingLongWithCASToLongFunction:(id<CASToLongFunction>)keyExtractor;

/*!
 @brief Returns a comparator with natural order.
 @return a comparator
 */
+ (CASComparatorCompat *)naturalOrder;

/*!
 @brief Returns a comparator that considers <code>null</code> to be
  less than non-null and all non-null values to be equal.
 @return a comparator
 */
+ (CASComparatorCompat *)nullsFirst;

/*!
 @brief Returns a comparator that considers <code>null</code> to be less than non-null.
 If the specified comparator is <code>null</code>, then the returned
  comparator considers all non-null values to be equal.
 @param comparator a comparator for comparing non-null values
 @return a comparator
 */
+ (CASComparatorCompat *)nullsFirstWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

/*!
 @brief Returns a comparator that considers <code>null</code> to be
  greater than non-null and all non-null values to be equal.
 @return a comparator
 */
+ (CASComparatorCompat *)nullsLast;

/*!
 @brief Returns a comparator that considers <code>null</code> to be greater than non-null.
 If the specified comparator is <code>null</code>, then the returned
  comparator considers all non-null values to be equal.
 @param comparator a comparator for comparing non-null values
 @return a comparator
 */
+ (CASComparatorCompat *)nullsLastWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

/*!
 @brief Reverses the order of comparator.
 @return the new <code>ComparatorCompat</code> instance
 - seealso: ComparatorCompat#reverseOrder()
 */
- (CASComparatorCompat *)reversed;

/*!
 @brief Returns a comparator that reverses the order of the specified comparator.
 If the specified comparator is <code>null</code>, this method is equivalent
  to <code>reverseOrder()</code>.
 @param comparator a comparator to be reversed
 @return a comparator
 - seealso: Collections#reverseOrder(java.util.Comparator)
 @throw NullPointerExceptionif <code>comparator</code> is null
 */
+ (id<JavaUtilComparator>)reversedWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

/*!
 @brief Returns a comparator with reverse order.
 @return a comparator
 - seealso: Collections#reverseOrder()
 */
+ (CASComparatorCompat *)reverseOrder;

/*!
 @brief Adds the given comparator to the chain.
 @param other the other comparator to be used when chained                comparator compares two objects that are equal
 @return the new <code>ComparatorCompat</code> instance
 */
- (CASComparatorCompat *)thenComparingWithJavaUtilComparator:(id<JavaUtilComparator>)other;

/*!
 @brief Returns a comparator that uses <code>c2</code> comparator
  if <code>c1</code> comparator considers two elements equal.
 @param c1 a first comparator
 @param c2 a second comparator
 @return a comparator
 @throw NullPointerExceptionif <code>c1</code> or <code>c2</code> is null
 */
+ (id<JavaUtilComparator>)thenComparingWithJavaUtilComparator:(id<JavaUtilComparator>)c1
                                       withJavaUtilComparator:(id<JavaUtilComparator>)c2;

/*!
 @brief Adds the comparator, that uses a function for extract a 
 <code>java.lang.Comparable</code> sort key, to the chain.
 @param keyExtractor the function that extracts the sort key
 @return the new <code>ComparatorCompat</code> instance
 */
- (CASComparatorCompat *)thenComparingWithCASFunction:(id<CASFunction>)keyExtractor;

/*!
 @brief Adds the comparator, that uses a function for extract
  a sort key, to the chain.
 @param keyExtractor the function that extracts the sort key
 @param keyComparator the comparator used to compare the sort key
 @return the new <code>ComparatorCompat</code> instance
 */
- (CASComparatorCompat *)thenComparingWithCASFunction:(id<CASFunction>)keyExtractor
                               withJavaUtilComparator:(id<JavaUtilComparator>)keyComparator;

/*!
 @brief Adds the comparator, that uses a function for extract a 
 <code>double</code> sort key, to the chain.
 @param keyExtractor the function that extracts the sort key
 @return the new <code>ComparatorCompat</code> instance
 */
- (CASComparatorCompat *)thenComparingDoubleWithCASToDoubleFunction:(id<CASToDoubleFunction>)keyExtractor;

/*!
 @brief Adds the comparator, that uses a function for extract
  an <code>int</code> sort key, to the chain.
 @param keyExtractor the function that extracts the sort key
 @return the new <code>ComparatorCompat</code> instance
 */
- (CASComparatorCompat *)thenComparingIntWithCASToIntFunction:(id<CASToIntFunction>)keyExtractor;

/*!
 @brief Adds the comparator, that uses a function for extract a 
 <code>long</code> sort key, to the chain.
 @param keyExtractor the function that extracts the sort key
 @return the new <code>ComparatorCompat</code> instance
 */
- (CASComparatorCompat *)thenComparingLongWithCASToLongFunction:(id<CASToLongFunction>)keyExtractor;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(CASComparatorCompat)

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_naturalOrder(void);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_reverseOrder(void);

FOUNDATION_EXPORT id<JavaUtilComparator> CASComparatorCompat_reversedWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT id<JavaUtilComparator> CASComparatorCompat_thenComparingWithJavaUtilComparator_withJavaUtilComparator_(id<JavaUtilComparator> c1, id<JavaUtilComparator> c2);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_comparingWithCASFunction_withJavaUtilComparator_(id<CASFunction> keyExtractor, id<JavaUtilComparator> keyComparator);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_comparingWithCASFunction_(id<CASFunction> keyExtractor);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_comparingIntWithCASToIntFunction_(id<CASToIntFunction> keyExtractor);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_comparingLongWithCASToLongFunction_(id<CASToLongFunction> keyExtractor);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_comparingDoubleWithCASToDoubleFunction_(id<CASToDoubleFunction> keyExtractor);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_nullsFirst(void);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_nullsFirstWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_nullsLast(void);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_nullsLastWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT CASComparatorCompat *CASComparatorCompat_chainWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT void CASComparatorCompat_initWithJavaUtilComparator_(CASComparatorCompat *self, id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT CASComparatorCompat *new_CASComparatorCompat_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASComparatorCompat *create_CASComparatorCompat_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

J2OBJC_TYPE_LITERAL_HEADER(CASComparatorCompat)

@compatibility_alias ComAnnimonStreamComparatorCompat CASComparatorCompat;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamComparatorCompat")
