//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/IntStream.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamIntStream")
#ifdef RESTRICT_ComAnnimonStreamIntStream
#define INCLUDE_ALL_ComAnnimonStreamIntStream 0
#else
#define INCLUDE_ALL_ComAnnimonStreamIntStream 1
#endif
#undef RESTRICT_ComAnnimonStreamIntStream

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIntStream_) && (INCLUDE_ALL_ComAnnimonStreamIntStream || defined(INCLUDE_CASIntStream))
#define CASIntStream_

#define RESTRICT_JavaIoCloseable 1
#define INCLUDE_JavaIoCloseable 1
#include "java/io/Closeable.h"

@class CASDoubleStream;
@class CASLongStream;
@class CASOptionalInt;
@class CASParams;
@class CASPrimitiveIterator_OfInt;
@class CASStream;
@class IOSIntArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;
@protocol CASFunction;
@protocol CASIndexedIntConsumer;
@protocol CASIndexedIntPredicate;
@protocol CASIntBinaryOperator;
@protocol CASIntConsumer;
@protocol CASIntFunction;
@protocol CASIntPredicate;
@protocol CASIntSupplier;
@protocol CASIntToDoubleFunction;
@protocol CASIntToLongFunction;
@protocol CASIntUnaryOperator;
@protocol CASObjIntConsumer;
@protocol CASSupplier;
@protocol JavaLangCharSequence;
@protocol JavaLangRunnable;
@protocol JavaUtilComparator;

/*!
 @brief A sequence of primitive int-valued elements supporting sequential operations.This is the <code>int</code>
  primitive specialization of <code>Stream</code>.
 */
@interface CASIntStream : NSObject < JavaIoCloseable >

#pragma mark Public

/*!
 @brief Returns whether all elements of this stream match the provided predicate.
 May not evaluate the predicate on all elements if not necessary for
  determining the result.  If the stream is empty then <code>true</code> is
  returned and the predicate is not evaluated. 
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a == 5
  stream: [1, 2, 3, 4, 5]
  result: false
  predicate: (a) -&gt; a == 5
  stream: [5, 5, 5]
  result: true 
  
@endcode
 @param predicate a non-interfering stateless predicate to apply to                   elements of this stream
 @return <code>true</code> if either all elements of the stream match the
          provided predicate or the stream is empty, otherwise <code>false</code>
 */
- (bool)allMatchWithCASIntPredicate:(id<CASIntPredicate>)predicate;

/*!
 @brief Returns whether any elements of this stream match the provided
  predicate.May not evaluate the predicate on all elements if not
  necessary for determining the result.
 If the stream is empty then 
 <code>false</code> is returned and the predicate is not evaluated. 
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a == 5
  stream: [1, 2, 3, 4, 5]
  result: true
  predicate: (a) -&gt; a == 5
  stream: [5, 5, 5]
  result: true 
  
@endcode
 @param predicate a non-interfering stateless predicate to apply                   to elements of this stream
 @return <code>true</code> if any elements of the stream match the provided
          predicate, otherwise <code>false</code>
 */
- (bool)anyMatchWithCASIntPredicate:(id<CASIntPredicate>)predicate;

/*!
 @brief Returns a <code>Stream</code> consisting of the elements of this stream,
  each boxed to an <code>Integer</code>.
 <p>This is an lazy intermediate operation.
 @return a <code>Stream</code> consistent of the elements of this stream,
          each boxed to an <code>Integer</code>
 */
- (CASStream *)boxed;

/*!
 @brief Causes close handler to be invoked if it exists.
 Since most of the stream providers are lists or arrays,
  it is not necessary to close the stream.
 @since 1.1.8
 */
- (void)close;

/*!
 @brief Collects elements to <code>supplier</code> provided container by applying the given accumulation function.
 <p>This is a terminal operation.
 @param supplier the supplier function that provides container
 @param accumulator the accumulation function
 @return the result of collect elements
 - seealso: Stream#collect(com.annimon.stream.function.Supplier, com.annimon.stream.function.BiConsumer)
 */
- (id)collectWithCASSupplier:(id<CASSupplier>)supplier
       withCASObjIntConsumer:(id<CASObjIntConsumer>)accumulator;

/*!
 @brief Creates a lazily concatenated stream whose elements are all the
  elements of the first stream followed by all the elements of the
  second stream.
 <p>Example:
  @code

  stream a: [1, 2, 3, 4]
  stream b: [5, 6]
  result:   [1, 2, 3, 4, 5, 6] 
  
@endcode
 @param a the first stream
 @param b the second stream
 @return the concatenation of the two input streams
 @throw NullPointerExceptionif <code>a</code> or <code>b</code> is null
 */
+ (CASIntStream *)concatWithCASIntStream:(CASIntStream *)a
                        withCASIntStream:(CASIntStream *)b;

/*!
 @brief Returns the count of elements in this stream.
 <p>This is a terminal operation.
 @return the count of elements in this stream
 */
- (int64_t)count;

/*!
 @brief Applies custom operator on stream.
 Transforming function can return <code>IntStream</code> for intermediate operations,
  or any value for terminal operation. 
 <p>Operator examples: 
 @code
<code>
      // Intermediate operator
      public class Zip&lt;T&gt; implements Function&lt;IntStream, IntStream&gt; {
                  &#64;Override
          public IntStream apply(IntStream firstStream) {
              final PrimitiveIterator.OfInt it1 = firstStream.iterator();
              final PrimitiveIterator.OfInt it2 = secondStream.iterator();
              return IntStream.of(new PrimitiveIterator.OfInt() {
                                  &#64;Override
                  public boolean hasNext() {
                      return it1.hasNext() &amp;&amp; it2.hasNext();
                  }                 
                 &#64;Override
                  public int nextInt() {
                      return combiner.applyAsInt(it1.nextInt(), it2.nextInt());
                  }
              });            }            }
      // Intermediate operator based on existing stream operators
      public class SkipAndLimit implements UnaryOperator&lt;IntStream&gt; {
          private final int skip, limit;
          public SkipAndLimit(int skip, int limit) {
              this.skip = skip;
              this.limit = limit;
          }         
         &#64;Override
          public IntStream apply(IntStream stream) {
              return stream.skip(skip).limit(limit);
          }        }
      // Terminal operator
      public class Average implements Function&lt;IntStream, Double&gt; {
          long count = 0, sum = 0;         
         &#64;Override
          public Double apply(IntStream stream) {
              final PrimitiveIterator.OfInt it = stream.iterator();
              while (it.hasNext()) {
                  count++;
                  sum += it.nextInt();
              }
              return (count == 0) ? 0 : sum / (double) count;
          }        }    
  </code>
@endcode
 @param function a transforming function
 @return a result of the transforming function
 - seealso: Stream#custom(com.annimon.stream.function.Function)
 @throw NullPointerExceptionif <code>function</code> is null
 */
- (id)customWithCASFunction:(id<CASFunction>)function;

/*!
 @brief Returns a stream consisting of the distinct elements of this stream.
 <p>This is a stateful intermediate operation. 
 <p>Example:
  @code

  stream: [1, 4, 2, 3, 3, 4, 1]
  result: [1, 4, 2, 3] 
  
@endcode
 @return the new stream
 */
- (CASIntStream *)distinct;

/*!
 @brief Drops elements while the predicate is true and returns the rest.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a &lt; 3
  stream: [1, 2, 3, 4, 1, 2, 3, 4]
  result: [3, 4, 1, 2, 3, 4] 
  
@endcode
 @param predicate the predicate used to drop elements
 @return the new <code>IntStream</code>
 */
- (CASIntStream *)dropWhileWithCASIntPredicate:(id<CASIntPredicate>)predicate;

/*!
 @brief Returns an empty stream.
 @return the empty stream
 */
+ (CASIntStream *)empty;

/*!
 @brief Returns a stream consisting of the elements of this stream that match
  the given predicate.
 <p> This is an intermediate operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a &gt; 2
  stream: [1, 2, 3, 4, -8, 0, 11]
  result: [3, 4, 11] 
  
@endcode
 @param predicate non-interfering, stateless predicate to apply to each                   element to determine if it should be included
 @return the new stream
 */
- (CASIntStream *)filterWithCASIntPredicate:(id<CASIntPredicate>)predicate;

/*!
 @brief Returns an <code>IntStream</code> with elements that satisfy the given <code>IndexedIntPredicate</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  predicate: (index, value) -&gt; (index + value) &gt; 6
  stream: [1, 2, 3, 4, 0, 11]
  index:  [0, 1, 2, 3, 4,  5]
  sum:    [1, 3, 5, 7, 4, 16]
  filter: [         7,    16]
  result: [4, 11] 
  
@endcode
 @param predicate the <code>IndexedIntPredicate</code>  used to filter elements
 @return the new stream
 @since 1.2.1
 */
- (CASIntStream *)filterIndexedWithCASIndexedIntPredicate:(id<CASIndexedIntPredicate>)predicate;

/*!
 @brief Returns an <code>IntStream</code> with elements that satisfy the given <code>IndexedIntPredicate</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  from: 4
  step: 3
  predicate: (index, value) -&gt; (index + value) &gt; 15
  stream: [1, 2,  3,  4,  0, 11]
  index:  [4, 7, 10, 13, 16, 19]
  sum:    [5, 9, 13, 17, 16, 30]
  filter: [          17, 16, 30]
  result: [4, 0, 11] 
  
@endcode
 @param from the initial value of the index (inclusive)
 @param step the step of the index
 @param predicate the <code>IndexedIntPredicate</code>  used to filter elements
 @return the new stream
 @since 1.2.1
 */
- (CASIntStream *)filterIndexedWithInt:(int32_t)from
                               withInt:(int32_t)step
            withCASIndexedIntPredicate:(id<CASIndexedIntPredicate>)predicate;

/*!
 @brief Returns a stream consisting of the elements of this stream that don't
  match the given predicate.
 <p> This is an intermediate operation.
 @param predicate non-interfering, stateless predicate to apply to each                   element to determine if it should not be included
 @return the new stream
 */
- (CASIntStream *)filterNotWithCASIntPredicate:(id<CASIntPredicate>)predicate;

/*!
 @brief Returns an <code>OptionalInt</code> describing the first element of this
  stream, or an empty <code>OptionalInt</code> if the stream is empty.
 <p>This is a short-circuiting terminal operation.
 @return an <code>OptionalInt</code> describing the first element of this stream,
          or an empty <code>OptionalInt</code> if the stream is empty
 */
- (CASOptionalInt *)findFirst;

/*!
 @brief Returns the last element wrapped by <code>OptionalInt</code> class.
 If stream is empty, returns <code>OptionalInt.empty()</code>.
  
 <p>This is a short-circuiting terminal operation.
 @return an <code>OptionalInt</code> with the last element
          or <code>OptionalInt.empty()</code> if the stream is empty
 @since 1.1.8
 */
- (CASOptionalInt *)findLast;

/*!
 @brief Returns the single element wrapped by <code>OptionalInt</code> class.
 If stream is empty, returns <code>OptionalInt.empty()</code>.
  If stream contains more than one element, throws <code>IllegalStateException</code>.
  
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  stream: []
  result: OptionalInt.empty()
  stream: [1]
  result: OptionalInt.of(1)
  stream: [1, 2, 3]
  result: IllegalStateException 
  
@endcode
 @return an <code>OptionalInt</code> with single element or <code>OptionalInt.empty()</code> if stream is empty
 @throw IllegalStateExceptionif stream contains more than one element
 @since 1.1.3
 */
- (CASOptionalInt *)findSingle;

/*!
 @brief Returns a stream consisting of the results of replacing each element of
  this stream with the contents of a mapped stream produced by applying
  the provided mapping function to each element.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  mapper: (a) -&gt; [a, a + 5]
  stream: [1, 2, 3, 4]
  result: [1, 6, 2, 7, 3, 8, 4, 9] 
  
@endcode
 @param mapper a non-interfering stateless function to apply to each                element which produces an 
 <code>IntStream</code>  of new values
 @return the new stream
 - seealso: Stream#flatMap(Function)
 */
- (CASIntStream *)flatMapWithCASIntFunction:(id<CASIntFunction>)mapper;

/*!
 @brief Performs an action for each element of this stream.
 <p>This is a terminal operation.
 @param action a non-interfering action to perform on the elements
 */
- (void)forEachWithCASIntConsumer:(id<CASIntConsumer>)action;

/*!
 @brief Performs the given indexed action on each element.
 <p>This is a terminal operation.
 @param action the action to be performed on each element
 @since 1.2.1
 */
- (void)forEachIndexedWithCASIndexedIntConsumer:(id<CASIndexedIntConsumer>)action;

/*!
 @brief Performs the given indexed action on each element.
 <p>This is a terminal operation.
 @param from the initial value of the index (inclusive)
 @param step the step of the index
 @param action the action to be performed on each element
 @since 1.2.1
 */
- (void)forEachIndexedWithInt:(int32_t)from
                      withInt:(int32_t)step
    withCASIndexedIntConsumer:(id<CASIndexedIntConsumer>)action;

/*!
 @brief Returns an infinite sequential unordered stream where each element is
  generated by the provided <code>IntSupplier</code>.This is suitable for
  generating constant streams, streams of random elements, etc.
 @param s the <code>IntSupplier</code>  for generated elements
 @return a new infinite sequential <code>IntStream</code>
 @throw NullPointerExceptionif <code>s</code> is null
 */
+ (CASIntStream *)generateWithCASIntSupplier:(id<CASIntSupplier>)s;

/*!
 @brief Creates an <code>IntStream</code> by iterative application <code>IntUnaryOperator</code> function
  to an initial element <code>seed</code>, conditioned on satisfying the supplied predicate.
 <p>Example:
  @code

  seed: 0
  predicate: (a) -&gt; a &lt; 20
  f: (a) -&gt; a + 5
  result: [0, 5, 10, 15] 
  
@endcode
 @param seed the initial value
 @param predicate a predicate to determine when the stream must terminate
 @param op operator to produce new element by previous one
 @return the new stream
 @throw NullPointerExceptionif <code>op</code> is null
 @since 1.1.5
 */
+ (CASIntStream *)iterateWithInt:(int32_t)seed
             withCASIntPredicate:(id<CASIntPredicate>)predicate
         withCASIntUnaryOperator:(id<CASIntUnaryOperator>)op;

/*!
 @brief Returns an infinite sequential ordered <code>IntStream</code> produced by iterative
  application of a function <code>f</code> to an initial element <code>seed</code>,
  producing a <code>Stream</code> consisting of <code>seed</code>, <code>f(seed)</code>,
  <code>f(f(seed))</code>, etc.
 <p> The first element (position <code>0</code>) in the <code>IntStream</code> will be
  the provided <code>seed</code>.  For <code>n > 0</code>, the element at position 
 <code>n</code>, will be the result of applying the function <code>f</code> to the
  element at position <code>n - 1</code>.
  
 <p>Example:
  @code

  seed: 1
  f: (a) -&gt; a + 5
  result: [1, 6, 11, 16, ...] 
  
@endcode
 @param seed the initial element
 @param f a function to be applied to the previous element to produce           a new element
 @return a new sequential <code>IntStream</code>
 @throw NullPointerExceptionif <code>f</code> is null
 */
+ (CASIntStream *)iterateWithInt:(int32_t)seed
         withCASIntUnaryOperator:(id<CASIntUnaryOperator>)f;

/*!
 @brief Returns internal <code>IntStream</code> iterator.
 @return internal <code>IntStream</code> iterator.
 */
- (CASPrimitiveIterator_OfInt *)iterator;

/*!
 @brief Returns a stream consisting of the elements of this stream, truncated
  to be no longer than <code>maxSize</code> in length.
 <p> This is a short-circuiting stateful intermediate operation. 
 <p>Example:
  @code

  maxSize: 3
  stream: [1, 2, 3, 4, 5]
  result: [1, 2, 3]
  maxSize: 10
  stream: [1, 2]
  result: [1, 2] 
  
@endcode
 @param maxSize the number of elements the stream should be limited to
 @return the new stream
 @throw IllegalArgumentExceptionif <code>maxSize</code> is negative
 */
- (CASIntStream *)limitWithLong:(int64_t)maxSize;

/*!
 @brief Returns an <code>IntStream</code> consisting of the results of applying the given
  function to the elements of this stream.
 <p> This is an intermediate operation. 
 <p>Example:
  @code

  mapper: (a) -&gt; a + 5
  stream: [1, 2, 3, 4]
  result: [6, 7, 8, 9] 
  
@endcode
 @param mapper a non-interfering stateless function to apply to                each element
 @return the new <code>IntStream</code>
 */
- (CASIntStream *)mapWithCASIntUnaryOperator:(id<CASIntUnaryOperator>)mapper;

/*!
 @brief Returns an <code>IntStream</code> with elements that obtained by applying the given <code>IntBinaryOperator</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  from: -2
  step: 2
  mapper: (index, value) -&gt; (index * value)
  stream: [ 1, 2, 3,  4]
  index:  [-2, 0, 2,  4]
  result: [-2, 0, 6, 16] 
  
@endcode
 @param from the initial value of the index (inclusive)
 @param step the step of the index
 @param mapper the mapper function used to apply to each element
 @return the new stream
 @since 1.2.1
 */
- (CASIntStream *)mapIndexedWithInt:(int32_t)from
                            withInt:(int32_t)step
           withCASIntBinaryOperator:(id<CASIntBinaryOperator>)mapper;

/*!
 @brief Returns an <code>IntStream</code> with elements that obtained by applying the given <code>IntBinaryOperator</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  mapper: (index, value) -&gt; (index * value)
  stream: [1, 2, 3,  4]
  index:  [0, 1, 2,  3]
  result: [0, 2, 6, 12] 
  
@endcode
 @param mapper the mapper function used to apply to each element
 @return the new stream
 @since 1.2.1
 */
- (CASIntStream *)mapIndexedWithCASIntBinaryOperator:(id<CASIntBinaryOperator>)mapper;

/*!
 @brief Returns a <code>DoubleStream</code> consisting of the results of applying the given
  function to the elements of this stream.
 <p> This is an intermediate operation.
 @param mapper the mapper function used to apply to each element
 @return the new <code>DoubleStream</code>
 @since 1.1.4
 - seealso: #flatMap(com.annimon.stream.function.IntFunction)
 */
- (CASDoubleStream *)mapToDoubleWithCASIntToDoubleFunction:(id<CASIntToDoubleFunction>)mapper;

/*!
 @brief Returns a <code>LongStream</code> consisting of the results of applying the given
  function to the elements of this stream.
 <p> This is an intermediate operation.
 @param mapper the mapper function used to apply to each element
 @return the new <code>LongStream</code>
 @since 1.1.4
 - seealso: #flatMap(com.annimon.stream.function.IntFunction)
 */
- (CASLongStream *)mapToLongWithCASIntToLongFunction:(id<CASIntToLongFunction>)mapper;

/*!
 @brief Returns a <code>Stream</code> consisting of the results of applying the given
  function to the elements of this stream.
 <p> This is an intermediate operation.
 @param mapper the mapper function used to apply to each element
 @return the new <code>Stream</code>
 */
- (CASStream *)mapToObjWithCASIntFunction:(id<CASIntFunction>)mapper;

/*!
 @brief Returns an <code>OptionalInt</code> describing the maximum element of this
  stream, or an empty optional if this stream is empty.
 <p>This is a terminal operation.
 @return an <code>OptionalInt</code> containing the maximum element of this
          stream, or an empty <code>OptionalInt</code> if the stream is empty
 */
- (CASOptionalInt *)max;

/*!
 @brief Returns an <code>OptionalInt</code> describing the minimum element of this
  stream, or an empty optional if this stream is empty.
 <p>This is a terminal operation.
 @return an <code>OptionalInt</code> containing the minimum element of this
          stream, or an empty <code>OptionalInt</code> if the stream is empty
 */
- (CASOptionalInt *)min;

/*!
 @brief Returns whether no elements of this stream match the provided predicate.
 May not evaluate the predicate on all elements if not necessary for
  determining the result.  If the stream is empty then <code>true</code> is
  returned and the predicate is not evaluated. 
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a == 5
  stream: [1, 2, 3, 4, 5]
  result: false
  predicate: (a) -&gt; a == 5
  stream: [1, 2, 3]
  result: true 
  
@endcode
 @param predicate a non-interfering stateless predicate to apply to                   elements of this stream
 @return <code>true</code> if either no elements of the stream match the
          provided predicate or the stream is empty, otherwise <code>false</code>
 */
- (bool)noneMatchWithCASIntPredicate:(id<CASIntPredicate>)predicate;

/*!
 @brief Returns stream whose elements are the specified values.
 @param values the elements of the new stream
 @return the new stream
 @throw NullPointerExceptionif <code>values</code> is null
 */
+ (CASIntStream *)ofWithIntArray:(IOSIntArray *)values;

/*!
 @brief Returns stream which contains single element passed as parameter.
 @param t element of the stream
 @return the new stream
 */
+ (CASIntStream *)ofWithInt:(int32_t)t;

/*!
 @brief Creates a <code>IntStream</code> from <code>PrimitiveIterator.OfInt</code>.
 @param iterator the iterator with elements to be passed to stream
 @return the new <code>IntStream</code>
 @throw NullPointerExceptionif <code>iterator</code> is null
 */
+ (CASIntStream *)ofWithCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator;

/*!
 @brief Creates an <code>IntStream</code> of code point values from the given sequence.
 Any surrogate pairs encountered in the sequence are combined as if by Character.toCodePoint
  and the result is passed to the stream.
  Any other code units, including ordinary BMP characters, unpaired surrogates, and
  undefined code units, are zero-extended to <code>int</code> values which are then
  passed to the stream.
 @param charSequence the sequence where to get all code points values.
 @return the new stream
 @since 1.1.8
 */
+ (CASIntStream *)ofCodePointsWithJavaLangCharSequence:(id<JavaLangCharSequence>)charSequence;

/*!
 @brief Adds close handler to the current stream.
 <p>This is an intermediate operation.
 @param closeHandler an action to execute when the stream is closed
 @return the new stream with the close handler
 @since 1.1.8
 */
- (CASIntStream *)onCloseWithJavaLangRunnable:(id<JavaLangRunnable>)closeHandler;

/*!
 @brief Returns a stream consisting of the elements of this stream, additionally
  performing the provided action on each element as elements are consumed
  from the resulting stream.Handy method for debugging purposes.
 <p>This is an intermediate operation.
 @param action the action to be performed on each element
 @return the new stream
 */
- (CASIntStream *)peekWithCASIntConsumer:(id<CASIntConsumer>)action;

/*!
 @brief Returns a sequential ordered <code>IntStream</code> from <code>startInclusive</code>
  (inclusive) to <code>endExclusive</code> (exclusive) by an incremental step of 
 <code>1</code>.
 @param startInclusive the (inclusive) initial value
 @param endExclusive the exclusive upper bound
 @return a sequential <code>IntStream</code> for the range of <code>int</code>
          elements
 */
+ (CASIntStream *)rangeWithInt:(int32_t)startInclusive
                       withInt:(int32_t)endExclusive;

/*!
 @brief Returns a sequential ordered <code>IntStream</code> from <code>startInclusive</code>
  (inclusive) to <code>endInclusive</code> (inclusive) by an incremental step of 
 <code>1</code>.
 @param startInclusive the (inclusive) initial value
 @param endInclusive the inclusive upper bound
 @return a sequential <code>IntStream</code> for the range of <code>int</code>
          elements
 */
+ (CASIntStream *)rangeClosedWithInt:(int32_t)startInclusive
                             withInt:(int32_t)endInclusive;

/*!
 @brief Performs a reduction on the elements of this stream, using the provided
  identity value and an associative accumulation function, and returns the
  reduced value.
 <p>The <code>identity</code> value must be an identity for the accumulator
  function. This means that for all <code>x</code>,
  <code>accumulator.apply(identity, x)</code> is equal to <code>x</code>.
  The <code>accumulator</code> function must be an associative function. 
 <p>This is a terminal operation. 
 <p>Example:
  @code

  identity: 0
  accumulator: (a, b) -&gt; a + b
  stream: [1, 2, 3, 4, 5]
  result: 15 
  
@endcode
 @param identity the identity value for the accumulating function
 @param op an associative non-interfering stateless function for            combining two values
 @return the result of the reduction
 - seealso: #sum()
 - seealso: #min()
 - seealso: #max()
 */
- (int32_t)reduceWithInt:(int32_t)identity
withCASIntBinaryOperator:(id<CASIntBinaryOperator>)op;

/*!
 @brief Performs a reduction on the elements of this stream, using an
  associative accumulation function, and returns an <code>OptionalInt</code>
  describing the reduced value, if any.
 <p>The <code>op</code> function must be an associative function. 
 <p>This is a terminal operation.
 @param op an associative, non-interfering, stateless function for            combining two values
 @return the result of the reduction
 - seealso: #reduce(int, IntBinaryOperator)
 */
- (CASOptionalInt *)reduceWithCASIntBinaryOperator:(id<CASIntBinaryOperator>)op;

/*!
 @brief Samples the <code>IntStream</code> by emitting every n-th element.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  stepWidth: 3
  stream: [1, 2, 3, 4, 5, 6, 7, 8]
  result: [1, 4, 7] 
  
@endcode
 @param stepWidth step width
 @return the new <code>IntStream</code>
 @throw IllegalArgumentExceptionif <code>stepWidth</code> is zero or negative
 - seealso: Stream#sample(int)
 */
- (CASIntStream *)sampleWithInt:(int32_t)stepWidth;

/*!
 @brief Returns a <code>IntStream</code> produced by iterative application of a accumulation function
  to an initial element <code>identity</code> and next element of the current stream.
 Produces a <code>IntStream</code> consisting of <code>identity</code>, <code>acc(identity, value1)</code>,
  <code>acc(acc(identity, value1), value2)</code>, etc. 
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  identity: 0
  accumulator: (a, b) -&gt; a + b
  stream: [1, 2, 3, 4, 5]
  result: [0, 1, 3, 6, 10, 15] 
  
@endcode
 @param identity the initial value
 @param accumulator the accumulation function
 @return the new stream
 @throw NullPointerExceptionif <code>accumulator</code> is null
 @since 1.1.6
 */
- (CASIntStream *)scanWithInt:(int32_t)identity
     withCASIntBinaryOperator:(id<CASIntBinaryOperator>)accumulator;

/*!
 @brief Returns a <code>IntStream</code> produced by iterative application of a accumulation function
  to reduction value and next element of the current stream.
 Produces a <code>IntStream</code> consisting of <code>value1</code>, <code>acc(value1, value2)</code>,
  <code>acc(acc(value1, value2), value3)</code>, etc. 
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  accumulator: (a, b) -&gt; a + b
  stream: [1, 2, 3, 4, 5]
  result: [1, 3, 6, 10, 15] 
  
@endcode
 @param accumulator the accumulation function
 @return the new stream
 @throw NullPointerExceptionif <code>accumulator</code> is null
 @since 1.1.6
 */
- (CASIntStream *)scanWithCASIntBinaryOperator:(id<CASIntBinaryOperator>)accumulator;

/*!
 @brief Returns the single element of stream.
 If stream is empty, throws <code>NoSuchElementException</code>.
  If stream contains more than one element, throws <code>IllegalStateException</code>.
  
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  stream: []
  result: NoSuchElementException
  stream: [1]
  result: 1
  stream: [1, 2, 3]
  result: IllegalStateException 
  
@endcode
 @return single element of stream
 @throw NoSuchElementExceptionif stream is empty
 @throw IllegalStateExceptionif stream contains more than one element
 @since 1.1.3
 */
- (int32_t)single;

/*!
 @brief Returns a stream consisting of the remaining elements of this stream
  after discarding the first <code>n</code> elements of the stream.
 If this stream contains fewer than <code>n</code> elements then an
  empty stream will be returned. 
 <p>This is a stateful intermediate operation. 
 <p>Example:
  @code

  n: 3
  stream: [1, 2, 3, 4, 5]
  result: [4, 5]
  n: 10
  stream: [1, 2]
  result: [] 
  
@endcode
 @param n the number of leading elements to skip
 @return the new stream
 @throw IllegalArgumentExceptionif <code>n</code> is negative
 */
- (CASIntStream *)skipWithLong:(int64_t)n;

/*!
 @brief Returns a stream consisting of the elements of this stream in sorted
  order.
 <p>This is a stateful intermediate operation. 
 <p>Example:
  @code

  stream: [3, 4, 1, 2]
  result: [1, 2, 3, 4] 
  
@endcode
 @return the new stream
 */
- (CASIntStream *)sorted;

/*!
 @brief Returns <code>IntStream</code> with sorted elements (as determinated by provided <code>Comparator</code>).
 <p>This is a stateful intermediate operation. 
 <p>Example:
  @code

  comparator: (a, b) -&gt; -a.compareTo(b)
  stream: [1, 2, 3, 4]
  result: [4, 3, 2, 1] 
  
@endcode
 @param comparator the <code>Comparator</code>  to compare elements
 @return the new <code>IntStream</code>
 */
- (CASIntStream *)sortedWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

/*!
 @brief Returns the sum of elements in this stream.
 @return the sum of elements in this stream
 */
- (int32_t)sum;

/*!
 @brief Takes elements while the predicate returns <code>false</code>.
 Once predicate condition is satisfied by an element, the stream
  finishes with this element. 
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  stopPredicate: (a) -&gt; a &gt; 2
  stream: [1, 2, 3, 4, 1, 2, 3, 4]
  result: [1, 2, 3] 
  
@endcode
 @param stopPredicate the predicate used to take elements
 @return the new <code>IntStream</code>
 @since 1.1.6
 */
- (CASIntStream *)takeUntilWithCASIntPredicate:(id<CASIntPredicate>)stopPredicate;

/*!
 @brief Takes elements while the predicate returns <code>true</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a &lt; 3
  stream: [1, 2, 3, 4, 1, 2, 3, 4]
  result: [1, 2] 
  
@endcode
 @param predicate the predicate used to take elements
 @return the new <code>IntStream</code>
 */
- (CASIntStream *)takeWhileWithCASIntPredicate:(id<CASIntPredicate>)predicate;

/*!
 @brief Returns an array containing the elements of this stream.
 <p>This is a terminal operation.
 @return an array containing the elements of this stream
 */
- (IOSIntArray *)toArray;

#pragma mark Package-Private

- (instancetype _Nonnull)initWithCASParams:(CASParams *)params
            withCASPrimitiveIterator_OfInt:(CASPrimitiveIterator_OfInt *)iterator;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(CASIntStream)

FOUNDATION_EXPORT CASIntStream *CASIntStream_empty(void);

FOUNDATION_EXPORT CASIntStream *CASIntStream_ofWithCASPrimitiveIterator_OfInt_(CASPrimitiveIterator_OfInt *iterator);

FOUNDATION_EXPORT CASIntStream *CASIntStream_ofWithIntArray_(IOSIntArray *values);

FOUNDATION_EXPORT CASIntStream *CASIntStream_ofWithInt_(int32_t t);

FOUNDATION_EXPORT CASIntStream *CASIntStream_ofCodePointsWithJavaLangCharSequence_(id<JavaLangCharSequence> charSequence);

FOUNDATION_EXPORT CASIntStream *CASIntStream_rangeWithInt_withInt_(int32_t startInclusive, int32_t endExclusive);

FOUNDATION_EXPORT CASIntStream *CASIntStream_rangeClosedWithInt_withInt_(int32_t startInclusive, int32_t endInclusive);

FOUNDATION_EXPORT CASIntStream *CASIntStream_generateWithCASIntSupplier_(id<CASIntSupplier> s);

FOUNDATION_EXPORT CASIntStream *CASIntStream_iterateWithInt_withCASIntUnaryOperator_(int32_t seed, id<CASIntUnaryOperator> f);

FOUNDATION_EXPORT CASIntStream *CASIntStream_iterateWithInt_withCASIntPredicate_withCASIntUnaryOperator_(int32_t seed, id<CASIntPredicate> predicate, id<CASIntUnaryOperator> op);

FOUNDATION_EXPORT CASIntStream *CASIntStream_concatWithCASIntStream_withCASIntStream_(CASIntStream *a, CASIntStream *b);

FOUNDATION_EXPORT void CASIntStream_initWithCASParams_withCASPrimitiveIterator_OfInt_(CASIntStream *self, CASParams *params, CASPrimitiveIterator_OfInt *iterator);

FOUNDATION_EXPORT CASIntStream *new_CASIntStream_initWithCASParams_withCASPrimitiveIterator_OfInt_(CASParams *params, CASPrimitiveIterator_OfInt *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIntStream *create_CASIntStream_initWithCASParams_withCASPrimitiveIterator_OfInt_(CASParams *params, CASPrimitiveIterator_OfInt *iterator);

J2OBJC_TYPE_LITERAL_HEADER(CASIntStream)

@compatibility_alias ComAnnimonStreamIntStream CASIntStream;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamIntStream")
