//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/LongStream.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamLongStream")
#ifdef RESTRICT_ComAnnimonStreamLongStream
#define INCLUDE_ALL_ComAnnimonStreamLongStream 0
#else
#define INCLUDE_ALL_ComAnnimonStreamLongStream 1
#endif
#undef RESTRICT_ComAnnimonStreamLongStream

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASLongStream_) && (INCLUDE_ALL_ComAnnimonStreamLongStream || defined(INCLUDE_CASLongStream))
#define CASLongStream_

#define RESTRICT_JavaIoCloseable 1
#define INCLUDE_JavaIoCloseable 1
#include "java/io/Closeable.h"

@class CASDoubleStream;
@class CASIntStream;
@class CASOptionalLong;
@class CASParams;
@class CASPrimitiveIterator_OfLong;
@class CASStream;
@class IOSLongArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;
@protocol CASFunction;
@protocol CASIndexedLongConsumer;
@protocol CASIndexedLongPredicate;
@protocol CASIndexedLongUnaryOperator;
@protocol CASLongBinaryOperator;
@protocol CASLongConsumer;
@protocol CASLongFunction;
@protocol CASLongPredicate;
@protocol CASLongSupplier;
@protocol CASLongToDoubleFunction;
@protocol CASLongToIntFunction;
@protocol CASLongUnaryOperator;
@protocol CASObjLongConsumer;
@protocol CASSupplier;
@protocol JavaLangRunnable;
@protocol JavaUtilComparator;

/*!
 @brief A sequence of <code>long</code>-valued elements supporting aggregate operations.
 @since 1.1.4
 - seealso: Stream
 */
@interface CASLongStream : NSObject < JavaIoCloseable >

#pragma mark Public

/*!
 @brief Tests whether all elements match the given predicate.
 May not evaluate the predicate on all elements if not necessary for
  determining the result. If the stream is empty then <code>true</code> is
  returned and the predicate is not evaluated. 
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a == 5
  stream: [1, 2, 3, 4, 5]
  result: false
  predicate: (a) -&gt; a == 5
  stream: [5, 5, 5]
  result: true 
  
@endcode
 @param predicate the predicate used to match elements
 @return <code>true</code> if either all elements of the stream match the
          provided predicate or the stream is empty, otherwise <code>false</code>
 */
- (bool)allMatchWithCASLongPredicate:(id<CASLongPredicate>)predicate;

/*!
 @brief Tests whether all elements match the given predicate.
 May not evaluate the predicate on all elements if not necessary
  for determining the result. If the stream is empty then 
 <code>false</code> is returned and the predicate is not evaluated. 
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a == 5
  stream: [1, 2, 3, 4, 5]
  result: true
  predicate: (a) -&gt; a == 5
  stream: [5, 5, 5]
  result: true 
  
@endcode
 @param predicate the predicate used to match elements
 @return <code>true</code> if any elements of the stream match the provided
          predicate, otherwise <code>false</code>
 */
- (bool)anyMatchWithCASLongPredicate:(id<CASLongPredicate>)predicate;

/*!
 @brief Returns a <code>Stream</code> consisting of the elements of this stream,
  each boxed to an <code>Long</code>.
 <p>This is an lazy intermediate operation.
 @return a <code>Stream</code> consistent of the elements of this stream,
          each boxed to an <code>Long</code>
 */
- (CASStream *)boxed;

/*!
 @brief Causes close handler to be invoked if it exists.
 Since most of the stream providers are lists or arrays,
  it is not necessary to close the stream.
 @since 1.1.8
 */
- (void)close;

/*!
 @brief Collects elements to <code>supplier</code> provided container by applying the given accumulation function.
 <p>This is a terminal operation.
 @param supplier the supplier function that provides container
 @param accumulator the accumulation function
 @return the result of collect elements
 - seealso: Stream#collect(com.annimon.stream.function.Supplier, com.annimon.stream.function.BiConsumer)
 */
- (id)collectWithCASSupplier:(id<CASSupplier>)supplier
      withCASObjLongConsumer:(id<CASObjLongConsumer>)accumulator;

/*!
 @brief Concatenates two streams.
 <p>Example:
  @code

  stream a: [1, 2, 3, 4]
  stream b: [5, 6]
  result:   [1, 2, 3, 4, 5, 6] 
  
@endcode
 @param a the first stream
 @param b the second stream
 @return the new concatenated stream
 @throw NullPointerExceptionif <code>a</code> or <code>b</code> is null
 */
+ (CASLongStream *)concatWithCASLongStream:(CASLongStream *)a
                         withCASLongStream:(CASLongStream *)b;

/*!
 @brief Returns the count of elements in this stream.
 <p>This is a terminal operation.
 @return the count of elements in this stream
 */
- (int64_t)count;

/*!
 @brief Applies custom operator on stream.
 Transforming function can return <code>LongStream</code> for intermediate operations,
  or any value for terminal operation. 
 <p>Operator examples: 
 @code
<code>
      // Intermediate operator
      public class Zip implements Function&lt;LongStream, LongStream&gt; {
          private final LongStream secondStream;
          private final LongBinaryOperator combiner;
          public Zip(LongStream secondStream, LongBinaryOperator combiner) {
              this.secondStream = secondStream;
              this.combiner = combiner;
          }         
         &#64;Override
          public LongStream apply(LongStream firstStream) {
              final PrimitiveIterator.OfLong it1 = firstStream.iterator();
              final PrimitiveIterator.OfLong it2 = secondStream.iterator();
              return LongStream.of(new PrimitiveIterator.OfLong() {
                                  &#64;Override
                  public boolean hasNext() {
                      return it1.hasNext() &amp;&amp; it2.hasNext();
                  }                 
                 &#64;Override
                  public long nextLong() {
                      return combiner.applyAsLong(it1.nextLong(), it2.nextLong());
                  }
              });            }            }
      // Intermediate operator based on existing stream operators
      public class SkipAndLimit implements UnaryOperator&lt;LongStream&gt; {
          private final int skip, limit;
          public SkipAndLimit(int skip, int limit) {
              this.skip = skip;
              this.limit = limit;
          }         
         &#64;Override
          public LongStream apply(LongStream stream) {
              return stream.skip(skip).limit(limit);
          }        }
      // Terminal operator
      public class LongSummaryStatistics implements Function&lt;LongStream, long[]&gt; {
                  &#64;Override
          public long[] apply(LongStream stream) {
              long count = 0;
              long sum = 0;
              final PrimitiveIterator.OfLong it = stream.iterator();
              while (it.hasNext()) {
                  count++;
                  sum += it.nextLong();
              }
              return new long[] {count, sum};
          }        }    
  </code>
@endcode
 @param function a transforming function
 @return a result of the transforming function
 - seealso: Stream#custom(com.annimon.stream.function.Function)
 @throw NullPointerExceptionif <code>function</code> is null
 */
- (id)customWithCASFunction:(id<CASFunction>)function;

/*!
 @brief Returns a stream consisting of the distinct elements of this stream.
 <p>This is a stateful intermediate operation. 
 <p>Example:
  @code

  stream: [1, 4, 2, 3, 3, 4, 1]
  result: [1, 4, 2, 3] 
  
@endcode
 @return the new stream
 */
- (CASLongStream *)distinct;

/*!
 @brief Drops elements while the predicate is true and returns the rest.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a &lt; 3
  stream: [1, 2, 3, 4, 1, 2, 3, 4]
  result: [3, 4, 1, 2, 3, 4] 
  
@endcode
 @param predicate the predicate used to drop elements
 @return the new <code>LongStream</code>
 */
- (CASLongStream *)dropWhileWithCASLongPredicate:(id<CASLongPredicate>)predicate;

/*!
 @brief Returns an empty stream.
 @return the empty stream
 */
+ (CASLongStream *)empty;

/*!
 @brief Returns <code>LongStream</code> with elements that satisfy the given predicate.
 <p> This is an intermediate operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a &gt; 2
  stream: [1, 2, 3, 4, -8, 0, 11]
  result: [3, 4, 11] 
  
@endcode
 @param predicate the predicate used to filter elements
 @return the new stream
 */
- (CASLongStream *)filterWithCASLongPredicate:(id<CASLongPredicate>)predicate;

/*!
 @brief Returns a <code>LongStream</code> with elements that satisfy the given <code>IndexedLongPredicate</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  predicate: (index, value) -&gt; (index + value) &gt; 6
  stream: [1, 2, 3, 4, 0, 11]
  index:  [0, 1, 2, 3, 4,  5]
  sum:    [1, 3, 5, 7, 4, 16]
  filter: [         7,    16]
  result: [4, 11] 
  
@endcode
 @param predicate the <code>IndexedLongPredicate</code>  used to filter elements
 @return the new stream
 @since 1.2.1
 */
- (CASLongStream *)filterIndexedWithCASIndexedLongPredicate:(id<CASIndexedLongPredicate>)predicate;

/*!
 @brief Returns a <code>LongStream</code> with elements that satisfy the given <code>IndexedLongPredicate</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  from: 4
  step: 3
  predicate: (index, value) -&gt; (index + value) &gt; 15
  stream: [1, 2,  3,  4,  0, 11]
  index:  [4, 7, 10, 13, 16, 19]
  sum:    [5, 9, 13, 17, 16, 30]
  filter: [          17, 16, 30]
  result: [4, 0, 11] 
  
@endcode
 @param from the initial value of the index (inclusive)
 @param step the step of the index
 @param predicate the <code>IndexedLongPredicate</code>  used to filter elements
 @return the new stream
 @since 1.2.1
 */
- (CASLongStream *)filterIndexedWithInt:(int32_t)from
                                withInt:(int32_t)step
            withCASIndexedLongPredicate:(id<CASIndexedLongPredicate>)predicate;

/*!
 @brief Returns <code>LongStream</code> with elements that does not satisfy the given predicate.
 <p> This is an intermediate operation.
 @param predicate the predicate used to filter elements
 @return the new stream
 */
- (CASLongStream *)filterNotWithCASLongPredicate:(id<CASLongPredicate>)predicate;

/*!
 @brief Returns the first element wrapped by <code>OptionalLong</code> class.
 If stream is empty, returns <code>OptionalLong.empty()</code>.
  
 <p>This is a short-circuiting terminal operation.
 @return an <code>OptionalLong</code> with first element
          or <code>OptionalLong.empty()</code> if stream is empty
 */
- (CASOptionalLong *)findFirst;

/*!
 @brief Returns the last element wrapped by <code>OptionalLong</code> class.
 If stream is empty, returns <code>OptionalLong.empty()</code>.
  
 <p>This is a short-circuiting terminal operation.
 @return an <code>OptionalLong</code> with the last element
          or <code>OptionalLong.empty()</code> if the stream is empty
 @since 1.1.8
 */
- (CASOptionalLong *)findLast;

/*!
 @brief Returns the single element wrapped by <code>OptionalLong</code> class.
 If stream is empty, returns <code>OptionalLong.empty()</code>.
  If stream contains more than one element, throws <code>IllegalStateException</code>.
  
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  stream: []
  result: OptionalLong.empty()
  stream: [1]
  result: OptionalLong.of(1)
  stream: [1, 2, 3]
  result: IllegalStateException 
  
@endcode
 @return an <code>OptionalLong</code> with single element
          or <code>OptionalLong.empty()</code> if stream is empty
 @throw IllegalStateExceptionif stream contains more than one element
 */
- (CASOptionalLong *)findSingle;

/*!
 @brief Returns a stream consisting of the results of replacing each element of
  this stream with the contents of a mapped stream produced by applying
  the provided mapping function to each element.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  mapper: (a) -&gt; [a, a + 5]
  stream: [1, 2, 3, 4]
  result: [1, 6, 2, 7, 3, 8, 4, 9] 
  
@endcode
 @param mapper the mapper function used to apply to each element
 @return the new stream
 - seealso: Stream#flatMap(com.annimon.stream.function.Function)
 */
- (CASLongStream *)flatMapWithCASLongFunction:(id<CASLongFunction>)mapper;

/*!
 @brief Performs an action for each element of this stream.
 <p>This is a terminal operation.
 @param action the action to be performed on each element
 */
- (void)forEachWithCASLongConsumer:(id<CASLongConsumer>)action;

/*!
 @brief Performs the given indexed action on each element.
 <p>This is a terminal operation.
 @param action the action to be performed on each element
 @since 1.2.1
 */
- (void)forEachIndexedWithCASIndexedLongConsumer:(id<CASIndexedLongConsumer>)action;

/*!
 @brief Performs the given indexed action on each element.
 <p>This is a terminal operation.
 @param from the initial value of the index (inclusive)
 @param step the step of the index
 @param action the action to be performed on each element
 @since 1.2.1
 */
- (void)forEachIndexedWithInt:(int32_t)from
                      withInt:(int32_t)step
   withCASIndexedLongConsumer:(id<CASIndexedLongConsumer>)action;

/*!
 @brief Creates a <code>LongStream</code> by elements that generated by <code>LongSupplier</code>.
 @param s the <code>LongSupplier</code>  for generated elements
 @return a new infinite sequential <code>LongStream</code>
 @throw NullPointerExceptionif <code>s</code> is null
 */
+ (CASLongStream *)generateWithCASLongSupplier:(id<CASLongSupplier>)s;

/*!
 @brief Creates an <code>LongStream</code> by iterative application <code>LongUnaryOperator</code> function
  to an initial element <code>seed</code>, conditioned on satisfying the supplied predicate.
 <p>Example:
  @code

  seed: 0
  predicate: (a) -&gt; a &lt; 20
  f: (a) -&gt; a + 5
  result: [0, 5, 10, 15] 
  
@endcode
 @param seed the initial value
 @param predicate a predicate to determine when the stream must terminate
 @param op operator to produce new element by previous one
 @return the new stream
 @throw NullPointerExceptionif <code>op</code> is null
 @since 1.1.5
 */
+ (CASLongStream *)iterateWithLong:(int64_t)seed
              withCASLongPredicate:(id<CASLongPredicate>)predicate
          withCASLongUnaryOperator:(id<CASLongUnaryOperator>)op;

/*!
 @brief Creates a <code>LongStream</code> by iterative application <code>LongUnaryOperator</code> function
  to an initial element <code>seed</code>.Produces <code>LongStream</code> consisting of 
 <code>seed</code>, <code>f(seed)</code>, <code>f(f(seed))</code>, etc.
 <p> The first element (position <code>0</code>) in the <code>LongStream</code> will be
  the provided <code>seed</code>. For <code>n > 0</code>, the element at position 
 <code>n</code>, will be the result of applying the function <code>f</code> to the
  element at position <code>n - 1</code>.
  
 <p>Example:
  @code

  seed: 1
  f: (a) -&gt; a + 5
  result: [1, 6, 11, 16, ...] 
  
@endcode
 @param seed the initial element
 @param f a function to be applied to the previous element to produce a new element
 @return a new sequential <code>LongStream</code>
 @throw NullPointerExceptionif <code>f</code> is null
 */
+ (CASLongStream *)iterateWithLong:(int64_t)seed
          withCASLongUnaryOperator:(id<CASLongUnaryOperator>)f;

/*!
 @brief Returns internal <code>LongStream</code> iterator.
 @return internal <code>LongStream</code> iterator.
 */
- (CASPrimitiveIterator_OfLong *)iterator;

/*!
 @brief Returns a stream consisting of the elements of this stream, truncated
  to be no longer than <code>maxSize</code> in length.
 <p> This is a short-circuiting stateful intermediate operation. 
 <p>Example:
  @code

  maxSize: 3
  stream: [1, 2, 3, 4, 5]
  result: [1, 2, 3]
  maxSize: 10
  stream: [1, 2]
  result: [1, 2] 
  
@endcode
 @param maxSize the number of elements the stream should be limited to
 @return the new stream
 @throw IllegalArgumentExceptionif <code>maxSize</code> is negative
 */
- (CASLongStream *)limitWithLong:(int64_t)maxSize;

/*!
 @brief Returns an <code>LongStream</code> consisting of the results of applying the given
  function to the elements of this stream.
 <p> This is an intermediate operation. 
 <p>Example:
  @code

  mapper: (a) -&gt; a + 5
  stream: [1, 2, 3, 4]
  result: [6, 7, 8, 9] 
  
@endcode
 @param mapper the mapper function used to apply to each element
 @return the new stream
 - seealso: Stream#map(com.annimon.stream.function.Function)
 */
- (CASLongStream *)mapWithCASLongUnaryOperator:(id<CASLongUnaryOperator>)mapper;

/*!
 @brief Returns a <code>LongStream</code> with elements that obtained
  by applying the given <code>IndexedLongUnaryOperator</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  mapper: (index, value) -&gt; (index * value)
  stream: [1, 2, 3,  4]
  index:  [0, 1, 2,  3]
  result: [0, 2, 6, 12] 
  
@endcode
 @param mapper the mapper function used to apply to each element
 @return the new stream
 @since 1.2.1
 */
- (CASLongStream *)mapIndexedWithCASIndexedLongUnaryOperator:(id<CASIndexedLongUnaryOperator>)mapper;

/*!
 @brief Returns a <code>LongStream</code> with elements that obtained
  by applying the given <code>IndexedLongUnaryOperator</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  from: -2
  step: 2
  mapper: (index, value) -&gt; (index * value)
  stream: [ 1, 2, 3,  4]
  index:  [-2, 0, 2,  4]
  result: [-2, 0, 6, 16] 
  
@endcode
 @param from the initial value of the index (inclusive)
 @param step the step of the index
 @param mapper the mapper function used to apply to each element
 @return the new stream
 @since 1.2.1
 */
- (CASLongStream *)mapIndexedWithInt:(int32_t)from
                             withInt:(int32_t)step
     withCASIndexedLongUnaryOperator:(id<CASIndexedLongUnaryOperator>)mapper;

/*!
 @brief Returns an <code>DoubleStream</code> consisting of the results of applying the given
  function to the elements of this stream.
 <p> This is an intermediate operation.
 @param mapper the mapper function used to apply to each element
 @return the new <code>DoubleStream</code>
 */
- (CASDoubleStream *)mapToDoubleWithCASLongToDoubleFunction:(id<CASLongToDoubleFunction>)mapper;

/*!
 @brief Returns an <code>IntStream</code> consisting of the results of applying the given
  function to the elements of this stream.
 <p> This is an intermediate operation.
 @param mapper the mapper function used to apply to each element
 @return the new <code>IntStream</code>
 */
- (CASIntStream *)mapToIntWithCASLongToIntFunction:(id<CASLongToIntFunction>)mapper;

/*!
 @brief Returns a <code>Stream</code> consisting of the results of applying the given
  function to the elements of this stream.
 <p> This is an intermediate operation.
 @param mapper the mapper function used to apply to each element
 @return the new <code>Stream</code>
 */
- (CASStream *)mapToObjWithCASLongFunction:(id<CASLongFunction>)mapper;

/*!
 @brief Returns an <code>OptionalLong</code> describing the maximum element of this
  stream, or an empty optional if this stream is empty.
 <p>This is a terminal operation.
 @return the maximum element
 */
- (CASOptionalLong *)max;

/*!
 @brief Returns an <code>OptionalLong</code> describing the minimum element of this
  stream, or an empty optional if this stream is empty.
 <p>This is a terminal operation.
 @return the minimum element
 */
- (CASOptionalLong *)min;

/*!
 @brief Tests whether no elements match the given predicate.
 May not evaluate the predicate on all elements if not necessary for
  determining the result. If the stream is empty then <code>true</code> is
  returned and the predicate is not evaluated. 
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a == 5
  stream: [1, 2, 3, 4, 5]
  result: false
  predicate: (a) -&gt; a == 5
  stream: [1, 2, 3]
  result: true 
  
@endcode
 @param predicate the predicate used to match elements
 @return <code>true</code> if either no elements of the stream match the
          provided predicate or the stream is empty, otherwise <code>false</code>
 */
- (bool)noneMatchWithCASLongPredicate:(id<CASLongPredicate>)predicate;

/*!
 @brief Creates a <code>LongStream</code> from the specified values.
 @param values the elements of the new stream
 @return the new stream
 @throw NullPointerExceptionif <code>values</code> is null
 */
+ (CASLongStream *)ofWithLongArray:(IOSLongArray *)values;

/*!
 @brief Returns stream which contains single element passed as param
 @param t element of the stream
 @return the new stream
 */
+ (CASLongStream *)ofWithLong:(int64_t)t;

/*!
 @brief Creates a <code>LongStream</code> from <code>PrimitiveIterator.OfLong</code>.
 @param iterator the iterator with elements to be passed to stream
 @return the new <code>LongStream</code>
 @throw NullPointerExceptionif <code>iterator</code> is null
 */
+ (CASLongStream *)ofWithCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator;

/*!
 @brief Adds close handler to the current stream.
 <p>This is an intermediate operation.
 @param closeHandler an action to execute when the stream is closed
 @return the new stream with the close handler
 @since 1.1.8
 */
- (CASLongStream *)onCloseWithJavaLangRunnable:(id<JavaLangRunnable>)closeHandler;

/*!
 @brief Performs provided action on each element.
 <p>This is an intermediate operation.
 @param action the action to be performed on each element
 @return the new stream
 */
- (CASLongStream *)peekWithCASLongConsumer:(id<CASLongConsumer>)action;

/*!
 @brief Returns a sequential ordered <code>LongStream</code> from <code>startInclusive</code>
  (inclusive) to <code>endExclusive</code> (exclusive) by an incremental step of 
 <code>1</code>.
 @param startInclusive the (inclusive) initial value
 @param endExclusive the exclusive upper bound
 @return a sequential <code>LongStream</code> for the range of <code>long</code>
          elements
 */
+ (CASLongStream *)rangeWithLong:(int64_t)startInclusive
                        withLong:(int64_t)endExclusive;

/*!
 @brief Returns a sequential ordered <code>LongStream</code> from <code>startInclusive</code>
  (inclusive) to <code>endInclusive</code> (inclusive) by an incremental step of 
 <code>1</code>.
 @param startInclusive the (inclusive) initial value
 @param endInclusive the inclusive upper bound
 @return a sequential <code>LongStream</code> for the range of <code>long</code>
          elements
 */
+ (CASLongStream *)rangeClosedWithLong:(int64_t)startInclusive
                              withLong:(int64_t)endInclusive;

/*!
 @brief Performs a reduction on the elements of this stream, using the provided
  identity value and an associative accumulation function, and returns the
  reduced value.
 <p>The <code>identity</code> value must be an identity for the accumulator
  function. This means that for all <code>x</code>,
  <code>accumulator.apply(identity, x)</code> is equal to <code>x</code>.
  The <code>accumulator</code> function must be an associative function. 
 <p>This is a terminal operation. 
 <p>Example:
  @code

  identity: 0
  accumulator: (a, b) -&gt; a + b
  stream: [1, 2, 3, 4, 5]
  result: 15 
  
@endcode
 @param identity the identity value for the accumulating function
 @param accumulator the accumulation function
 @return the result of the reduction
 - seealso: #sum()
 - seealso: #min()
 - seealso: #max()
 */
- (int64_t)reduceWithLong:(int64_t)identity
withCASLongBinaryOperator:(id<CASLongBinaryOperator>)accumulator;

/*!
 @brief Performs a reduction on the elements of this stream, using an
  associative accumulation function, and returns an <code>OptionalLong</code>
  describing the reduced value, if any.
 <p>The <code>accumulator</code> function must be an associative function. 
 <p>This is a terminal operation.
 @param accumulator the accumulation function
 @return the result of the reduction
 - seealso: #reduce(com.annimon.stream.function.LongBinaryOperator)
 */
- (CASOptionalLong *)reduceWithCASLongBinaryOperator:(id<CASLongBinaryOperator>)accumulator;

/*!
 @brief Samples the <code>LongStream</code> by emitting every n-th element.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  stepWidth: 3
  stream: [1, 2, 3, 4, 5, 6, 7, 8]
  result: [1, 4, 7] 
  
@endcode
 @param stepWidth step width
 @return the new <code>LongStream</code>
 @throw IllegalArgumentExceptionif <code>stepWidth</code> is zero or negative
 - seealso: Stream#sample(int)
 */
- (CASLongStream *)sampleWithInt:(int32_t)stepWidth;

/*!
 @brief Returns a <code>LongStream</code> produced by iterative application of a accumulation function
  to an initial element <code>identity</code> and next element of the current stream.
 Produces a <code>LongStream</code> consisting of <code>identity</code>, <code>acc(identity, value1)</code>,
  <code>acc(acc(identity, value1), value2)</code>, etc. 
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  identity: 0
  accumulator: (a, b) -&gt; a + b
  stream: [1, 2, 3, 4, 5]
  result: [0, 1, 3, 6, 10, 15] 
  
@endcode
 @param identity the initial value
 @param accumulator the accumulation function
 @return the new stream
 @throw NullPointerExceptionif <code>accumulator</code> is null
 @since 1.1.6
 */
- (CASLongStream *)scanWithLong:(int64_t)identity
      withCASLongBinaryOperator:(id<CASLongBinaryOperator>)accumulator;

/*!
 @brief Returns a <code>LongStream</code> produced by iterative application of a accumulation function
  to reduction value and next element of the current stream.
 Produces a <code>LongStream</code> consisting of <code>value1</code>, <code>acc(value1, value2)</code>,
  <code>acc(acc(value1, value2), value3)</code>, etc. 
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  accumulator: (a, b) -&gt; a + b
  stream: [1, 2, 3, 4, 5]
  result: [1, 3, 6, 10, 15] 
  
@endcode
 @param accumulator the accumulation function
 @return the new stream
 @throw NullPointerExceptionif <code>accumulator</code> is null
 @since 1.1.6
 */
- (CASLongStream *)scanWithCASLongBinaryOperator:(id<CASLongBinaryOperator>)accumulator;

/*!
 @brief Returns the single element of stream.
 If stream is empty, throws <code>NoSuchElementException</code>.
  If stream contains more than one element, throws <code>IllegalStateException</code>.
  
 <p>This is a short-circuiting terminal operation. 
 <p>Example:
  @code

  stream: []
  result: NoSuchElementException
  stream: [1]
  result: 1
  stream: [1, 2, 3]
  result: IllegalStateException 
  
@endcode
 @return single element of stream
 @throw NoSuchElementExceptionif stream is empty
 @throw IllegalStateExceptionif stream contains more than one element
 */
- (int64_t)single;

/*!
 @brief Skips first <code>n</code> elements and returns <code>LongStream</code> with remaining elements.
 If this stream contains fewer than <code>n</code> elements, then an
  empty stream will be returned. 
 <p>This is a stateful intermediate operation. 
 <p>Example:
  @code

  n: 3
  stream: [1, 2, 3, 4, 5]
  result: [4, 5]
  n: 10
  stream: [1, 2]
  result: [] 
  
@endcode
 @param n the number of elements to skip
 @return the new stream
 @throw IllegalArgumentExceptionif <code>n</code> is negative
 */
- (CASLongStream *)skipWithLong:(int64_t)n;

/*!
 @brief Returns a stream consisting of the elements of this stream in sorted order.
 <p>This is a stateful intermediate operation. 
 <p>Example:
  @code

  stream: [3, 4, 1, 2]
  result: [1, 2, 3, 4] 
  
@endcode
 @return the new stream
 */
- (CASLongStream *)sorted;

/*!
 @brief Returns a stream consisting of the elements of this stream
  in sorted order as determinated by provided <code>Comparator</code>.
 <p>This is a stateful intermediate operation. 
 <p>Example:
  @code

  comparator: (a, b) -&gt; -a.compareTo(b)
  stream: [1, 2, 3, 4]
  result: [4, 3, 2, 1] 
  
@endcode
 @param comparator the <code>Comparator</code>  to compare elements
 @return the new <code>LongStream</code>
 */
- (CASLongStream *)sortedWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

/*!
 @brief Returns the sum of elements in this stream.
 @return the sum of elements in this stream
 */
- (int64_t)sum;

/*!
 @brief Takes elements while the predicate returns <code>false</code>.
 Once predicate condition is satisfied by an element, the stream
  finishes with this element. 
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  stopPredicate: (a) -&gt; a &gt; 2
  stream: [1, 2, 3, 4, 1, 2, 3, 4]
  result: [1, 2, 3] 
  
@endcode
 @param stopPredicate the predicate used to take elements
 @return the new <code>LongStream</code>
 @since 1.1.6
 */
- (CASLongStream *)takeUntilWithCASLongPredicate:(id<CASLongPredicate>)stopPredicate;

/*!
 @brief Takes elements while the predicate returns <code>true</code>.
 <p>This is an intermediate operation. 
 <p>Example:
  @code

  predicate: (a) -&gt; a &lt; 3
  stream: [1, 2, 3, 4, 1, 2, 3, 4]
  result: [1, 2] 
  
@endcode
 @param predicate the predicate used to take elements
 @return the new <code>LongStream</code>
 */
- (CASLongStream *)takeWhileWithCASLongPredicate:(id<CASLongPredicate>)predicate;

/*!
 @brief Returns an array containing the elements of this stream.
 <p>This is a terminal operation.
 @return an array containing the elements of this stream
 */
- (IOSLongArray *)toArray;

#pragma mark Package-Private

- (instancetype _Nonnull)initWithCASParams:(CASParams *)params
           withCASPrimitiveIterator_OfLong:(CASPrimitiveIterator_OfLong *)iterator;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(CASLongStream)

FOUNDATION_EXPORT CASLongStream *CASLongStream_empty(void);

FOUNDATION_EXPORT CASLongStream *CASLongStream_ofWithCASPrimitiveIterator_OfLong_(CASPrimitiveIterator_OfLong *iterator);

FOUNDATION_EXPORT CASLongStream *CASLongStream_ofWithLongArray_(IOSLongArray *values);

FOUNDATION_EXPORT CASLongStream *CASLongStream_ofWithLong_(int64_t t);

FOUNDATION_EXPORT CASLongStream *CASLongStream_rangeWithLong_withLong_(int64_t startInclusive, int64_t endExclusive);

FOUNDATION_EXPORT CASLongStream *CASLongStream_rangeClosedWithLong_withLong_(int64_t startInclusive, int64_t endInclusive);

FOUNDATION_EXPORT CASLongStream *CASLongStream_generateWithCASLongSupplier_(id<CASLongSupplier> s);

FOUNDATION_EXPORT CASLongStream *CASLongStream_iterateWithLong_withCASLongUnaryOperator_(int64_t seed, id<CASLongUnaryOperator> f);

FOUNDATION_EXPORT CASLongStream *CASLongStream_iterateWithLong_withCASLongPredicate_withCASLongUnaryOperator_(int64_t seed, id<CASLongPredicate> predicate, id<CASLongUnaryOperator> op);

FOUNDATION_EXPORT CASLongStream *CASLongStream_concatWithCASLongStream_withCASLongStream_(CASLongStream *a, CASLongStream *b);

FOUNDATION_EXPORT void CASLongStream_initWithCASParams_withCASPrimitiveIterator_OfLong_(CASLongStream *self, CASParams *params, CASPrimitiveIterator_OfLong *iterator);

FOUNDATION_EXPORT CASLongStream *new_CASLongStream_initWithCASParams_withCASPrimitiveIterator_OfLong_(CASParams *params, CASPrimitiveIterator_OfLong *iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASLongStream *create_CASLongStream_initWithCASParams_withCASPrimitiveIterator_OfLong_(CASParams *params, CASPrimitiveIterator_OfLong *iterator);

J2OBJC_TYPE_LITERAL_HEADER(CASLongStream)

@compatibility_alias ComAnnimonStreamLongStream CASLongStream;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamLongStream")
