//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/Objects.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamObjects")
#ifdef RESTRICT_ComAnnimonStreamObjects
#define INCLUDE_ALL_ComAnnimonStreamObjects 0
#else
#define INCLUDE_ALL_ComAnnimonStreamObjects 1
#endif
#undef RESTRICT_ComAnnimonStreamObjects

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASObjects_) && (INCLUDE_ALL_ComAnnimonStreamObjects || defined(INCLUDE_CASObjects))
#define CASObjects_

@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;
@class NSString;
@protocol CASSupplier;
@protocol JavaUtilCollection;
@protocol JavaUtilComparator;

/*!
 @brief Common operations with Object.
 */
@interface CASObjects : NSObject

#pragma mark Public

/*!
 @brief Compares two objects with provided comparator.
 @param a an object
 @param b an object
 @param c the comparator
 @return comparing result
 */
+ (int32_t)compareWithId:(id)a
                  withId:(id)b
  withJavaUtilComparator:(id<JavaUtilComparator>)c;

/*!
 @brief Compares two <code>int</code> values.
 @param x the first <code>int</code>  value
 @param y the second <code>int</code>  value
 @return comparing result
 @since 1.1.6
 */
+ (int32_t)compareIntWithInt:(int32_t)x
                     withInt:(int32_t)y;

/*!
 @brief Compares two <code>long</code> values.
 @param x the first <code>long</code>  value
 @param y the second <code>long</code>  value
 @return comparing result
 @since 1.1.6
 */
+ (int32_t)compareLongWithLong:(int64_t)x
                      withLong:(int64_t)y;

/*!
 @brief Checks deep equality of two objects.
 @param a an object
 @param b an object
 @return <code>true</code> if objects are deeply equals, <code>false</code> otherwise
 - seealso: Arrays#deepEquals(Object[], Object[])
 - seealso: Objects#equals(Object, Object)
 @since 1.2.0
 */
+ (bool)deepEqualsWithId:(id)a
                  withId:(id)b;

/*!
 @brief Checks equality of two objects.
 @param a an object
 @param b an object
 @return <code>true</code> if objects are equals, <code>false</code> otherwise
 */
+ (bool)equalsWithId:(id)a
              withId:(id)b;

/*!
 @brief Returns the hash code for objects.
 @param values the values
 @return the hash code
 */
+ (int32_t)hash__WithNSObjectArray:(IOSObjectArray *)values;

/*!
 @brief Returns the hash code of object.
 @param o an object
 @return the hash code
 */
+ (int32_t)hashCodeWithId:(id)o;

/*!
 @brief Checks that object reference is <code>null</code>.
 @param obj an object
 @return <code>true</code> if the object reference is <code>null</code>, <code>false</code> otherwise
 - seealso: Predicate
 @since 1.2.0
 */
+ (bool)isNullWithId:(id)obj;

/*!
 @brief Checks that object reference is not <code>null</code>.
 @param obj an object
 @return <code>false</code> if the object reference is <code>null</code>, <code>true</code> otherwise
 - seealso: Predicate
 - seealso: Predicate.Util#notNull()
 @since 1.2.0
 */
+ (bool)nonNullWithId:(id)obj;

/*!
 @brief Checks that object reference is not <code>null</code>.
 @param obj an object
 @return a source object if it is not <code>null</code>
 @throw NullPointerExceptionif object is <code>null</code>
 - seealso: #requireNonNull(java.lang.Object, java.lang.String)
 */
+ (id)requireNonNullWithId:(id)obj;

/*!
 @brief Checks that object reference is not <code>null</code>.
 @param obj an object
 @param message a message to be used as exception details
 @return a source object if it is not <code>null</code>
 @throw NullPointerExceptionif object is <code>null</code>
 - seealso: #requireNonNull(java.lang.Object)
 */
+ (id)requireNonNullWithId:(id)obj
              withNSString:(NSString *)message;

/*!
 @brief Checks that object reference is not <code>null</code>.
 @param obj an object
 @param messageSupplier a supplier of the detail message                          for 
 <code>NullPointerException</code> .
 @return a source object if it is not <code>null</code>
 @throw NullPointerExceptionif object is <code>null</code>
 - seealso: #requireNonNull(java.lang.Object)
 @since 1.2.0
 */
+ (id)requireNonNullWithId:(id)obj
           withCASSupplier:(id<CASSupplier>)messageSupplier;

/*!
 @brief Checks that collection and its elements are non-<code>null</code>.
 @param collection a collection to be checked for non-<code>null</code>  elements
 @return a collection
 @throw NullPointerExceptionif collection or its elements are <code>null</code>
 @since 1.2.0
 */
+ (id<JavaUtilCollection>)requireNonNullElementsWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

/*!
 @brief Returns the first object if it is non-<code>null</code>,
  returns the non-<code>null</code> second object otherwise.
 @param obj an object
 @param defaultObj a non-<code>null</code>  object to return                     if the first object is 
 <code>null</code>
 @return the first object if it is non-<code>null</code>,
          the non-<code>null</code> second object otherwise.
 @since 1.2.0
 */
+ (id)requireNonNullElseWithId:(id)obj
                        withId:(id)defaultObj;

/*!
 @brief Returns the first object if it is non-<code>null</code>,
  returns the non-<code>null</code> supplier's result otherwise.
 @param obj an object
 @param supplier a supplier to return non-<code>null</code>  object                   if first object is 
 <code>null</code>
 @return the first object if it is non-<code>null</code>,
          the non-<code>null</code> supplier's result otherwise
 @since 1.2.0
 */
+ (id)requireNonNullElseGetWithId:(id)obj
                  withCASSupplier:(id<CASSupplier>)supplier;

/*!
 @brief Returns result of calling <code>toString</code> on object or <code>nullDefault</code> if object is null.
 @param o an object
 @param nullDefault a string to return if object is null
 @return a result of calling <code>toString</code> on object or <code>nullDefault</code> if object is null.
 */
+ (NSString *)toStringWithId:(id)o
                withNSString:(NSString *)nullDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(CASObjects)

FOUNDATION_EXPORT bool CASObjects_equalsWithId_withId_(id a, id b);

FOUNDATION_EXPORT bool CASObjects_deepEqualsWithId_withId_(id a, id b);

FOUNDATION_EXPORT int32_t CASObjects_hashCodeWithId_(id o);

FOUNDATION_EXPORT int32_t CASObjects_hash__WithNSObjectArray_(IOSObjectArray *values);

FOUNDATION_EXPORT NSString *CASObjects_toStringWithId_withNSString_(id o, NSString *nullDefault);

FOUNDATION_EXPORT int32_t CASObjects_compareWithId_withId_withJavaUtilComparator_(id a, id b, id<JavaUtilComparator> c);

FOUNDATION_EXPORT int32_t CASObjects_compareIntWithInt_withInt_(int32_t x, int32_t y);

FOUNDATION_EXPORT int32_t CASObjects_compareLongWithLong_withLong_(int64_t x, int64_t y);

FOUNDATION_EXPORT id CASObjects_requireNonNullWithId_(id obj);

FOUNDATION_EXPORT id CASObjects_requireNonNullWithId_withNSString_(id obj, NSString *message);

FOUNDATION_EXPORT id CASObjects_requireNonNullWithId_withCASSupplier_(id obj, id<CASSupplier> messageSupplier);

FOUNDATION_EXPORT id CASObjects_requireNonNullElseWithId_withId_(id obj, id defaultObj);

FOUNDATION_EXPORT id CASObjects_requireNonNullElseGetWithId_withCASSupplier_(id obj, id<CASSupplier> supplier);

FOUNDATION_EXPORT id<JavaUtilCollection> CASObjects_requireNonNullElementsWithJavaUtilCollection_(id<JavaUtilCollection> collection);

FOUNDATION_EXPORT bool CASObjects_isNullWithId_(id obj);

FOUNDATION_EXPORT bool CASObjects_nonNullWithId_(id obj);

J2OBJC_TYPE_LITERAL_HEADER(CASObjects)

@compatibility_alias ComAnnimonStreamObjects CASObjects;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamObjects")
