//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/OptionalDouble.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOptionalDouble")
#ifdef RESTRICT_ComAnnimonStreamOptionalDouble
#define INCLUDE_ALL_ComAnnimonStreamOptionalDouble 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOptionalDouble 1
#endif
#undef RESTRICT_ComAnnimonStreamOptionalDouble

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASOptionalDouble_) && (INCLUDE_ALL_ComAnnimonStreamOptionalDouble || defined(INCLUDE_CASOptionalDouble))
#define CASOptionalDouble_

@class CASDoubleStream;
@class CASOptional;
@class CASOptionalInt;
@class CASOptionalLong;
@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangInteger;
@class NSString;
@protocol CASDoubleConsumer;
@protocol CASDoubleFunction;
@protocol CASDoublePredicate;
@protocol CASDoubleSupplier;
@protocol CASDoubleToIntFunction;
@protocol CASDoubleToLongFunction;
@protocol CASDoubleUnaryOperator;
@protocol CASFunction;
@protocol CASSupplier;
@protocol JavaLangRunnable;

/*!
 @brief A container object which may or may not contain a <code>double</code> value.
 @since 1.1.4
 - seealso: Optional
 */
@interface CASOptionalDouble : NSObject

#pragma mark Public

/*!
 @brief Applies custom operator on <code>OptionalDouble</code>.
 @param function a transforming function
 @return a result of the transforming function
 @throw NullPointerExceptionif <code>function</code> is null
 @since 1.1.9
 */
- (id)customWithCASFunction:(id<CASFunction>)function;

/*!
 @brief Returns an empty <code>OptionalDouble</code> instance.
 @return an empty <code>OptionalDouble</code>
 */
+ (CASOptionalDouble *)empty;

- (bool)isEqual:(id)obj;

/*!
 @brief Invokes action function if value is absent.
 @param action action that invokes if value absent
 @return this <code>OptionalDouble</code>
 */
- (CASOptionalDouble *)executeIfAbsentWithJavaLangRunnable:(id<JavaLangRunnable>)action;

/*!
 @brief Invokes consumer function with the value if present.
 This method same as <code>ifPresent</code>, but does not breaks chaining
 @param consumer consumer function
 @return this <code>OptionalDouble</code>
 - seealso: #ifPresent(com.annimon.stream.function.DoubleConsumer)
 */
- (CASOptionalDouble *)executeIfPresentWithCASDoubleConsumer:(id<CASDoubleConsumer>)consumer;

/*!
 @brief Performs filtering on inner value if it is present.
 @param predicate a predicate function
 @return this <code>OptionalDouble</code> if the value is present and matches predicate,
          otherwise an empty <code>OptionalDouble</code>
 */
- (CASOptionalDouble *)filterWithCASDoublePredicate:(id<CASDoublePredicate>)predicate;

/*!
 @brief Performs negated filtering on inner value if it is present.
 @param predicate a predicate function
 @return this <code>OptionalDouble</code> if the value is present and doesn't matches predicate,
               otherwise an empty <code>OptionalDouble</code>
 @since 1.1.9
 */
- (CASOptionalDouble *)filterNotWithCASDoublePredicate:(id<CASDoublePredicate>)predicate;

/*!
 @brief Returns an inner value if present, otherwise throws <code>NoSuchElementException</code>.
 Since 1.2.0 prefer <code>orElseThrow()</code> method as it has readable name.
 @return the inner value of this <code>OptionalDouble</code>
 @throw NoSuchElementExceptionif there is no value present
 - seealso: OptionalDouble#isPresent()
 - seealso: #orElseThrow()
 */
- (double)getAsDouble;

- (NSUInteger)hash;

/*!
 @brief Invokes consumer function with value if present, otherwise does nothing.
 @param consumer the consumer function to be executed if a value is present
 @throw NullPointerExceptionif value is present and <code>consumer</code> is null
 */
- (void)ifPresentWithCASDoubleConsumer:(id<CASDoubleConsumer>)consumer;

/*!
 @brief If a value is present, performs the given action with the value,
  otherwise performs the empty-based action.
 @param consumer the consumer function to be executed, if a value is present
 @param emptyAction the empty-based action to be performed, if no value is present
 @throw NullPointerExceptionif a value is present and the given consumer function is null,
          or no value is present and the given empty-based action is null.
 */
- (void)ifPresentOrElseWithCASDoubleConsumer:(id<CASDoubleConsumer>)consumer
                        withJavaLangRunnable:(id<JavaLangRunnable>)emptyAction;

/*!
 @brief Checks the value is not present.
 @return <code>true</code> if a value is not present, <code>false</code> otherwise
 @since 1.2.1
 */
- (bool)isEmpty;

/*!
 @brief Checks value present.
 @return <code>true</code> if a value present, <code>false</code> otherwise
 */
- (bool)isPresent;

/*!
 @brief Invokes the given mapping function on inner value if present.
 @param mapper mapping function
 @return an <code>OptionalDouble</code> with transformed value if present,
          otherwise an empty <code>OptionalDouble</code>
 @throw NullPointerExceptionif value is present and
          <code>mapper</code> is <code>null</code>
 */
- (CASOptionalDouble *)mapWithCASDoubleUnaryOperator:(id<CASDoubleUnaryOperator>)mapper;

/*!
 @brief Invokes the given mapping function on inner value if present.
 @param mapper mapping function
 @return an <code>OptionalInt</code> with transformed value if present,
          otherwise an empty <code>OptionalInt</code>
 @throw NullPointerExceptionif value is present and
          <code>mapper</code> is <code>null</code>
 */
- (CASOptionalInt *)mapToIntWithCASDoubleToIntFunction:(id<CASDoubleToIntFunction>)mapper;

/*!
 @brief Invokes the given mapping function on inner value if present.
 @param mapper mapping function
 @return an <code>OptionalLong</code> with transformed value if present,
          otherwise an empty <code>OptionalLong</code>
 @throw NullPointerExceptionif value is present and
          <code>mapper</code> is <code>null</code>
 */
- (CASOptionalLong *)mapToLongWithCASDoubleToLongFunction:(id<CASDoubleToLongFunction>)mapper;

/*!
 @brief Invokes the given mapping function on inner value if present.
 @param mapper mapping function
 @return an <code>Optional</code> with transformed value if present,
          otherwise an empty <code>Optional</code>
 @throw NullPointerExceptionif value is present and
          <code>mapper</code> is <code>null</code>
 */
- (CASOptional *)mapToObjWithCASDoubleFunction:(id<CASDoubleFunction>)mapper;

/*!
 @brief Returns an <code>OptionalDouble</code> with the specified value present.
 @param value the value to be present
 @return an <code>OptionalDouble</code> with the value present
 */
+ (CASOptionalDouble *)ofWithDouble:(double)value;

/*!
 @brief Returns an <code>OptionalDouble</code> with the specified value, or empty <code>OptionalDouble</code> if value is null.
 @param value the value which can be null
 @return an <code>OptionalDouble</code>
 @since 1.2.1
 */
+ (CASOptionalDouble *)ofNullableWithJavaLangDouble:(JavaLangDouble *)value;

/*!
 @brief Returns current <code>OptionalDouble</code> if value is present, otherwise
  returns an <code>OptionalDouble</code> produced by supplier function.
 @param supplier supplier function that produces an <code>OptionalDouble</code>  to be returned
 @return this <code>OptionalDouble</code> if value is present, otherwise
          an <code>OptionalDouble</code> produced by supplier function
 @throw NullPointerExceptionif value is not present and
          <code>supplier</code> or value produced by it is <code>null</code>
 */
- (CASOptionalDouble *)or__WithCASSupplier:(id<CASSupplier>)supplier;

/*!
 @brief Returns inner value if present, otherwise returns <code>other</code>.
 @param other the value to be returned if there is no value present
 @return the value, if present, otherwise <code>other</code>
 */
- (double)orElseWithDouble:(double)other;

/*!
 @brief Returns the value if present, otherwise returns value produced by supplier function.
 @param other supplier function that produces value if inner value is not present
 @return the value if present otherwise the result of <code>other.getAsDouble()</code>
 @throw NullPointerExceptionif value is not present and <code>other</code> is null
 */
- (double)orElseGetWithCASDoubleSupplier:(id<CASDoubleSupplier>)other;

/*!
 @brief Returns inner value if present, otherwise throws <code>NoSuchElementException</code>.
 @return inner value if present
 @throw NoSuchElementExceptionif inner value is not present
 @since 1.2.0
 */
- (double)orElseThrow;

/*!
 @brief Returns the value if present, otherwise throws an exception provided by supplier function.
 @param exceptionSupplier supplier function that produces an exception to be thrown
 @return inner value if present
 @throw Xif inner value is not present
 */
- (double)orElseThrowWithCASSupplier:(id<CASSupplier>)exceptionSupplier;

/*!
 @brief Wraps a value into <code>DoubleStream</code> if present,
  otherwise returns an empty <code>DoubleStream</code>.
 @return the optional value as an <code>DoubleStream</code>
 */
- (CASDoubleStream *)stream;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(CASOptionalDouble)

FOUNDATION_EXPORT CASOptionalDouble *CASOptionalDouble_empty(void);

FOUNDATION_EXPORT CASOptionalDouble *CASOptionalDouble_ofWithDouble_(double value);

FOUNDATION_EXPORT CASOptionalDouble *CASOptionalDouble_ofNullableWithJavaLangDouble_(JavaLangDouble *value);

J2OBJC_TYPE_LITERAL_HEADER(CASOptionalDouble)

@compatibility_alias ComAnnimonStreamOptionalDouble CASOptionalDouble;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOptionalDouble")
