//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/OptionalLong.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamOptionalLong")
#ifdef RESTRICT_ComAnnimonStreamOptionalLong
#define INCLUDE_ALL_ComAnnimonStreamOptionalLong 0
#else
#define INCLUDE_ALL_ComAnnimonStreamOptionalLong 1
#endif
#undef RESTRICT_ComAnnimonStreamOptionalLong

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASOptionalLong_) && (INCLUDE_ALL_ComAnnimonStreamOptionalLong || defined(INCLUDE_CASOptionalLong))
#define CASOptionalLong_

@class CASLongStream;
@class CASOptional;
@class CASOptionalInt;
@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;
@class NSString;
@protocol CASFunction;
@protocol CASLongConsumer;
@protocol CASLongFunction;
@protocol CASLongPredicate;
@protocol CASLongSupplier;
@protocol CASLongToIntFunction;
@protocol CASLongUnaryOperator;
@protocol CASSupplier;
@protocol JavaLangRunnable;

/*!
 @brief A container object which may or may not contain a <code>long</code> value.
 @since 1.1.4
 - seealso: Optional
 */
@interface CASOptionalLong : NSObject

#pragma mark Public

/*!
 @brief Applies custom operator on <code>OptionalLong</code>.
 @param function a transforming function
 @return a result of the transforming function
 @throw NullPointerExceptionif <code>function</code> is null
 @since 1.1.9
 */
- (id)customWithCASFunction:(id<CASFunction>)function;

/*!
 @brief Returns an empty <code>OptionalLong</code> instance.
 @return an empty <code>OptionalLong</code>
 */
+ (CASOptionalLong *)empty;

- (bool)isEqual:(id)obj;

/*!
 @brief Invokes action function if value is absent.
 @param action action that invokes if value absent
 @return this <code>OptionalLong</code>
 */
- (CASOptionalLong *)executeIfAbsentWithJavaLangRunnable:(id<JavaLangRunnable>)action;

/*!
 @brief Invokes consumer function with the value if present.
 This method same as <code>ifPresent</code>, but does not breaks chaining
 @param consumer consumer function
 @return this <code>OptionalLong</code>
 - seealso: #ifPresent(com.annimon.stream.function.LongConsumer)
 */
- (CASOptionalLong *)executeIfPresentWithCASLongConsumer:(id<CASLongConsumer>)consumer;

/*!
 @brief Performs filtering on inner value if it is present.
 @param predicate a predicate function
 @return this <code>OptionalLong</code> if the value is present and matches predicate,
          otherwise an empty <code>OptionalLong</code>
 */
- (CASOptionalLong *)filterWithCASLongPredicate:(id<CASLongPredicate>)predicate;

/*!
 @brief Performs negated filtering on inner value if it is present.
 @param predicate a predicate function
 @return this <code>OptionalLong</code> if the value is present and doesn't matches predicate,
               otherwise an empty <code>OptionalLong</code>
 @since 1.1.9
 */
- (CASOptionalLong *)filterNotWithCASLongPredicate:(id<CASLongPredicate>)predicate;

/*!
 @brief Returns an inner value if present, otherwise throws <code>NoSuchElementException</code>.
 Since 1.2.0 prefer <code>orElseThrow()</code> method as it has readable name.
 @return the inner value of this <code>OptionalLong</code>
 @throw NoSuchElementExceptionif there is no value present
 - seealso: OptionalLong#isPresent()
 - seealso: #orElseThrow()
 */
- (int64_t)getAsLong;

- (NSUInteger)hash;

/*!
 @brief Invokes consumer function with value if present, otherwise does nothing.
 @param consumer the consumer function to be executed if a value is present
 @throw NullPointerExceptionif value is present and <code>consumer</code> is null
 */
- (void)ifPresentWithCASLongConsumer:(id<CASLongConsumer>)consumer;

/*!
 @brief If a value is present, performs the given action with the value,
  otherwise performs the empty-based action.
 @param consumer the consumer function to be executed, if a value is present
 @param emptyAction the empty-based action to be performed, if no value is present
 @throw NullPointerExceptionif a value is present and the given consumer function is null,
          or no value is present and the given empty-based action is null.
 */
- (void)ifPresentOrElseWithCASLongConsumer:(id<CASLongConsumer>)consumer
                      withJavaLangRunnable:(id<JavaLangRunnable>)emptyAction;

/*!
 @brief Checks the value is not present.
 @return <code>true</code> if a value is not present, <code>false</code> otherwise
 @since 1.2.1
 */
- (bool)isEmpty;

/*!
 @brief Checks value present.
 @return <code>true</code> if a value present, <code>false</code> otherwise
 */
- (bool)isPresent;

/*!
 @brief Invokes the given mapping function on inner value if present.
 @param mapper mapping function
 @return an <code>OptionalLong</code> with transformed value if present,
          otherwise an empty <code>OptionalLong</code>
 @throw NullPointerExceptionif value is present and
          <code>mapper</code> is <code>null</code>
 */
- (CASOptionalLong *)mapWithCASLongUnaryOperator:(id<CASLongUnaryOperator>)mapper;

/*!
 @brief Invokes the given mapping function on inner value if present.
 @param mapper mapping function
 @return an <code>OptionalInt</code> with transformed value if present,
          otherwise an empty <code>OptionalInt</code>
 @throw NullPointerExceptionif value is present and
          <code>mapper</code> is <code>null</code>
 */
- (CASOptionalInt *)mapToIntWithCASLongToIntFunction:(id<CASLongToIntFunction>)mapper;

/*!
 @brief Invokes the given mapping function on inner value if present.
 @param mapper mapping function
 @return an <code>Optional</code> with transformed value if present,
          otherwise an empty <code>Optional</code>
 @throw NullPointerExceptionif value is present and
          <code>mapper</code> is <code>null</code>
 */
- (CASOptional *)mapToObjWithCASLongFunction:(id<CASLongFunction>)mapper;

/*!
 @brief Returns an <code>OptionalLong</code> with the specified value present.
 @param value the value to be present
 @return an <code>OptionalLong</code> with the value present
 */
+ (CASOptionalLong *)ofWithLong:(int64_t)value;

/*!
 @brief Returns an <code>OptionalLong</code> with the specified value, or empty <code>OptionalLong</code> if value is null.
 @param value the value which can be null
 @return an <code>OptionalLong</code>
 @since 1.2.1
 */
+ (CASOptionalLong *)ofNullableWithJavaLangLong:(JavaLangLong *)value;

/*!
 @brief Returns current <code>OptionalLong</code> if value is present, otherwise
  returns an <code>OptionalLong</code> produced by supplier function.
 @param supplier supplier function that produces an <code>OptionalLong</code>  to be returned
 @return this <code>OptionalLong</code> if value is present, otherwise
          an <code>OptionalLong</code> produced by supplier function
 @throw NullPointerExceptionif value is not present and
          <code>supplier</code> or value produced by it is <code>null</code>
 */
- (CASOptionalLong *)or__WithCASSupplier:(id<CASSupplier>)supplier;

/*!
 @brief Returns inner value if present, otherwise returns <code>other</code>.
 @param other the value to be returned if there is no value present
 @return the value, if present, otherwise <code>other</code>
 */
- (int64_t)orElseWithLong:(int64_t)other;

/*!
 @brief Returns the value if present, otherwise returns value produced by supplier function.
 @param other supplier function that produces value if inner value is not present
 @return the value if present otherwise the result of <code>other.getAsLong()</code>
 @throw NullPointerExceptionif value is not present and <code>other</code> is null
 */
- (int64_t)orElseGetWithCASLongSupplier:(id<CASLongSupplier>)other;

/*!
 @brief Returns inner value if present, otherwise throws <code>NoSuchElementException</code>.
 @return inner value if present
 @throw NoSuchElementExceptionif inner value is not present
 @since 1.2.0
 */
- (int64_t)orElseThrow;

/*!
 @brief Returns the value if present, otherwise throws an exception provided by supplier function.
 @param exceptionSupplier supplier function that produces an exception to be thrown
 @return inner value if present
 @throw Xif inner value is not present
 */
- (int64_t)orElseThrowWithCASSupplier:(id<CASSupplier>)exceptionSupplier;

/*!
 @brief Wraps a value into <code>LongStream</code> if present,
  otherwise returns an empty <code>LongStream</code>.
 @return the optional value as an <code>LongStream</code>
 */
- (CASLongStream *)stream;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(CASOptionalLong)

FOUNDATION_EXPORT CASOptionalLong *CASOptionalLong_empty(void);

FOUNDATION_EXPORT CASOptionalLong *CASOptionalLong_ofWithLong_(int64_t value);

FOUNDATION_EXPORT CASOptionalLong *CASOptionalLong_ofNullableWithJavaLangLong_(JavaLangLong *value);

J2OBJC_TYPE_LITERAL_HEADER(CASOptionalLong)

@compatibility_alias ComAnnimonStreamOptionalLong CASOptionalLong;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamOptionalLong")
