//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/iterator/IndexedIterator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamIteratorIndexedIterator")
#ifdef RESTRICT_ComAnnimonStreamIteratorIndexedIterator
#define INCLUDE_ALL_ComAnnimonStreamIteratorIndexedIterator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamIteratorIndexedIterator 1
#endif
#undef RESTRICT_ComAnnimonStreamIteratorIndexedIterator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASIndexedIterator_) && (INCLUDE_ALL_ComAnnimonStreamIteratorIndexedIterator || defined(INCLUDE_CASIndexedIterator))
#define CASIndexedIterator_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@protocol JavaUtilFunctionConsumer;

/*!
 @brief Iterator wrapper that supports indexing.
 @since 1.1.6
 */
@interface CASIndexedIterator : NSObject < JavaUtilIterator >

#pragma mark Public

- (instancetype _Nonnull)initWithInt:(int32_t)start
                             withInt:(int32_t)step
                withJavaUtilIterator:(id<JavaUtilIterator>)iterator;

- (instancetype _Nonnull)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator;

- (int32_t)getIndex;

- (bool)hasNext;

- (id)next;

- (void)remove;

// Disallowed inherited constructors, do not use.

- (instancetype _Nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(CASIndexedIterator)

FOUNDATION_EXPORT void CASIndexedIterator_initWithJavaUtilIterator_(CASIndexedIterator *self, id<JavaUtilIterator> iterator);

FOUNDATION_EXPORT CASIndexedIterator *new_CASIndexedIterator_initWithJavaUtilIterator_(id<JavaUtilIterator> iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIndexedIterator *create_CASIndexedIterator_initWithJavaUtilIterator_(id<JavaUtilIterator> iterator);

FOUNDATION_EXPORT void CASIndexedIterator_initWithInt_withInt_withJavaUtilIterator_(CASIndexedIterator *self, int32_t start, int32_t step, id<JavaUtilIterator> iterator);

FOUNDATION_EXPORT CASIndexedIterator *new_CASIndexedIterator_initWithInt_withInt_withJavaUtilIterator_(int32_t start, int32_t step, id<JavaUtilIterator> iterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT CASIndexedIterator *create_CASIndexedIterator_initWithInt_withInt_withJavaUtilIterator_(int32_t start, int32_t step, id<JavaUtilIterator> iterator);

J2OBJC_TYPE_LITERAL_HEADER(CASIndexedIterator)

@compatibility_alias ComAnnimonStreamIteratorIndexedIterator CASIndexedIterator;


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamIteratorIndexedIterator")
