//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/annimon/stream/iterator/PrimitiveExtIterator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveExtIterator")
#ifdef RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator
#define INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveExtIterator 0
#else
#define INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveExtIterator 1
#endif
#undef RESTRICT_ComAnnimonStreamIteratorPrimitiveExtIterator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CASPrimitiveExtIterator_) && (INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveExtIterator || defined(INCLUDE_CASPrimitiveExtIterator))
#define CASPrimitiveExtIterator_

/*!
 @brief Extended PrimitiveIterator for common purposes.
 */
@interface CASPrimitiveExtIterator : NSObject

@end

J2OBJC_EMPTY_STATIC_INIT(CASPrimitiveExtIterator)

J2OBJC_TYPE_LITERAL_HEADER(CASPrimitiveExtIterator)

@compatibility_alias ComAnnimonStreamIteratorPrimitiveExtIterator CASPrimitiveExtIterator;


#endif

#if !defined (CASPrimitiveExtIterator_OfInt_) && (INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveExtIterator || defined(INCLUDE_CASPrimitiveExtIterator_OfInt))
#define CASPrimitiveExtIterator_OfInt_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfInt 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangInteger;

@interface CASPrimitiveExtIterator_OfInt : CASPrimitiveIterator_OfInt {
 @public
  int32_t next_;
  bool hasNext_;
  bool isInit_;
}

#pragma mark Public

- (instancetype _Nonnull)init;

- (bool)hasNext;

- (int32_t)nextInt;

#pragma mark Protected

- (void)nextIteration;

@end

J2OBJC_EMPTY_STATIC_INIT(CASPrimitiveExtIterator_OfInt)

FOUNDATION_EXPORT void CASPrimitiveExtIterator_OfInt_init(CASPrimitiveExtIterator_OfInt *self);

J2OBJC_TYPE_LITERAL_HEADER(CASPrimitiveExtIterator_OfInt)


#endif

#if !defined (CASPrimitiveExtIterator_OfLong_) && (INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveExtIterator || defined(INCLUDE_CASPrimitiveExtIterator_OfLong))
#define CASPrimitiveExtIterator_OfLong_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfLong 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangLong;

@interface CASPrimitiveExtIterator_OfLong : CASPrimitiveIterator_OfLong {
 @public
  int64_t next_;
  bool hasNext_;
  bool isInit_;
}

#pragma mark Public

- (instancetype _Nonnull)init;

- (bool)hasNext;

- (int64_t)nextLong;

#pragma mark Protected

- (void)nextIteration;

@end

J2OBJC_EMPTY_STATIC_INIT(CASPrimitiveExtIterator_OfLong)

FOUNDATION_EXPORT void CASPrimitiveExtIterator_OfLong_init(CASPrimitiveExtIterator_OfLong *self);

J2OBJC_TYPE_LITERAL_HEADER(CASPrimitiveExtIterator_OfLong)


#endif

#if !defined (CASPrimitiveExtIterator_OfDouble_) && (INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveExtIterator || defined(INCLUDE_CASPrimitiveExtIterator_OfDouble))
#define CASPrimitiveExtIterator_OfDouble_

#define RESTRICT_ComAnnimonStreamIteratorPrimitiveIterator 1
#define INCLUDE_CASPrimitiveIterator_OfDouble 1
#include "com/annimon/stream/iterator/PrimitiveIterator.h"

@class JavaLangBoolean;
@class JavaLangDouble;

@interface CASPrimitiveExtIterator_OfDouble : CASPrimitiveIterator_OfDouble {
 @public
  double next_;
  bool hasNext_;
  bool isInit_;
}

#pragma mark Public

- (instancetype _Nonnull)init;

- (bool)hasNext;

- (double)nextDouble;

#pragma mark Protected

- (void)nextIteration;

@end

J2OBJC_EMPTY_STATIC_INIT(CASPrimitiveExtIterator_OfDouble)

FOUNDATION_EXPORT void CASPrimitiveExtIterator_OfDouble_init(CASPrimitiveExtIterator_OfDouble *self);

J2OBJC_TYPE_LITERAL_HEADER(CASPrimitiveExtIterator_OfDouble)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComAnnimonStreamIteratorPrimitiveExtIterator")
